include("${CMAKE_CURRENT_LIST_DIR}/../../dll/cmake/FlarialShims.cmake")
set(root "${CMAKE_CURRENT_BINARY_DIR}/shim-test")
flarial_write_shims("${root}" imgui minhook stb)
file(GLOB_RECURSE headers "${root}/*.h")
foreach(header IN LISTS headers)
    file(TIMESTAMP "${header}" time "%s")
    string(SHA256 key "${header}")
    set("before_${key}" "${time}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.2)
flarial_write_shims("${root}" imgui minhook stb)
foreach(header IN LISTS headers)
    file(TIMESTAMP "${header}" time "%s")
    string(SHA256 key "${header}")
    if(NOT time STREQUAL "${before_${key}}")
        message(FATAL_ERROR "unchanged shim was rewritten: ${header}")
    endif()
endforeach()
flarial_write_shims("${root}" other_imgui minhook stb)
file(READ "${root}/imgui/imgui_impl_dx12.h" content)
if(NOT content MATCHES "other_imgui/backends/imgui_impl_dx12.h")
    message(FATAL_ERROR "changed include path was not updated")
endif()
