#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Show cosmetics in game", "Cosmetics im Spiel anzeigen"},
    {"Enable Monchi Online to show cosmetics on players.", "Aktiviere Monchi Online, um Cosmetics an Spielern anzuzeigen."},
    {"World cosmetics default applied", "Standard fuer Welt-Cosmetics uebernommen"},
    {"World cosmetics are switched off. Enable the switch at the top of the Cosmetics tab to see equipped cosmetics on players.",
     "Welt-Cosmetics sind ausgeschaltet. Aktiviere den Schalter oben im Cosmetics-Tab, damit ausgeruestete Cosmetics an Spielern erscheinen."},
    {"Info displays", "Info-Anzeigen"},
    {"Client Settings", "Client-Einstellungen"},
    {"Name tag behind your name in chat, notifications and other global options.", "Namens-Tag hinter deinem Namen im Chat, Benachrichtigungen und weitere globale Optionen."},
    {"Client tag", "Client-Tag"},
    {"Shown at your own name in Better Chat, in the Tab List and above your head. With Monchi Online on, other Monchi users see it too; a change shows for you at once and reaches them after one to two minutes.",
     "Wird an deinem eigenen Namen im Better Chat, in der Tab-Liste und über deinem Kopf angezeigt. Mit Monchi Online sehen ihn auch andere Monchi-Nutzer; eine Änderung siehst du sofort, bei ihnen kommt sie nach ein bis zwei Minuten an."},
    {"Shown behind your own name in Better Chat and in the Tab List. Only you see it, nothing is sent to the server.", "Wird hinter deinem eigenen Namen im Better Chat und in der Tab-Liste angezeigt. Nur du siehst ihn, es wird nichts an den Server gesendet."},
    {"Client tag behind my name", "Client-Tag hinter meinem Namen"},
    {"Tag text", "Tag-Text"},
    {"Tag color", "Tag-Farbe"},
    {"Tag position", "Tag-Position"},
    {"Inside the name brackets", "In den Namens-Klammern"},
    {"Before the message", "Vor der Nachricht"},
    {"Tag in brackets", "Tag in Klammern"},
    {"Also in the Tab List", "Auch in der Tab-Liste"},
    {"Notifications", "Benachrichtigungen"},
    {"One switch for steady frame times: turns on System Boost, Low Latency and the Frame Limiter and pauses post effects and extras. Your old setup returns when you switch it off.", "Ein Schalter für gleichmäßige Frametimes: schaltet System Boost, Low Latency und den Frame Limiter ein und pausiert Post-Effekte und Extras. Dein altes Setup kommt zurück, sobald du ihn ausschaltest."},
    {"Pause post effects", "Post-Effekte pausieren"},
    {"Pause extras (pet, petals, games)", "Extras pausieren (Pet, Blütenblätter, Spiele)"},
    {"Maps to avoid (comma)", "Zu meidende Karten (Komma)"},
    {"Demo server", "Demo-Server"},
    {"Automatic", "Automatisch"},
    {"Slot 1", "Platz 1"},
    {"Slot 2", "Platz 2"},
    {"Slot 3", "Platz 3"},
    {"Slot 4", "Platz 4"},
    {"Slot 5", "Platz 5"},
    {"Slot 6", "Platz 6"},
    {"Slot 7", "Platz 7"},
    {"Slot 8", "Platz 8"},
    {"Slot 9", "Platz 9"},
    {"Key 1", "Taste 1"},
    {"Command 1", "Befehl 1"},
    {"Text 1", "Text 1"},
    {"Profile 1", "Profil 1"},
    {"Key 2", "Taste 2"},
    {"Command 2", "Befehl 2"},
    {"Text 2", "Text 2"},
    {"Profile 2", "Profil 2"},
    {"Key 3", "Taste 3"},
    {"Command 3", "Befehl 3"},
    {"Text 3", "Text 3"},
    {"Profile 3", "Profil 3"},
    {"Key 4", "Taste 4"},
    {"Command 4", "Befehl 4"},
    {"Text 4", "Text 4"},
    {"Profile 4", "Profil 4"},
    {"Key 5", "Taste 5"},
    {"Command 5", "Befehl 5"},
    {"Text 5", "Text 5"},
    {"Profile 5", "Profil 5"},
    {"Key 6", "Taste 6"},
    {"Command 6", "Befehl 6"},
    {"Text 6", "Text 6"},
    {"Profile 6", "Profil 6"},
    {"Key 7", "Taste 7"},
    {"Command 7", "Befehl 7"},
    {"Text 7", "Text 7"},
    {"Profile 7", "Profil 7"},
    {"Key 8", "Taste 8"},
    {"Command 8", "Befehl 8"},
    {"Text 8", "Text 8"},
    {"Profile 8", "Profil 8"},
    {"Key 9", "Taste 9"},
    {"Command 9", "Befehl 9"},
    {"Text 9", "Text 9"},
    {"Profile 9", "Profil 9"},
    {"Key 10", "Taste 10"},
    {"Command 10", "Befehl 10"},
    {"Text 10", "Text 10"},
    {"Profile 10", "Profil 10"},
    {"Key 11", "Taste 11"},
    {"Command 11", "Befehl 11"},
    {"Text 11", "Text 11"},
    {"Profile 11", "Profil 11"},
    {"Key 12", "Taste 12"},
    {"Command 12", "Befehl 12"},
    {"Text 12", "Text 12"},
    {"Profile 12", "Profil 12"},
    {"Better Chat needs game data for this version. Until then the tag only shows in the Tab List.", "Better Chat braucht Spieldaten für diese Version. Bis dahin erscheint das Tag nur in der Tab-Liste."},
    {"Turn on Better Chat", "Better Chat einschalten"},
    {"Search all modules …", "Alle Module durchsuchen …"},
    {"Type to search modules …", "Tippen, um Module zu suchen …"},
    {"{} modules · {} ready", "{} Module · {} bereit"},
    {"{} starred", "{} markiert"},
    {"Star modules to pin them here", "Markiere Module mit dem Stern, dann stehen sie hier"},
    {"Wings, capes, bandanas · free", "Flügel, Capes, Bandanas · gratis"},
    {"Language, chat tag, look", "Sprache, Chat-Tag, Aussehen"},
    {"QUICK SWITCHES", "SCHNELLSCHALTER"},
    {"Right Shift again opens the full menu · Esc closes", "Rechts-Shift noch einmal öffnet das ganze Menü · Esc schließt"},
    {"Favorites", "Favoriten"},
    {"Pick a module to see its settings", "Wähle ein Modul, um seine Einstellungen zu sehen"},
    {"Profile", "Profil"},
    {"Menu", "Menü"},
    {"Watermark", "Watermark"},
    {"Switch many modules at once. Modules that are blocked on your server or need game data stay as they are.", "Schaltet viele Module auf einmal. Module, die auf deinem Server gesperrt sind oder Spieldaten brauchen, bleiben wie sie sind."},
    {"Minimal", "Minimal"},
    {"PvP essentials", "PvP-Grundausstattung"},
    {"Everything off", "Alles aus"},
    {"Reset all HUD positions", "Alle HUD-Positionen zurücksetzen"},
    {"List", "Liste"},
    {"Show more modules", "Mehr Module anzeigen"},
    {"Adds fun extras and rarely used modules to the list.", "Fügt Spaß-Extras und selten genutzte Module zur Liste hinzu."},
    {"Your character. The 3D preview of equipped cosmetics comes with the first set.", "Deine Figur. Die 3D-Vorschau ausgerüsteter Cosmetics kommt mit dem ersten Set."},
    {"Chat & watermark", "Chat & Watermark"},
    {"About", "Über"},
    {"Wings", "Flügel"},
    {"Capes", "Capes"},
    {"Head", "Kopf"},
    {"Body", "Körper"},
    {"Feet", "Füße"},
    {"Face", "Gesicht"},
    {"Pets", "Haustiere"},
    {"Tails", "Schwänze"},
    {"Auras", "Auren"},
    {"More {}", "Mehr {}"},
    {"Language and menu", "Sprache und Menü"},
    {"Client tag and inventory mark", "Client-Tag und Inventar-Zeichen"},
    {"Colors, shapes and effects", "Farben, Formen und Effekte"},
    {"Presets and defaults for all modules", "Voreinstellungen und Standardwerte für alle Module"},
    {"Save and switch setups", "Setups speichern und wechseln"},
    {"Version, game and server", "Version, Spiel und Server"},
    {"Health Above Head", "Leben über dem Kopf"},
    {"Stays after aiming", "Bleibt nach dem Anvisieren"},
    {"Particle Filter", "Partikel-Filter"},
    {"Switches single particle effects off: critical hits, totem, a server's own effects. Play for a moment, then pick from the list of what the game has shown.", "Schaltet einzelne Partikel-Effekte ab: kritische Treffer, Totem, eigene Effekte eines Servers. Kurz spielen, dann aus der Liste dessen wählen, was das Spiel gezeigt hat."},
    {"Switch every named effect off", "Alle benannten Effekte abschalten"},
    {"Effects that are off (comma)", "Abgeschaltete Effekte (Komma)"},
    {"Waiting for the game: the list fills once you are in a world.", "Warte auf das Spiel: Die Liste füllt sich, sobald du in einer Welt bist."},
    {"Effects kept from the screen so far: {}", "Bisher vom Bildschirm ferngehaltene Effekte: {}"},
    {"No effect seen yet. Hit something or walk around, then look here again.", "Noch kein Effekt gesehen. Schlag etwas oder lauf herum und schau dann wieder hier."},
    {"Seen in this session (click to switch an effect off or on):", "In dieser Sitzung gesehen (Klick schaltet einen Effekt aus oder an):"},
    {"Screen animations off (menus open at once)", "Menü-Animationen aus (Menüs öffnen sofort)"},
    {"Game tip animations off", "Animationen der Spieltipps aus"},
    {"Darkness effect at its weakest", "Dunkelheits-Effekt so schwach wie möglich"},
    {"Lower edge stays in place (the chat grows upward)", "Unterkante bleibt stehen (der Chat wächst nach oben)"},
    {"not moved yet", "noch nicht bewegt"},
    {"Server symbols inside my chat font (rank badges)", "Server-Symbole in meiner Chat-Schrift (Rang-Abzeichen)"},
    {"This server draws its scoreboard with its own symbols. Monchi leaves the game's scoreboard as it is here.", "Dieser Server zeichnet sein Scoreboard mit eigenen Symbolen. Monchi lässt hier das Scoreboard des Spiels, wie es ist."},
    {"Newest message", "Neueste Nachricht"},
    {"At the bottom", "Unten"},
    {"At the top", "Oben"},
    {"RTSS / Afterburner is running in the game: Monchi leaves Reflex and the frame limit to it. Close RTSS to let Monchi do both.", "RTSS / Afterburner läuft im Spiel: Monchi überlässt ihm Reflex und die FPS-Grenze. RTSS schließen, damit Monchi beides macht."},
    {"Display {} Hz with a fixed rate: no cap, every frame waits for it", "Bildschirm {} Hz mit fester Rate: keine Grenze, jedes Bild wartet darauf"},
    {"NVIDIA Reflex / AMD Anti-Lag 2", "NVIDIA Reflex / AMD Anti-Lag 2"},
    {"NVIDIA Reflex Boost", "NVIDIA Reflex Boost"},
    {"Hold the FPS just under the refresh rate (G-Sync, FreeSync, smoother with VSync)", "FPS knapp unter der Bildwiederholrate halten (G-Sync, FreeSync, ruhiger mit VSync)"},
    {"Display {} Hz, frame rate held at {:.0f} FPS", "Bildschirm {} Hz, Bildrate wird bei {:.0f} FPS gehalten"},
    {"Use only one tool for Reflex and FPS limits: turn the limiter of RTSS / Afterburner off while this is on.", "Nur ein Werkzeug für Reflex und FPS-Grenzen benutzen: den Begrenzer von RTSS / Afterburner ausschalten, solange das hier an ist."},
    {"Reset to defaults", "Auf Standard zurücksetzen"},
    {"Show units", "Einheiten zeigen"},
    {"X 12 Y 64 Z -30", "X 12 Y 64 Z -30"},
    {"12 64 -30", "12 64 -30"},
    {"12, 64, -30", "12, 64, -30"},
    {"Phase name", "Name der Phase"},
    {"Phase name in front of the time", "Name der Phase vor der Zeit"},
    {"Ring size", "Größe des Rings"},
    {"Ring thickness", "Dicke des Rings"},
    {"Icon corner radius", "Eckenradius der Symbole"},
    {"Swatch size", "Größe des Farbfelds"},
    {"Round swatch", "Rundes Farbfeld"},
    {"Gap in front of the time", "Abstand vor der Zeit"},
    {"Show a note without effects", "Hinweis ohne Effekte zeigen"},
    {"Total line", "Zeile mit der Summe"},
    {"List of the shares", "Liste der Anteile"},
    {"Colored dots (off colors the text)", "Farbige Punkte (aus färbt den Text)"},
    {"Percent in front of the name", "Prozent vor dem Namen"},
    {"Hide programs below (% CPU)", "Programme ausblenden unter (% CPU)"},
    {"Programs in a dimmer color", "Programme in gedämpfter Farbe"},
    {"Text in front of the rank", "Text vor dem Rang"},
    {"Top ranks in accent color", "Oberste Ränge in Akzentfarbe"},
    {"Gap between the columns", "Abstand zwischen den Spalten"},
    {"Coordinates as", "Koordinaten als"},
    {"Text in front of each point", "Text vor jedem Punkt"},
    {"Newest point in accent color", "Neuester Punkt in Akzentfarbe"},
    {"Show a note while there is no death", "Hinweis zeigen, solange es keinen Tod gab"},
    {"Gap behind the icon", "Abstand hinter dem Symbol"},
    {"Text in front of the amount", "Text vor der Anzahl"},
    {"Show a note for an empty hand", "Hinweis bei leerer Hand zeigen"},
    {"Custom title (empty uses default)", "Eigener Titel (leer = Standard)"},
    {"Gap between slots", "Abstand zwischen den Slots"},
    {"Slot corner radius", "Eckenradius der Slots"},
    {"Slot color", "Farbe der Slots"},
    {"Draw empty slots", "Leere Slots zeichnen"},
    {"Size of the item counts", "Größe der Item-Anzahlen"},
    {"Name in accent color", "Name in Akzentfarbe"},
    {"Health value as", "Lebenswert als"},
    {"Health bar position", "Position des Lebensbalkens"},
    {"Under the name", "Unter dem Namen"},
    {"Under the text", "Unter dem Text"},
    {"Distance decimals", "Nachkommastellen der Entfernung"},
    {"Distance unit", "Einheit der Entfernung"},
    {"Separator", "Trennzeichen"},
    {"Everything in one line", "Alles in einer Zeile"},
    {"Text after the distance (empty uses default)", "Text hinter der Entfernung (leer = Standard)"},
    {"Time only", "Nur Zeit"},
    {"Name only", "Nur Name"},
    {"Name and time", "Name und Zeit"},
    {"Time unit", "Einheit der Zeit"},
    {"Time decimals", "Nachkommastellen der Zeit"},
    {"Empties", "Leert sich"},
    {"Fills", "Füllt sich"},
    {"Centered", "Mittig"},
    {"Title in accent color", "Titel in Akzentfarbe"},
    {"Gap under the title", "Abstand unter dem Titel"},
    {"Gap in front of the numbers", "Abstand vor den Zahlen"},
    {"Heart size", "Größe des Herzens"},
    {"Gap behind the heart", "Abstand hinter dem Herz"},
    {"Size of version and FPS", "Größe von Version und FPS"},
    {"Bar above the text", "Balken über dem Text"},
    {"Bar only, no text", "Nur Balken, kein Text"},
    {"Number the packs", "Pakete nummerieren"},
    {"Text in front of each pack", "Text vor jedem Paket"},
    {"Top pack in accent color", "Oberstes Paket in Akzentfarbe"},
    {"Show a note when no pack is active", "Hinweis zeigen, wenn kein Paket aktiv ist"},
    {"Performance Mode", "Leistungsmodus"},
    {"Switches Minecraft's own costly video settings off while it is on and gives them back afterwards: smooth lighting, see-through leaves, clouds, bubbles, far particles. Lighting and leaves change as chunks are loaded anew.", "Schaltet Minecrafts eigene teure Grafikeinstellungen ab, solange er an ist, und gibt sie danach zurück: weiche Beleuchtung, durchsichtige Blätter, Wolken, Blasen, ferne Partikel. Beleuchtung und Blätter ändern sich, sobald Chunks neu geladen werden."},
    {"Smooth lighting off", "Weiche Beleuchtung aus"},
    {"See-through leaves off", "Durchsichtige Blätter aus"},
    {"Clouds off", "Wolken aus"},
    {"Bubble particles off", "Blasen-Partikel aus"},
    {"Particles only close by", "Partikel nur in der Nähe"},
    {"Settings held right now: {}", "Gerade gehaltene Einstellungen: {}"},
    {"Not known on this game version: {}", "Auf dieser Spielversion unbekannt: {}"},
    {"Shows the health of players you have aimed at above their heads, as a bar, a number or both. Never for players you have not had in your crosshair.", "Zeigt das Leben von Spielern, die du anvisiert hast, über ihren Köpfen, als Balken, Zahl oder beides. Nie für Spieler, die du nicht im Fadenkreuz hattest."},
    {"Shows information the vanilla client doesn't. Only use it where the server allows it.", "Zeigt Informationen, die der normale Client nicht zeigt. Nur nutzen, wo der Server es erlaubt."},
    {"Number as", "Zahl als"},
    {"Range", "Reichweite"},
    {"Height above feet", "Höhe über den Füßen"},
    {"Also teammates", "Auch Teammitglieder"},
    {"Also mobs", "Auch Mobs"},
    {"Switch to third person", "In die dritte Person wechseln"},
    {"The game's own name tag is not available on this version, so Monchi draws it. Server colors still show, the pack font does not.", "Das Namensschild des Spiels ist auf dieser Version nicht verfügbar, darum zeichnet Monchi es selbst. Server-Farben bleiben, die Pack-Schrift nicht."},
    {"Points", "Punkte"},
    {"Bar and number", "Balken und Zahl"},
    {"Points of max", "Punkte von Maximum"},
    {"Idle", "Ruhig"},
    {"Walk", "Gehen"},
    {"Cosmetics", "Cosmetics"},
    {"Equip", "Ausrüsten"},
    {"Equipped", "Ausgerüstet"},
    {"No cosmetics installed yet. Wings, capes and bandanas arrive with the first release and will show up here.", "Noch keine Cosmetics installiert. Flügel, Capes und Bandanas kommen mit dem ersten Release und erscheinen dann hier."},
    {"Nothing in this category.", "In dieser Kategorie ist nichts."},
    {"No favorites yet. Click the star next to a module.", "Noch keine Favoriten. Klicke auf den Stern neben einem Modul."},
    {"Watermark in the inventory", "Watermark im Inventar"},
    {"Default HUD size", "Standard-Größe der HUD-Module"},
    {"Menu background blur", "Hintergrund-Unschärfe im Menü"},
    {"Blur", "Unschärfe"},
    {"Blurs the game image, always or only while a menu, the inventory or the chat is open.", "Macht das Spielbild unscharf, immer oder nur bei offenem Menü, Inventar oder Chat."},
    {"Only in menus", "Nur in Menüs"},
    {"{} · {} ready", "{} · {} bereit"},
    {"Pin modules", "Module anpinnen"},
    {"Free", "Gratis"},
    {"Language, tag, look", "Sprache, Tag, Aussehen"},
    {"Right Shift or Esc: close", "Rechts-Shift oder Esc: schließen"},
    {"Shader Packs", "Shader Packs"},
    {"Loads shaders on top of the game image, also on servers. Four looks are built in, your own .hlsl files go into the shaders folder. Only changes what you see.", "Lädt Shader über das Spielbild, auch auf Servern. Vier Looks sind eingebaut, eigene .hlsl-Dateien kommen in den Ordner shaders. Ändert nur, was du siehst."},
    {"Reload shaders", "Shader neu laden"},
    {"Open folder", "Ordner öffnen"},
    {"Shader", "Shader"},
    {"Game scheduling for render and input threads", "Spiel-Priorität für Render- und Eingabe-Thread"},
    {"Windows settings while Minecraft runs: precise timer, higher priority, no power saving, game scheduling for render and input threads. Reverted when you quit.", "Windows-Einstellungen, solange Minecraft läuft: präziser Timer, höhere Priorität, kein Energiesparen, Spiel-Priorität für Render- und Eingabe-Thread. Wird beim Beenden zurückgesetzt."},
    {"Mouse Sync", "Maus-Sync"},
    {"Detects your mouse, measures its polling rate and keeps your aim the same when you switch mice or change DPI.", "Erkennt deine Maus, misst die Abfragerate und hält dein Zielgefühl gleich, wenn du die Maus oder die DPI wechselst."},
    {"Keep my aim when the DPI changes", "Zielgefühl bei DPI-Wechsel beibehalten"},
    {"DPI (0 = use the measured one)", "DPI (0 = gemessenen Wert nehmen)"},
    {"Measuring distance (cm)", "Messstrecke (cm)"},
    {"No mouse found yet. Move your mouse.", "Noch keine Maus gefunden. Bewege die Maus."},
    {"{} Hz", "{} Hz"},
    {"measuring …", "wird gemessen …"},
    {"{} DPI", "{} DPI"},
    {"DPI unknown", "DPI unbekannt"},
    {"Mouse software running: %s. Your DPI is set there.", "Maus-Software läuft: %s. Dort stellst du deine DPI ein."},
    {"Measure DPI", "DPI messen"},
    {"Put the mouse at the left end of a ruler, then move it exactly %.0f cm to the right in a straight line and press Done.", "Setze die Maus links an ein Lineal, bewege sie genau %.0f cm gerade nach rechts und drücke Fertig."},
    {"Done", "Fertig"},
    {"Use as my reference", "Als meine Referenz nehmen"},
    {"Reference: %d DPI (the DPI your in-game sensitivity was set for).", "Referenz: %d DPI (die DPI, für die deine Spiel-Empfindlichkeit eingestellt ist)."},
    {"%d Hz is low. Raise the polling rate to 1000 Hz or more in your mouse software.", "%d Hz ist niedrig. Stelle die Abfragerate in deiner Maus-Software auf 1000 Hz oder mehr."},
    {"Very high polling rates can cost FPS in Minecraft. If it stutters, try 1000 to 2000 Hz.", "Sehr hohe Abfrageraten können in Minecraft FPS kosten. Wenn es ruckelt, probiere 1000 bis 2000 Hz."},
    {"Keeping your aim needs game data for this version. Detection and measuring work already.", "Das Zielgefühl beibehalten braucht Spieldaten für diese Version. Erkennung und Messung funktionieren schon."},
    {"Music", "Musik"},
    {"Shows what Spotify, Apple Music, Deezer or Amazon Music plays and lets you control it with keys, without leaving the game.", "Zeigt, was Spotify, Apple Music, Deezer oder Amazon Music spielt, und steuert es per Taste, ohne das Spiel zu verlassen."},
    {"No music app found. Start Spotify, Apple Music, Deezer or Amazon Music.", "Keine Musik-App gefunden. Starte Spotify, Apple Music, Deezer oder Amazon Music."},
    {"Found: %s", "Gefunden: %s"},
    {"Keys control whichever player Windows treats as active. The volume keys change the volume of the music app only, not of Minecraft.", "Die Tasten steuern den Player, den Windows als aktiv ansieht. Die Lautstärke-Tasten ändern nur die Lautstärke der Musik-App, nicht die von Minecraft."},
    {"No music", "Keine Musik"},
    {"Play / pause", "Wiedergabe / Pause"},
    {"Next song", "Nächster Song"},
    {"Previous song", "Vorheriger Song"},
    {"Music volume up", "Musik lauter"},
    {"Music volume down", "Musik leiser"},
    {"Mute music", "Musik stumm"},
    {"Slowest: {} ({:.2f} ms)", "Langsamstes: {} ({:.2f} ms)"},
    {"Slim arms (Alex model)", "Schmale Arme (Alex-Modell)"},
    {"Turn speed", "Drehgeschwindigkeit"},
    {"Animation speed", "Animationsgeschwindigkeit"},
    {"Equip a cosmetic to change its colors here.", "Rüste ein Cosmetic aus, um hier seine Farben zu ändern."},
    {"Item Tracker", "Item-Tracker"},
    {"Shows what you pick up and lose for a few seconds, for example +3 Iron Ingot or -1 Ender Pearl.",
     "Zeigt ein paar Sekunden lang, was du aufsammelst und verlierst, zum Beispiel +3 Eisenbarren oder -1 Enderperle."},
    {"Iron Ingot", "Eisenbarren"},
    {"Show for (s)", "Anzeigen für (s)"},
    {"Lines at most", "Höchstens Zeilen"},
    {"Picked up", "Aufgesammelt"},
    {"Lost", "Verloren"},
    {"Instant (no animation)", "Sofort (ohne Animation)"},
    {"Sensitivity reduction", "Empfindlichkeit senken"},
    {"Frame time", "Frametime"},
    {"Color by ping", "Farbe nach Ping"},
    {"Good", "Gut"},
    {"Okay", "Okay"},
    {"Bad", "Schlecht"},
    {"Double click fix (ms)", "Doppelklick-Schutz (ms)"},
    {"Sets the size of the game's interface, for example to 2, independent of the window size. Whole or quarter steps.",
     "Stellt die Größe der Spieloberfläche ein, zum Beispiel auf 2, unabhängig von der Fenstergröße. Ganze oder Viertelschritte."},
    {"Whole numbers only", "Nur ganze Zahlen"},
    {"Limits your clicks per second, for example for servers with a CPS limit. Can also filter the double clicks of a worn mouse switch.",
     "Begrenzt deine Klicks pro Sekunde, zum Beispiel für Server mit CPS-Grenze. Filtert auf Wunsch auch die Doppelklicks eines abgenutzten Maustasters."},
};

i18n::Table table(entries);

}
