#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Offhand key to keep available", "Offhand-Taste freihalten"},
    {"Reset after no hits (s, 0 = never)", "Zurücksetzen ohne Treffer (s, 0 = nie)"},
    {"  (demo, not sent)", "  (Demo, nicht gesendet)"},
    {"  (paused)", "  (Pause)"},
    {"  ·  ", "  ·  vor "},
    {"  ·  Best {}", "  ·  Rekord {}"},
    {"  ·  channel {}", "  ·  Kanal {}"},
    {"  ·  requested", "  ·  angefordert"},
    {"  ·  {:.0f} damage", "  ·  {:.0f} Schaden"},
    {"  ·  {:.0f}% crit", "  ·  {:.0f}% Crit"},
    {"  ·  {} hits", "  ·  {} Treffer"},
    {" blocks", " Blöcke"},
    {" for ", " für "},
    {"%.1f h", "%.1f Uhr"},
    {"%d game modules ready, %d waiting for signatures", "%d Spiel-Module bereit, %d warten auf Signaturen"},
    {"1% low and peak", "1% Low und Spitze"},
    {"1% low {:.0f} FPS  ·  peak {:.1f} ms", "1% Low {:.0f} FPS  ·  Spitze {:.1f} ms"},
    {"1% low: {:.0f} fps  ·  worst frame {:.1f} ms", "1% Low: {:.0f} fps  ·  schlechtester Frame {:.1f} ms"},
    {"1.8-style swing and block animations, smaller item, own swing speed.", "Schwung- und Block-Animationen im 1.8-Stil, kleineres Item, eigene Schwunggeschwindigkeit."},
    {"10 degrees", "10 Grad"},
    {"15 degrees", "15 Grad"},
    {"2.4 GHz", "2,4 GHz"},
    {"30 and 60 FPS lines", "Linien für 30 und 60 FPS"},
    {"3D box", "3D-Box"},
    {"5 degrees", "5 Grad"},
    {"<Max> who has the pearl?", "<Max> wer hat die Perle?"},
    {"A LAN cable is the surest fix for jitter", "LAN-Kabel ist die sicherste Lösung gegen Jitter"},
    {"A little Monchi pet in the HUD: bounces, cheers on hits, sleeps when idle.", "Kleines Monchi-Haustier im HUD: wippt, freut sich über Treffer, schläft bei Ruhe."},
    {"A rain of hearts and text on screen when you get a kill. Local only.", "Herzchen-Regen und Text auf dem Bildschirm, wenn du einen Kill machst. Nur lokal."},
    {"A red, pulsing screen edge when your health is low.", "Roter, pulsierender Rand am Bildschirm, wenn dein Leben niedrig ist."},
    {"A short look behind you on a key, without changing your aim.", "Kurzer Blick nach hinten per Taste, ohne die Blickrichtung zu ändern."},
    {"A short marker at the crosshair when you hit. Display only, changes nothing in the game.", "Kurzer Marker am Fadenkreuz, wenn du triffst. Nur eine Anzeige, ändert nichts am Spiel."},
    {"A small figure in the HUD that wears your armor, sneaks, sprints and flashes red when you are hit.", "Kleine Figur im HUD, die deine Rüstung trägt, schleicht, sprintet und bei Treffern rot aufblitzt."},
    {"A smooth selection frame that glides between hotbar slots, with a small pop when you switch.", "Ein weicher Auswahlrahmen, der zwischen den Hotbar-Plätzen gleitet und beim Wechseln kurz hüpft."},
    {"A warmer blue-light filter for relaxed eyes, optionally automatic in the evening.", "Wärmerer Blaufilter für entspanntere Augen, auf Wunsch automatisch am Abend."},
    {"About {:.0f} ms in total until the hit", "Gesamt ca. {:.0f} ms bis zum Treffer"},
    {"Accept duel requests", "Duell-Anfragen annehmen"},
    {"Accept friend requests", "Freundschaftsanfragen annehmen"},
    {"Accept party invites", "Party-Einladungen annehmen"},
    {"Accepting", "Wird angenommen"},
    {"Active limit: %.0f FPS  ·  Monitor: %d Hz", "Aktives Limit: %.0f FPS  ·  Monitor: %d Hz"},
    {"What Windows reports right now:", "Das meldet Windows gerade:"},
    {"Priority above normal", "Priorität über Normal"},
    {"Timer resolution", "Timer-Auflösung"},
    {"Power saving off", "Energiesparen aus"},
    {"Render thread scheduling", "Scheduling des Render-Threads"},
    {"Active: %s", "Aktiv: %s"},
    {"Adapter power saving is on", "Energiesparen des Adapters aktiv"},
    {"Add", "Addieren"},
    {"Add here", "Hier hinzufügen"},
    {"Adjust sensitivity while zooming", "Empfindlichkeit beim Zoomen anpassen"},
    {"Advanced settings", "Erweiterte Einstellungen"},
    {"Adventure", "Abenteuer"},
    {"After a kill", "Nach einem Kill"},
    {"Alignment to the crosshair", "Ausrichtung zum Fadenkreuz"},
    {"All axes", "Alle Achsen"},
    {"All items", "Alle Items"},
    {"All time", "Gesamt"},
    {"Allow {name} to use your player name", "{name} darf deinen Spielernamen nutzen"},
    {"Also armor, shield and totems", "Auch Rüstung, Schild und Totems"},
    {"Also in first person", "Auch in der Ich-Perspektive"},
    {"Also in third person", "Auch in der dritten Person"},
    {"Also preview the saturation", "Auch die Sättigung vorab zeigen"},
    {"Also report when they leave", "Auch beim Verlassen melden"},
    {"Also show a bar", "Zusätzlich Balken"},
    {"Also show players", "Spieler zusätzlich"},
    {"Also show when off", "Auch anzeigen, wenn aus"},
    {"Also when your team is eliminated", "Auch wenn dein Team ausgeschieden ist"},
    {"Also write a clean file (no colors, no time)", "Zusätzlich eine saubere Datei schreiben (ohne Farben, ohne Zeit)"},
    {"Always", "Immer"},
    {"Always animate (also when scrolling)", "Immer animieren (auch beim Scrollen)"},
    {"Always as stars", "Immer als Sterne"},
    {"Always protect these hotbar slots (1 to 9, comma)", "Diese Hotbar-Plätze immer schützen (1 bis 9, Komma)"},
    {"Amount", "Menge"},
    {"Anchor", "Anker"},
    {"Announce your vote in chat", "Deine Stimme im Chat ansagen"},
    {"Announcement ({map})", "Ansage ({map})"},
    {"Anvil", "Amboss"},
    {"Append jitter", "Jitter anhängen"},
    {"Append loss", "Verlust anhängen"},
    {"Applied settings for {} modules.", "Einstellungen für {} Module angewendet."},
    {"Apply recommendation", "Empfehlung anwenden"},
    {"Apply the code", "Code anwenden"},
    {"Aqua", "Aqua"},
    {"Arrow", "Pfeil"},
    {"Arrow at the screen edge", "Pfeil am Bildschirmrand"},
    {"Arrow color", "Pfeilfarbe"},
    {"Arrows", "Pfeile"},
    {"As listed", "Wie aufgelistet"},
    {"As percent", "Als Prozent"},
    {"As sent by the server", "Wie vom Server"},
    {"Assigns your own keys to the hotbar slots, for example mouse buttons or keys next to WASD.", "Belegt die Hotbar-Plätze mit eigenen Tasten, zum Beispiel Maustasten oder Tasten neben WASD."},
    {"At the end of a game", "Am Spielende"},
    {"Auto requeue after a game", "Nach dem Spiel automatisch neu einreihen"},
    {"Automatic", "Automatisch"},
    {"Automatic by server", "Automatisch nach Server"},
    {"Automatic while walking forward", "Automatisch beim Vorwärtsgehen"},
    {"Automatically switches your settings profile when you join a server and back afterwards.", "Wechselt beim Betreten eines Servers automatisch dein Einstellungs-Profil und danach wieder zurück."},
    {"Automatically writes gg at the end of a game. On a kill it is banned on some servers.", "Schreibt am Spielende automatisch gg. Beim Kill ist es auf manchen Servern verboten."},
    {"Available on this version:", "Auf dieser Version verfügbar:"},
    {"Available profiles: %s", "Vorhandene Profile: %s"},
    {"Average", "Durchschnitt"},
    {"Avoiding map {}", "Map {} wird gemieden"},
    {"Back to work", "Zurück an die Arbeit"},
    {"Background blur", "Hintergrund-Unschärfe"},
    {"Background limit", "Hintergrund-Limit"},
    {"Background {:.0f}%", "Hintergrund {:.0f}%"},
    {"Balanced", "Ausgewogen"},
    {"Bar", "Leiste"},
    {"Bar color", "Balkenfarbe"},
    {"Bar height", "Balkenhöhe"},
    {"Bar width", "Breite der Leiste"},
    {"Base field of view", "Basis-Sichtfeld"},
    {"Base value", "Grundwert"},
    {"Beam height", "Strahlhöhe"},
    {"Beds", "Betten"},
    {"Beep", "Signalton"},
    {"Behavior", "Verhalten"},
    {"Behind", "Hinten"},
    {"Bell", "Glocke"},
    {"Best first", "Beste zuerst"},
    {"Best value", "Bestwert"},
    {"Biggest share: {} ({:.0f} %)", "Größter Anteil: {} ({:.0f} %)"},
    {"Biome", "Biom"},
    {"Biome: {}", "Biom: {}"},
    {"Black", "Schwarz"},
    {"Black and white", "Schwarzweiß"},
    {"Black bars at the top and bottom of the screen for a film look. They slide in and out and can hide in menus.", "Schwarze Balken oben und unten für einen Film-Look. Sie fahren ein und aus und können sich in Menüs verstecken."},
    {"Blend mode", "Mischmodus"},
    {"Blindness", "Blindheit"},
    {"Block Drop", "Block Drop"},
    {"Block Game  ·  {}  ·  Level {}  ·  Lines {}  ·  Best {}", "Block Game  ·  {}  ·  Level {}  ·  Linien {}  ·  Rekord {}"},
    {"Block Party", "Block Party"},
    {"Block coordinates", "Blockkoordinaten"},
    {"Block coordinates only", "Nur Blockkoordinaten"},
    {"Block entities off (chests, signs)", "Block-Entities aus (Truhen, Schilder)"},
    {"Block pose while blocking", "Block-Pose beim Blocken"},
    {"Block shadow", "Schatten des Blocks"},
    {"Block size", "Blockgröße"},
    {"Block titles", "Block-Titel"},
    {"Blocks per second", "Blöcke pro Sekunde"},
    {"Blue", "Blau"},
    {"Blue weakness (tritanopia)", "Blauschwäche (Tritanopie)"},
    {"Blur strength", "Unschärfe-Stärke"},
    {"Bobbing strength", "Wackel-Stärke"},
    {"Bold", "Fett"},
    {"Border", "Rand"},
    {"Border color", "Randfarbe"},
    {"Border thickness", "Randdicke"},
    {"Boss bar position", "Bossbar-Position"},
    {"Both", "Beides"},
    {"Both cancel out", "Beide neutralisieren"},
    {"Bottom center", "Unten Mitte"},
    {"Bottom left", "Unten links"},
    {"Bottom right", "Unten rechts"},
    {"Bottom up", "Von unten nach oben"},
    {"Bow", "Bogen"},
    {"Bow only", "Nur Bogen"},
    {"Box shadow", "Kastenschatten"},
    {"Box shadow color", "Farbe des Kastenschattens"},
    {"Box shadow size", "Größe des Kastenschattens"},
    {"Box style", "Boxform"},
    {"Break", "Pause"},
    {"Break progress", "Abbaufortschritt"},
    {"Breaking: {:.0f}%", "Abbau: {:.0f}%"},
    {"Brightness", "Helligkeit"},
    {"Brightness, contrast, gamma and vignette for the game image.", "Helligkeit, Kontrast, Gamma und Vignette für das Spielbild."},
    {"Brown", "Braun"},
    {"Button", "Knopf"},
    {"By kind", "Nach Art"},
    {"By name", "Nach Name"},
    {"CPS text ({value})", "CPS-Text ({value})"},
    {"CPU: {:.0f}% of {} threads", "CPU: {:.0f}% von {} Threads"},
    {"Camera", "Kamera"},
    {"Camera bobbing", "Kamera-Wackeln"},
    {"Camera bobbing off", "Kamera-Wackeln aus"},
    {"Camera rotation", "Kamera-Rotation"},
    {"Cancel", "Abbrechen"},
    {"Capture", "Aufnahme"},
    {"Capture key", "Aufnahme-Taste"},
    {"Capture now", "Jetzt aufnehmen"},
    {"Cardinal text", "Text der Himmelsrichtungen"},
    {"Cardinal text size", "Textgröße der Himmelsrichtungen"},
    {"Center", "Mitte"},
    {"Center dot", "Mittelpunkt"},
    {"Change level with the mouse wheel", "Stufe per Mausrad ändern"},
    {"Change the item field of view", "Sichtfeld des Items ändern"},
    {"Change the weather only for you: turn rain and thunder off or force them.", "Wetter nur bei dir ändern: Regen und Gewitter abschalten oder erzwingen."},
    {"Changes saturation and hue of the game image, with presets and an optional rainbow cycle.", "Ändert Sättigung und Farbton des Spielbilds, mit Vorlagen und optionalem Regenbogen-Wechsel."},
    {"Changes the color of the enchantment glint on items and armor.", "Ändert die Farbe des Verzauberungs-Glanzes auf Items und Rüstung."},
    {"Changes the red tint when you or an opponent take damage.", "Ändert die rote Farbe, wenn du oder ein Gegner Schaden nehmen."},
    {"Changes the text and background color of the name tags above players.", "Ändert Text- und Hintergrundfarbe der Namensschilder über Spielern."},
    {"Chat key in game", "Chat-Taste im Spiel"},
    {"Check armor", "Rüstung prüfen"},
    {"Check cable and router, enable router QoS for games", "Kabel und Router prüfen, Router-QoS für Spiele aktivieren"},
    {"Check item in hand", "Item in der Hand prüfen"},
    {"Chest", "Truhe"},
    {"Cinematic bars", "Kino-Balken"},
    {"Clear", "Klar"},
    {"Click", "Klack"},
    {"Click color / second color", "Klickfarbe / Zweitfarbe"},
    {"Click once and I will measure", "Klick mal, dann messe ich"},
    {"Click to frame: %.1f ms on average (%d clicks)", "Klick bis Bild: %.1f ms im Schnitt (%d Klicks)"},
    {"Click to measure the latency.", "Klicke, um die Latenz zu messen."},
    {"Client logo with heart and version as text, pill or gradient.", "Client-Logo mit Herz und Version als Text, Pille oder Verlauf."},
    {"Clock", "Uhr"},
    {"Clouds", "Wolken"},
    {"Clouds off", "Wolken aus"},
    {"Code copied ({} characters)", "Code kopiert ({} Zeichen)"},
    {"Color X", "Farbe X"},
    {"Color Y", "Farbe Y"},
    {"Color Z", "Farbe Z"},
    {"Color almost broken", "Farbe fast kaputt"},
    {"Color at full draw", "Farbe bei voller Spannung"},
    {"Color bad", "Farbe schlecht"},
    {"Color by danger", "Nach Gefahr einfärben"},
    {"Color by effect", "Farbe nach Effekt"},
    {"Color by health", "Farbe nach Leben"},
    {"Color by time left", "Nach Restzeit einfärben"},
    {"Color by value", "Farbe nach Wert"},
    {"Color current chunk", "Farbe aktueller Chunk"},
    {"Color filter for color blindness: corrects or simulates red, green and blue weakness.", "Farbfilter für Farbsehschwäche: korrigiert oder simuliert Rot-, Grün- und Blauschwäche."},
    {"Color frame", "Farbe Bild"},
    {"Color full", "Farbe voll"},
    {"Color full health", "Farbe volles Leben"},
    {"Color good", "Farbe gut"},
    {"Color half", "Farbe halb"},
    {"Color half health", "Farbe halbes Leben"},
    {"Color high", "Farbe hoch"},
    {"Color input", "Farbe Eingabe"},
    {"Color levels", "Farbe Ebenen"},
    {"Color low", "Farbe niedrig"},
    {"Color low health", "Farbe wenig Leben"},
    {"Color medium", "Farbe mittel"},
    {"Color names by team", "Namen nach Team einfärben"},
    {"Color neighbor chunks", "Farbe Nachbarchunks"},
    {"Color network", "Farbe Netzwerk"},
    {"Color on crit", "Farbe bei Crit"},
    {"Color server", "Farbe Server"},
    {"Color swatch", "Farbfeld"},
    {"Color temperature (K)", "Farbtemperatur (K)"},
    {"Color values by size", "Werte nach Größe einfärben"},
    {"Color when aiming", "Farbe beim Anvisieren"},
    {"Color when aiming at an opponent", "Farbe beim Anvisieren eines Gegners"},
    {"Color when almost done", "Farbe kurz vor fertig"},
    {"Bar direction", "Richtung des Balkens"},
    {"Horizontal", "Waagerecht"},
    {"Border width", "Randbreite"},
    {"Blur behind", "Unschärfe dahinter"},
    {"Smooth fill", "Weich füllen"},
    {"Show while not breaking", "Auch ohne Abbauen zeigen"},
    {"Color when it hurts", "Farbe, wenn es wehtut"},
    {"Color when lethal", "Farbe, wenn tödlich"},
    {"Color when low", "Farbe bei wenig Zeit"},
    {"Color while clicking", "Farbe beim Klicken"},
    {"Colored badge", "Farbiges Abzeichen"},
    {"Colored name", "Farbiger Name"},
    {"Column titles", "Spaltentitel"},
    {"Columns (0 = by rows)", "Spalten (0 = nach Zeilen)"},
    {"Combat displays", "Kampf-Anzeigen"},
    {"Combo record", "Combo-Rekord"},
    {"Command ", "Befehl "},
    {"Command ({mode} or {id})", "Befehl ({mode} oder {id})"},
    {"Compass direction", "Himmelsrichtung"},
    {"Compass with direction, degrees and view angle, as text or as a bar with waypoints.", "Kompass mit Richtung, Grad und Blickwinkel, als Text oder als Leiste mit Waypoints."},
    {"Connected", "Verbunden"},
    {"Connected to The Hive", "Mit The Hive verbunden"},
    {"Connected to Zeqa", "Mit Zeqa verbunden"},
    {"Connecting ...", "Verbinde ..."},
    {"Connection (Wi-Fi / LAN)", "Verbindung (WLAN / LAN)"},
    {"Connection poor", "Verbindung schlecht"},
    {"Connection type unknown", "Verbindungsart unbekannt"},
    {"Connection: ", "Verbindung: "},
    {"Constant spin", "Dauerdrehung"},
    {"Content", "Inhalt"},
    {"Contrast", "Kontrast"},
    {"Coordinates of the other dimension", "Koordinaten der anderen Dimension"},
    {"Copied", "Kopiert"},
    {"Copy code", "Code kopieren"},
    {"Copy custom server codes", "Custom-Server-Codes kopieren"},
    {"Copy format", "Kopierformat"},
    {"Copy last point", "Letzten Punkt kopieren"},
    {"Copy my settings as a code", "Meine Einstellungen als Code kopieren"},
    {"Copy position to the clipboard", "Position in die Zwischenablage kopieren"},
    {"Copy the file path afterwards", "Dateipfad danach kopieren"},
    {"Copy the folder path", "Ordnerpfad kopieren"},
    {"Copy to the clipboard", "In die Zwischenablage kopieren"},
    {"Could not load", "Konnte nicht laden"},
    {"Could not load the list.", "Die Liste konnte nicht geladen werden."},
    {"Could not read the image", "Das Bild konnte nicht gelesen werden"},
    {"Could not save the file.", "Die Datei konnte nicht gespeichert werden."},
    {"Count", "Anzahl"},
    {"Count hotbar only", "Nur Hotbar zählen"},
    {"Count to negatives", "Ins Minus zählen"},
    {"Counts any items you choose. Several items at once, sorting, format, hide at 0 or 1 and colored icons.", "Zählt beliebige Items. Mehrere Items gleichzeitig, Sortierung, Format, Ausblenden bei 0 oder 1 und farbige Symbole."},
    {"Counts entities and players around you.", "Zählt Entities und Spieler in deiner Umgebung."},
    {"Counts the splash potions in your inventory.", "Zählt die Wurftränke in deinem Inventar."},
    {"Counts your arrows. Can show only while you hold a bow or crossbow.", "Zählt deine Pfeile. Kann nur zeigen, solange du Bogen oder Armbrust hältst."},
    {"Counts your clicks per second. Format placeholders: {lmb} {rmb} {value}.", "Zählt deine Klicks pro Sekunde. Platzhalter im Format: {lmb} {rmb} {value}."},
    {"Counts your hits in a row until the opponent hits you.", "Zählt deine Treffer in Folge, bis dich der Gegner trifft."},
    {"Counts your totems of undying. Can show only while you hold one.", "Zählt deine Totems der Unsterblichkeit. Kann nur zeigen, solange du eines hältst."},
    {"Create an example script", "Beispielskript anlegen"},
    {"Created combo_hud.lua.", "combo_hud.lua angelegt."},
    {"Creative", "Kreativ"},
    {"Creeper", "Creeper"},
    {"Crit rate", "Crit-Quote"},
    {"Critical hit particles", "Crit-Partikel"},
    {"Critical hit particles on every hit", "Crit-Partikel bei jedem Treffer"},
    {"Critical!", "Kritisch!"},
    {"Crosses", "Kreuze"},
    {"Crystal without base", "Crystal ohne Sockel"},
    {"Crystal without spin and bobbing", "Crystal ohne Drehen und Wippen"},
    {"Crystals hidden by you: {}  ·  hidden right now: {}", "Von dir ausgeblendete Crystals: {}  ·  gerade ausgeblendet: {}"},
    {"Current", "Aktuell"},
    {"Current chunk only", "Nur aktueller Chunk"},
    {"Custom", "Eigener"},
    {"Custom command", "Eigener Befehl"},
    {"Custom grid", "Eigenes Raster"},
    {"Disable Inventory Hotkeys", "Inventar-Hotkeys aus"},
    {"Game crosshair", "Fadenkreuz des Spiels"},
    {"Pixel size of the game crosshair", "Pixelgröße des Spiel-Fadenkreuzes"},
    {"The crosshair of your texture pack, or the game's own without one. Size and color are yours.", "Das Fadenkreuz deines Texture Packs, ohne Pack das des Spiels. Größe und Farbe bestimmst du."},
    {"From: the game's own textures", "Aus: Texturen des Spiels"},
    {"From: {}", "Aus: {}"},
    {"No crosshair image found", "Kein Fadenkreuz-Bild gefunden"},
    {"Read again", "Neu einlesen"},
    {"On screen: {} x {} pixels", "Auf dem Bildschirm: {} x {} Pixel"},
    {"Solid cross", "Gefülltes Kreuz"},
    {"Arm length (GUI pixels)", "Armlänge (GUI-Pixel)"},
    {"Thickness (GUI pixels)", "Dicke (GUI-Pixel)"},
    {"The original crosshair cannot be hidden on this version yet, so it shows through. Pick the shape \"Solid cross\" to cover it cleanly.", "Das Original-Fadenkreuz lässt sich in dieser Version noch nicht ausblenden und scheint deshalb durch. Wähle die Form \"Gefülltes Kreuz\", dann wird es sauber verdeckt."},
    {"Custom target (empty = server)", "Eigenes Ziel (leer = Server)"},
    {"Custom text", "Eigener Text"},
    {"Cyan", "Cyan"},
    {"Cycle the hue", "Farbton durchlaufen"},
    {"D {}  ", "T {}  "},
    {"DD.MM.YYYY", "TT.MM.JJJJ"},
    {"Damage", "Schaden"},
    {"Damage numbers rise from the crosshair when you hit.", "Schadenszahlen steigen vom Fadenkreuz auf, wenn du triffst."},
    {"Danger below (s)", "Gefahr unter (s)"},
    {"Danger color", "Gefahrfarbe"},
    {"Danger up to light level", "Gefahr bis Lichtlevel"},
    {"Dark blue", "Dunkelblau"},
    {"Dark edge while zooming", "Dunkler Rand beim Zoomen"},
    {"Dark green", "Dunkelgrün"},
    {"Dark red", "Dunkelrot"},
    {"Darkness", "Dunkelheit"},
    {"Data", "Daten"},
    {"Date format", "Datumsformat"},
    {"Day", "Tag"},
    {"Day or night", "Tag oder Nacht"},
    {"Day {}", "Tag {}"},
    {"Death", "Tod"},
    {"Death Run", "Death Run"},
    {"Death Run: requeue after too many deaths", "Death Run: nach zu vielen Toden neu einreihen"},
    {"Death Run: requeue as Death", "Death Run: als Death neu einreihen"},
    {"Death Run: requeue as Runner", "Death Run: als Runner neu einreihen"},
    {"Death point is on the clipboard.", "Todespunkt in der Zwischenablage."},
    {"Death words (comma)", "Wörter für Tod (Komma)"},
    {"Deaths", "Tode"},
    {"Deaths before requeue", "Tode bis zum Requeue"},
    {"Decimals", "Nachkommastellen"},
    {"Deep-fries the game image: oversaturated, grainy and harshly stepped. Pure fun.", "Frittiert das Spielbild: übersättigt, körnig und hart abgestuft. Reiner Spaß."},
    {"Default color", "Standardfarbe"},
    {"Degrees under the arrow", "Grad unter dem Pfeil"},
    {"Delay (s)", "Verzögerung (s)"},
    {"Delay after closing (ms)", "Verzögerung nach dem Schließen (ms)"},
    {"Delete my data from the service", "Meine Daten im Dienst löschen"},
    {"Demo data (simulated game values)", "Demo-Daten (simulierte Spielwerte)"},
    {"Demo data on", "Demo-Daten aktiv"},
    {"Brightness / Contrast", "Helligkeit / Kontrast"},
    {"Saturation / Hue", "Sättigung / Farbton"},
    {"Hits {}  Kills {}  Deaths {}", "Treffer {}  Kills {}  Tode {}"},
    {"LAN  ·  {} Mbit/s", "LAN  ·  {} MBit/s"},
    {"Yaw / Pitch", "Gierwinkel / Neigung"},
    {"Demo data on: all game modules show simulated values.", "Demo-Daten aktiv: alle Spiel-Module zeigen simulierte Werte."},
    {"Demo data: the numbers are made up, the Hive API is not called.", "Demo-Daten: Die Zahlen sind erfunden, die Hive-API wird nicht aufgerufen."},
    {"Depth", "Tiefe"},
    {"Detect game end", "Spielende erkennen"},
    {"Detects your hardware, recommends a performance profile and applies it.", "Erkennt deine Hardware, empfiehlt ein Performance-Profil und wendet es an."},
    {"Diagnostics", "Diagnose"},
    {"Diamond", "Raute"},
    {"Dimension name", "Dimensionsname"},
    {"Dimension: {}", "Dimension: {}"},
    {"Direction", "Richtung"},
    {"Direction (camera)", "Richtung (Kamera)"},
    {"Direction arrows", "Richtungspfeile"},
    {"Disabled scripts", "Ausgeschaltete Skripte"},
    {"Display style", "Darstellung"},
    {"Display time (s, 0 = permanent)", "Anzeigedauer (s, 0 = dauerhaft)"},
    {"Display time after looking away (s)", "Anzeigedauer nach Blickwechsel (s)"},
    {"Displays are back on.", "Anzeigen sind wieder an."},
    {"Distance", "Distanz"},
    {"Distance to the block", "Abstand zum Block"},
    {"Do not change", "Nichts ändern"},
    {"Door", "Tür"},
    {"Dots", "Punkte"},
    {"Down", "Runter"},
    {"Draw entities", "Entities zeichnen"},
    {"Draw it above the TNT", "Über dem TNT zeichnen"},
    {"Draw terrain", "Gelände zeichnen"},
    {"Draws a fading line behind arrows, ender pearls and tridents in flight, so you can read where they fly.", "Zeichnet eine verblassende Linie hinter Pfeilen, Enderperlen und Dreizacken im Flug, damit du ihre Flugbahn lesen kannst."},
    {"Drop key", "Wegwerf-Taste"},
    {"Dropped items lie flat on the ground and settle smoothly instead of spinning in the air.", "Fallengelassene Items liegen flach am Boden und setzen sich weich ab, statt sich in der Luft zu drehen."},
    {"Drops blocked so far: {}", "Bisher blockierte Würfe: {}"},
    {"Duel accept command", "Befehl zum Annehmen von Duellen"},
    {"Duel mode", "Duell-Modus"},
    {"Duel request words (comma)", "Wörter für Duell-Anfragen (Komma)"},
    {"Duos", "Duo"},
    {"Durability", "Haltbarkeit"},
    {"Durability bar", "Haltbarkeitsbalken"},
    {"Durability bars", "Haltbarkeitsbalken"},
    {"Duration (s)", "Dauer (s)"},
    {"Duration {}", "Dauer {}"},
    {"Dynamic (walking, jumping, sneaking)", "Dynamisch (Laufen, Springen, Schleichen)"},
    {"E", "O"},
    {"East", "Osten"},
    {"Edge width", "Breite des Rands"},
    {"Effect channels", "Effekt-Kanäle"},
    {"Effect channels:", "Effekt-Kanäle:"},
    {"Effect name", "Effektname"},
    {"Eliminated", "Ausgeschieden"},
    {"Elimination words (comma)", "Wörter fürs Ausscheiden (Komma)"},
    {"Empty hand", "Leere Hand"},
    {"Ender pearl", "Enderperle"},
    {"Ender pearls", "Enderperlen"},
    {"Entities off", "Entities aus"},
    {"Entities: {}  Players: {}", "Entities: {}  Spieler: {}"},
    {"Entity: {}  ·  {:.1f} m", "Entity: {}  ·  {:.1f} m"},
    {"Every click", "Jeder Klick"},
    {"Everyone together", "Alle zusammen"},
    {"Exclude team", "Team ausschließen"},
    {"Explosion", "Explosion"},
    {"Extra while flying", "Zusatz beim Fliegen"},
    {"Extra while sprinting", "Zusatz beim Sprinten"},
    {"Eye line", "Augenlinie"},
    {"Eye line color", "Farbe der Augenlinie"},
    {"FKDR", "FKDR"},
    {"FKDR green from", "FKDR grün ab"},
    {"FKDR yellow from", "FKDR gelb ab"},
    {"FOV effects", "Sichtfeld-Effekte"},
    {"FPS behind it", "FPS dahinter"},
    {"Facing", "Blick"},
    {"Facing: yaw {:.1f} pitch {:.1f}", "Blick: yaw {:.1f} pitch {:.1f}"},
    {"Factor while sprinting", "Faktor beim Sprinten"},
    {"Fade in (s)", "Einblenden (s)"},
    {"Fade in and out", "Ein- und ausblenden"},
    {"Fade out (s)", "Ausblenden (s)"},
    {"Fade out at the edges", "Zum Rand ausblenden"},
    {"Fade out when close", "In der Nähe ausblenden"},
    {"Fade out with distance", "Mit Entfernung ausblenden"},
    {"Fall", "Fall"},
    {"Fall speed", "Fallgeschwindigkeit"},
    {"Falling blocks while you queue. Space drops, ESC quits.", "Fallende Blöcke für die Warteschlange. Leertaste lässt fallen, ESC beendet."},
    {"Falls asleep after (s)", "Einschlafen nach (s)"},
    {"Faster moving of items in the inventory. Banned on many servers.", "Schnelleres Bewegen von Items im Inventar. Auf vielen Servern verboten."},
    {"Favorite maps (comma)", "Lieblings-Maps (Komma)"},
    {"Field of view", "Sichtfeld"},
    {"File name", "Dateiname"},
    {"Fill", "Füllung"},
    {"Fill color", "Füllfarbe"},
    {"Fill the faces", "Flächen füllen"},
    {"Filled tiles", "Gefüllte Felder"},
    {"Final kills", "Final Kills"},
    {"Fire", "Feuer"},
    {"Fire Resistance", "Feuerresistenz"},
    {"Fire overlay", "Feuer-Overlay"},
    {"First game", "Erstes Spiel"},
    {"First line ({server} {mode} {name} {version})", "Erste Zeile ({server} {mode} {name} {version})"},
    {"First person", "Erste Person"},
    {"Fixed time", "Feste Uhrzeit"},
    {"Fixed value", "Fester Wert"},
    {"Flash color", "Blinkfarbe"},
    {"Flash on a new hit", "Aufleuchten bei neuem Treffer"},
    {"Flash on warning", "Blinken bei Warnung"},
    {"Flash the screen", "Bildschirm aufblitzen"},
    {"Flash when low", "Blinken bei wenig Zeit"},
    {"Flat (2D)", "Flach (2D)"},
    {"Flat hitbox", "Flache Hitbox"},
    {"Fluid swing (smooths repeated swings)", "Fließender Schwung (glättet wiederholte Schwünge)"},
    {"Fog", "Nebel"},
    {"Fog color", "Nebelfarbe"},
    {"Fog off", "Nebel aus"},
    {"Folder (empty = Pictures\\Monchi)", "Ordner (leer = Bilder\\Monchi)"},
    {"Folder: %s", "Ordner: %s"},
    {"Folder: {}", "Ordner: {}"},
    {"Footsteps", "Schritte"},
    {"Format ({D} {X} {Y} {Z}, empty = layout)", "Format ({D} {X} {Y} {Z}, leer = Layout)"},
    {"Format ({name} {value} {id})", "Format ({name} {value} {id})"},
    {"Format ({value})", "Format ({value})"},
    {"Forward / Back", "Vor / Zurück"},
    {"Forward key", "Vorwärts-Taste"},
    {"Frame", "Bild"},
    {"Frame blending", "Bildmischung"},
    {"Frame thickness", "Rahmendicke"},
    {"Frame timing", "Frame-Timing"},
    {"Frames in the graph", "Frames im Graphen"},
    {"Frametime graph", "Frametime-Graph"},
    {"Freelook key", "Freelook-Taste"},
    {"Changes the field of view of hand and item in first person, and where the game version allows it their position, size and rotation.", "Ändert das Sichtfeld von Hand und Item in der Ego-Perspektive und, wo die Spielversion es erlaubt, ihre Position, Größe und Drehung."},
    {"Fri", "Fr"},
    {"Friend accept command", "Befehl zum Annehmen von Freunden"},
    {"Friend request words (comma)", "Wörter für Freundschaftsanfragen (Komma)"},
    {"From (hearts)", "Ab (Herzen)"},
    {"From (hour)", "Ab (Uhr)"},
    {"Full", "Voll"},
    {"Full name", "Voller Name"},
    {"Full round trip", "Volle Rundlaufzeit"},
    {"GUI scale", "GUI-Skalierung"},
    {"GUI scale (0 = automatic)", "GUI-Skalierung (0 = automatisch)"},
    {"GUI scale of the game (0 = automatic)", "GUI-Skalierung des Spiels (0 = automatisch)"},
    {"Game", "Spiel"},
    {"Game day", "Spieltag"},
    {"Game end words (comma)", "Wörter für Spielende (Komma)"},
    {"Game mode", "Spielmodus"},
    {"Game over", "Spielende"},
    {"Game running for {}", "Spiel läuft seit {}"},
    {"Game time", "Spielzeit"},
    {"Game: {}", "Spiel: {}"},
    {"Game: {}  ·  Mode: {}  ·  Map: {}", "Spiel: {}  ·  Modus: {}  ·  Map: {}"},
    {"Games", "Spiele"},
    {"Games played", "Gespielte Spiele"},
    {"Glass breaking", "Glasbruch"},
    {"Glide speed", "Gleittempo"},
    {"Glint color", "Glanzfarbe"},
    {"Glow", "Leuchten"},
    {"Glow color", "Leuchtfarbe"},
    {"Glow on idle keys", "Leuchten bei ruhenden Tasten"},
    {"Glow on pressed keys", "Leuchten bei gedrückten Tasten"},
    {"Glow size", "Leuchtgröße"},
    {"Glow when idle", "Leuchten im Ruhezustand"},
    {"Glow when pressed", "Leuchten beim Drücken"},
    {"Gold", "Gold"},
    {"Gradient", "Verlauf"},
    {"Graph height", "Höhe des Graphen"},
    {"Graph position", "Position des Graphen"},
    {"Graph width", "Breite des Graphen"},
    {"Graphics", "Grafik"},
    {"Graphics card: %s", "Grafikkarte: %s"},
    {"Gravity", "Schwerkraft"},
    {"Gray", "Grau"},
    {"Green", "Grün"},
    {"Green weakness (deuteranopia)", "Grünschwäche (Deuteranopie)"},
    {"Grid", "Raster"},
    {"Group", "Gruppe"},
    {"Grows while fading", "Wächst beim Ausblenden"},
    {"HUD parts", "HUD-Teile"},
    {"Hair color", "Haarfarbe"},
    {"Half", "Halb"},
    {"Half round trip (one way)", "Halbe Rundlaufzeit (nur Hinweg)"},
    {"Hand bobbing", "Hand-Wackeln"},
    {"Hand bobbing off", "Hand-Wackeln aus"},
    {"Hand transform", "Hand-Transformation"},
    {"Hand transform in third person", "Hand-Transformation in der dritten Person"},
    {"Haste", "Eile"},
    {"Header", "Kopfzeile"},
    {"Health", "Leben"},
    {"Health Boost", "Lebensschub"},
    {"Health bar", "Lebensbalken"},
    {"Health value", "Lebenswert"},
    {"Health {:.1f}  Hunger {:.0f}  Level {}", "Leben {:.1f}  Hunger {:.0f}  Level {}"},
    {"Health {:.1f} / {:.0f}", "Leben {:.1f} / {:.0f}"},
    {"Heart before my name", "Herz vor meinem Namen"},
    {"Heart behind my name", "Herz hinter meinem Namen"},
    {"Heart color", "Herzfarbe"},
    {"Heartbeat pulse", "Herzschlag-Puls"},
    {"Hearts", "Herzen"},
    {"Hearts on hits", "Herzchen bei Treffern"},
    {"Height", "Höhe"},
    {"Height (fraction)", "Höhe (Anteil)"},
    {"Height above and below you", "Höhe über und unter dir"},
    {"Height above the ground", "Höhe über dem Boden"},
    {"Hidden by you: {}  ·  hidden right now: {}", "Von dir ausgeblendet: {}  ·  gerade ausgeblendet: {}"},
    {"Hide (streamer)", "Verstecken (Streamer)"},
    {"Hide No Teaming messages", "No-Teaming-Meldungen ausblenden"},
    {"Hide a hit crystal at once", "Getroffenen Crystal sofort ausblenden"},
    {"Hide after (s, 0 = never)", "Ausblenden nach (s, 0 = nie)"},
    {"Hide and Seek", "Hide and Seek"},
    {"Hide and Seek: requeue as Hider", "Hide and Seek: als Hider neu einreihen"},
    {"Hide and Seek: requeue as Seeker", "Hide and Seek: als Seeker neu einreihen"},
    {"Hide chat from Hive+ players", "Chat von Hive+-Spielern ausblenden"},
    {"Hide chat from players without a rank", "Chat von Spielern ohne Rang ausblenden"},
    {"Hide crystal instantly", "Crystal sofort ausblenden"},
    {"Hide empty slots", "Leere Plätze ausblenden"},
    {"Hide hand", "Hand ausblenden"},
    {"Hide in inventory, chat and pause", "In Inventar, Chat und Pause ausblenden"},
    {"Hide in menus", "In Menüs ausblenden"},
    {"Hide in third person", "In dritter Person ausblenden"},
    {"Hide items you do not have", "Items ausblenden, die du nicht hast"},
    {"Hide join messages", "Beitritts-Meldungen ausblenden"},
    {"Hide kill streak messages", "Kill-Serien-Meldungen ausblenden"},
    {"Hide leave messages", "Verlassen-Meldungen ausblenden"},
    {"Hide locally removed entities", "Lokal entfernte Entities ausblenden"},
    {"Hide main hand", "Haupthand ausblenden"},
    {"Hide offhand", "Nebenhand ausblenden"},
    {"Hide players who die according to chat", "Spieler ausblenden, die laut Chat sterben"},
    {"Hide players you kill", "Spieler ausblenden, die du tötest"},
    {"Hide promo messages", "Werbenachrichten ausblenden"},
    {"Hide the HUD modules while zooming", "HUD-Module beim Zoomen ausblenden"},
    {"Hide the game's own coordinates", "Die Koordinaten des Spiels ausblenden"},
    {"Hide the game's own day counter", "Den Tageszähler des Spiels ausblenden"},
    {"Hide the hand while zooming", "Hand beim Zoomen ausblenden"},
    {"Hide the number when it is 1", "Zahl bei 1 ausblenden"},
    {"Hide the original HUD", "Original-HUD ausblenden"},
    {"Hide the original chat", "Original-Chat ausblenden "},
    {"Hide the original crosshair", "Original-Fadenkreuz ausblenden "},
    {"Hide the original outline", "Original-Umriss ausblenden"},
    {"Hide the original scoreboard", "Original-Scoreboard ausblenden"},
    {"Hide unlock hints", "Freischalt-Hinweise ausblenden"},
    {"Hide when hit (game setting)", "Beim Treffen ausblenden (Spiel-Einstellung)"},
    {"Hide with a key", "Verstecken per Taste"},
    {"Hides IP, coordinates, server and chat on a key. A second press brings everything back.", "Versteckt per Taste IP, Koordinaten, Server und Chat. Zweiter Druck bringt alles zurück."},
    {"Hides a player right after you kill them until the game catches up. Client side only.", "Blendet einen Spieler direkt nach deinem Kill aus, bis das Spiel nachkommt. Nur clientseitig."},
    {"A hit end crystal disappears at once instead of waiting for the server. Client side only, sends nothing extra.", "Ein getroffener Endkristall verschwindet sofort, statt auf den Server zu warten. Nur clientseitig, sendet nichts zusätzlich."},
    {"Hides hand and item in first person, for a clear view or screenshots.", "Blendet Hand und Item in der Ego-Perspektive aus, für freie Sicht oder Screenshots."},
    {"High", "Hoch"},
    {"High (nice graphics)", "Hoch (schöne Grafik)"},
    {"High background load", "Hintergrundlast hoch"},
    {"High jitter, probably radio interference", "Jitter hoch, vermutlich Funk-Störung"},
    {"High jitter, the line fluctuates", "Jitter hoch, die Leitung schwankt"},
    {"High ping ({:.0f} ms), server far away or poor route", "Ping hoch ({:.0f} ms), Server weit weg oder Route schlecht"},
    {"Highlight", "Hervorhebung"},
    {"Highlight enchanted", "Verzauberte hervorheben"},
    {"Highlight players", "Spieler hervorheben"},
    {"Highlight words", "Wörter hervorheben"},
    {"History height", "Verlauf-Höhe"},
    {"Hit", "Treffer"},
    {"Hit detection needs the AttackEntity signature. \"Every click\" always works.", "Treffer-Erkennung braucht die Signatur AttackEntity. Mit \"Klick\" geht es immer."},
    {"Hit feedback", "Treffer-Feedback"},
    {"Hit ping", "Hit-Ping"},
    {"Hit rate", "Trefferquote"},
    {"Hit visuals", "Treffer-Visuals"},
    {"Hitbox color", "Hitbox-Farbe"},
    {"Hitbox eye line", "Hitbox-Augenlinie"},
    {"Hitbox eye line color", "Farbe der Hitbox-Augenlinie"},
    {"Hitbox line width", "Linienbreite der Hitbox"},
    {"Hitbox look line", "Hitbox-Blicklinie"},
    {"Hitbox look line color", "Farbe der Hitbox-Blicklinie"},
    {"Hitbox look line length", "Länge der Hitbox-Blicklinie"},
    {"Hitbox range", "Hitbox-Reichweite"},
    {"Hitboxes", "Hitboxen"},
    {"Hits", "Treffer"},
    {"Hits in the average", "Treffer im Durchschnitt"},
    {"Hits, swings and hit rate of the current round.", "Treffer, Schwünge und Trefferquote der aktuellen Runde."},
    {"Hold", "Halten"},
    {"Hold key", "Halte-Taste"},
    {"Hold the hand lower", "Hand tiefer halten"},
    {"Hot pink", "Knallrosa"},
    {"Hotbar Animation", "Hotbar-Animation"},
    {"Hotbar position", "Hotbar-Position"},
    {"Hotbar row", "Hotbar-Reihe"},
    {"Hotkey", "Taste"},
    {"Hotkeys for chat commands like /hub. Opens the chat like a player and sends the command.", "Tastenkürzel für Chat-Befehle wie /hub. Öffnet den Chat wie ein Spieler und sendet den Befehl."},
    {"Hotkeys for ready-made chat messages.", "Tastenkürzel für fertige Chat-Nachrichten."},
    {"Hue", "Farbton"},
    {"Hunger color", "Hungerfarbe"},
    {"Hunger {:.0f}  ·  Saturation {:.1f}", "Hunger {:.0f}  ·  Sättigung {:.1f}"},
    {"Hurt animation", "Treffer-Animation"},
    {"Hurt camera shake", "Treffer-Wackeln"},
    {"Hurt color", "Trefferfarbe"},
    {"Icon", "Symbol"},
    {"Icon size", "Symbolgröße"},
    {"Icons", "Symbole"},
    {"Ignore it when aiming", "Beim Zielen ignorieren"},
    {"Ignore locally removed entities when aiming", "Lokal entfernte Entities beim Zielen ignorieren"},
    {"Ignore repeats within (ms)", "Wiederholungen ignorieren innerhalb (ms)"},
    {"Ignore sounds containing (comma)", "Sounds ignorieren, die enthalten (Komma)"},
    {"Ignore them when aiming", "Beim Zielen ignorieren"},
    {"Image pixel size", "Pixelgröße des Bildes"},
    {"Image tint", "Bildfarbe"},
    {"In a row", "In einer Reihe"},
    {"In chunk", "Im Chunk"},
    {"In hearts", "In Herzen"},
    {"Include key binds and texts in the code", "Tastenbelegungen und Texte im Code mitgeben"},
    {"Include the server tick", "Server-Tick einrechnen"},
    {"Input", "Eingabe"},
    {"Install", "Installieren"},
    {"Installing ...", "Installiere ..."},
    {"Instant Damage", "Sofortschaden"},
    {"Instant Health", "Sofortheilung"},
    {"Intercardinal directions", "Zwischen-Himmelsrichtungen"},
    {"Intercardinal text", "Text der Zwischenrichtungen"},
    {"Intercardinal text size", "Textgröße der Zwischenrichtungen"},
    {"Inventory", "Inventar"},
    {"Inventory Lock", "Inventory Lock"},
    {"Inventory delay", "Inventar-Verzögerung"},
    {"Inventory info", "Inventar-Info"},
    {"Inventory rows", "Inventar-Reihen"},
    {"Invert Y axis", "Y-Achse umkehren"},
    {"Invisibility", "Unsichtbarkeit"},
    {"Item counts", "Item-Mengen"},
    {"Item field of view", "Sichtfeld des Items"},
    {"Item in hand", "Item in der Hand"},
    {"Item in hand off", "Item in der Hand aus"},
    {"Item name", "Item-Name"},
    {"Item physics", "Item-Physik"},
    {"Item physics values", "Werte der Item-Physik"},
    {"Item size", "Item-Größe"},
    {"Item use delay", "Item-Nutzungs-Verzögerung"},
    {"Items (comma, name or name:variant)", "Items (Komma, Name oder Name:Variante)"},
    {"Items (name=seconds, comma separated)", "Items (name=Sekunden, mit Komma)"},
    {"JPEG quality", "JPEG-Qualität"},
    {"Java hitbox size", "Java-Hitbox-Größe"},
    {"Java size key", "Taste für Java-Größe"},
    {"Java-style FOV changes: sprinting, speed and drawing a bow change the view smoothly.", "Sichtfeld-Änderungen wie in Java: Sprinten, Schnelligkeit und Bogenspannen verändern das Bild sanft."},
    {"Java-style debug display (F3) with performance, position, world, target, system, server and time blocks and a frametime graph.", "Debug-Anzeige im Java-Stil (F3) mit Blöcken für Leistung, Position, Welt, Ziel, System, Server und Zeit sowie einem Frametime-Graphen."},
    {"Java-style player list with heads, platform icons, ping, world name, columns, sorting and highlights.", "Spielerliste im Java-Stil mit Köpfen, Plattform-Symbolen, Ping, Weltname, Spalten, Sortierung und Hervorhebungen."},
    {"Java-style size (+0.1)", "Java-Größe (+0,1)"},
    {"Jitter bad from (ms)", "Jitter schlecht ab (ms)"},
    {"Jitter medium from (ms)", "Jitter mittel ab (ms)"},
    {"Join words (comma)", "Beitritts-Wörter (Komma)"},
    {"Jump Boost", "Sprungkraft"},
    {"Just Build", "Just Build"},
    {"K/D", "K/D"},
    {"K/D green from", "K/D grün ab"},
    {"K/D yellow from", "K/D gelb ab"},
    {"Keep it hidden for at least (ms)", "Mindestens ausgeblendet lassen für (ms)"},
    {"Keep pitch", "Neigung beibehalten"},
    {"Keep the rotation when it lands", "Drehung beim Landen behalten"},
    {"Keep them hidden for (s)", "Ausgeblendet lassen für (s)"},
    {"Keeps tools and other valuables from being dropped by accident: dropping needs a quick double press of the drop key.", "Schützt Werkzeuge und andere Wertsachen vor versehentlichem Wegwerfen: Wegwerfen braucht einen schnellen Doppeldruck der Taste."},
    {"Keeps your movement keys going after you close the inventory, chat or a menu while still holding them.", "Hält deine Bewegungstasten aktiv, wenn du Inventar, Chat oder ein Menü schließt, während du sie noch hältst."},
    {"Key ", "Taste "},
    {"Key border", "Tastenrand"},
    {"Key border pressed", "Tastenrand gedrückt"},
    {"Key border thickness", "Tastenrand-Dicke"},
    {"Key in game", "Taste im Spiel"},
    {"Key shadow", "Tastenschatten"},
    {"Key shadow color", "Farbe des Tastenschattens"},
    {"Key spacing", "Tastenabstand"},
    {"Keys restored so far: {}", "Bisher wiederhergestellte Tasten: {}"},
    {"Kill streak words (comma)", "Kill-Serien-Wörter (Komma)"},
    {"Kill!", "Kill!"},
    {"Kill: ", "Kill: "},
    {"Kills and deaths", "Kills und Tode"},
    {"Kills, deaths, K/D and kill streak of this session.", "Kills, Tode, K/D und Kill-Serie dieser Sitzung."},
    {"Label", "Beschriftung"},
    {"Last commands", "Letzte Befehle"},
    {"Last file: {}", "Letzte Datei: {}"},
    {"Last frame: %.2f ms (%.0f FPS)", "Letzter Frame: %.2f ms (%.0f FPS)"},
    {"Last hit", "Letzter Treffer"},
    {"Last pressed key wins", "Zuletzt gedrückte Taste gewinnt"},
    {"Layout", "Anordnung"},
    {"Leave words (comma)", "Verlassen-Wörter (Komma)"},
    {"Left / Right", "Links / Rechts"},
    {"Left click paints, right click erases", "Linksklick malt, Rechtsklick löscht"},
    {"Left column", "Linke Spalte"},
    {"Length", "Länge"},
    {"Let scripts type in chat (monchi.say)", "Skripte dürfen im Chat schreiben (monchi.say)"},
    {"Level", "Level"},
    {"Level and bar", "Level und Balken"},
    {"Level up", "Level-Up"},
    {"Level {}  ·  {:.0f} points to the next level", "Level {}  ·  {:.0f} Punkte bis zum nächsten Level"},
    {"Level, bar and percent", "Level, Balken und Prozent"},
    {"Levitation", "Schwebekraft"},
    {"Lifetime (s)", "Lebensdauer (s)"},
    {"Light beam", "Lichtstrahl"},
    {"Light blue", "Hellblau"},
    {"Light numbers", "Lichtzahlen"},
    {"Lime", "Hellgrün"},
    {"Line background", "Zeilen-Hintergrund"},
    {"Line thickness", "Liniendicke"},
    {"Lines at most", "Höchstens Zeilen"},
    {"List", "Liste"},
    {"Lists your resource packs and writes the active list for the next game start, so you do not need the slow pack menu.", "Listet deine Ressourcenpakete und schreibt die aktive Liste für den nächsten Spielstart, damit du das langsame Paketmenü nicht brauchst."},
    {"Load a code from the clipboard", "Code aus der Zwischenablage laden"},
    {"Loading ...", "Lädt ..."},
    {"Loading …", "Lädt …"},
    {"Long break", "Lange Pause"},
    {"Long break (min)", "Lange Pause (min)"},
    {"Longest first", "Längste zuerst"},
    {"Look at a player first.", "Sieh zuerst einen Spieler an."},
    {"Look direction line", "Blickrichtungslinie"},
    {"Look key", "Blick-Taste"},
    {"Look line color", "Farbe der Blicklinie"},
    {"Look line length", "Länge der Blicklinie"},
    {"Look movement", "Blickbewegung"},
    {"Loss bad from (%)", "Verlust schlecht ab (%)"},
    {"Losses", "Niederlagen"},
    {"Low", "Niedrig"},
    {"Low (maximum FPS)", "Niedrig (maximale FPS)"},
    {"Low FPS", "Niedrige FPS"},
    {"Low below (FPS)", "Niedrig ab (FPS)"},
    {"Lower", "Absenken"},
    {"Lowers the fire overlay at the bottom of the screen or hides it completely.", "Senkt das Feuer-Overlay am unteren Bildrand oder blendet es ganz aus."},
    {"MM/DD/YYYY", "MM/TT/JJJJ"},
    {"Made-up users, no network", "Erfundene Nutzer, kein Netzwerk"},
    {"Magenta", "Magenta"},
    {"Main color", "Hauptfarbe"},
    {"Makes end crystals easier to see and hit: no spin and bobbing, no base, and a hit crystal disappears at once instead of waiting for the server. Client side only, sends nothing extra.", "Macht End-Crystals leichter sichtbar und treffbar: kein Drehen und Wippen, kein Sockel, und ein getroffener Crystal verschwindet sofort, statt auf den Server zu warten. Nur clientseitig, sendet nichts Zusätzliches."},
    {"Map avoider", "Map Avoider"},
    {"Map vote", "Map-Abstimmung"},
    {"Map vote helper", "Map-Vote-Hilfe"},
    {"Mark the selected slot", "Gewählten Slot markieren"},
    {"Marks the tiles around you where monsters can spawn, with colors or light numbers.", "Markiert die Felder um dich, auf denen Monster spawnen können, mit Farben oder Lichtzahlen."},
    {"Match end words (comma)", "Wörter für Match-Ende (Komma)"},
    {"Match over", "Match vorbei"},
    {"Maximum brightness everywhere, with a smooth fade and optionally only at night.", "Maximale Helligkeit überall, mit weichem Übergang und optional nur nachts oder in Höhlen."},
    {"Maximum distance (0 = unlimited)", "Maximale Entfernung (0 = unbegrenzt)"},
    {"Maximum lines", "Maximale Zeilen"},
    {"Measurement interval (ms)", "Messabstand (ms)"},
    {"Measurement interval (s)", "Messabstand (s)"},
    {"Measurement method", "Messverfahren"},
    {"Medium", "Mittel"},
    {"Mega", "Mega"},
    {"Mention sound", "Erwähnungs-Ton"},
    {"Menu limit", "Menü-Limit"},
    {"Merge identical lines", "Gleiche Zeilen zusammenfassen"},
    {"Message after kill", "Nachricht nach Kill"},
    {"Messages (random, separate with |)", "Nachrichten (zufällig, mit | trennen)"},
    {"Middle left", "Mitte links"},
    {"Middle right", "Mitte rechts"},
    {"Min / avg / max", "Min / Mittel / Max"},
    {"Min {:.0f}  ·  Avg {:.0f}  ·  Max {:.0f} ms", "Min {:.0f}  ·  Mittel {:.0f}  ·  Max {:.0f} ms"},
    {"Minimum gap (s)", "Mindestabstand (s)"},
    {"Minimum gap between requeues (s)", "Mindestabstand zwischen Requeues (s)"},
    {"Minimum time between hits (ms)", "Mindestabstand zwischen Treffern (ms)"},
    {"Minimum width", "Mindestbreite"},
    {"Mining Fatigue", "Abbaulähmung"},
    {"Mint", "Minze"},
    {"Minutes per day", "Minuten pro Tag"},
    {"Mirror", "Spiegeln"},
    {"Mirror the item", "Item spiegeln"},
    {"Mix", "Mischen"},
    {"Monchi", "Monchi"},
    {"Monchi Online", "Monchi Online"},
    {"Monchi block", "Monchi-Block"},
    {"MonchiPlayer", "MonchiSpieler"},
    {"Mode", "Modus"},
    {"Model", "Modell"},
    {"Modules and their signatures", "Module und ihre Signaturen"},
    {"Modules that get hidden (comma)", "Module, die versteckt werden (Komma)"},
    {"Mon", "Mo"},
    {"More or fewer particles, and critical hit particles on every hit. Fewer helps FPS, more looks nicer.", "Mehr oder weniger Partikel und Crit-Partikel bei jedem Treffer. Weniger hilft den FPS, mehr sieht schöner aus."},
    {"More words ( @here, comma)", "Weitere Wörter (@here, Komma)"},
    {"Most first", "Meiste zuerst"},
    {"Motion blur from camera movement and frame blending. Strength, quality and threshold adjustable.", "Bewegungsunschärfe aus Kamerabewegung und Bildmischung. Stärke, Qualität und Schwelle einstellbar."},
    {"Move closer to the router or use a LAN cable", "Näher an den Router oder LAN-Kabel nutzen"},
    {"Move forward and back", "Vor und zurück verschieben"},
    {"Move sideways", "Seitlich verschieben"},
    {"Move the big title text of the game, for example away from the middle of the screen.", "Verschiebe den großen Titeltext des Spiels, zum Beispiel weg aus der Bildschirmmitte."},
    {"Move the boss bar at the top of the screen. Drag the frame in the HUD editor.", "Verschiebe die Bossbar am oberen Rand. Ziehe den Rahmen im HUD-Editor."},
    {"Move the game's own hotbar anywhere on the screen. Drag the frame in the HUD editor.", "Verschiebe die Hotbar des Spiels an eine beliebige Stelle. Ziehe den Rahmen im HUD-Editor."},
    {"Move up and down", "Hoch und runter verschieben"},
    {"Movement", "Bewegung"},
    {"Moves the hand and the item in first person to the left side of the screen, mirrored.", "Setzt Hand und Item in der Ich-Perspektive spiegelverkehrt auf die linke Bildschirmseite."},
    {"Multiply", "Multiplizieren"},
    {"Murder Mystery", "Murder Mystery"},
    {"Murder Mystery: requeue as Innocent", "Murder Mystery: als Innocent neu einreihen"},
    {"Murder Mystery: requeue as Murderer", "Murder Mystery: als Murderer neu einreihen"},
    {"Murder Mystery: requeue as Sheriff", "Murder Mystery: als Sheriff neu einreihen"},
    {"Murderer", "Murderer"},
    {"NE", "NO"},
    {"Name and distance of the opponent you aim at, health only on request.", "Name und Distanz des anvisierten Gegners, Leben nur auf Wunsch."},
    {"Name color", "Namensfarbe"},
    {"Name style", "Namensstil"},
    {"Name the biggest share", "Größten Anteil nennen"},
    {"Names (comma)", "Namen (Komma)"},
    {"Nametag background color", "Hintergrundfarbe der Namensschilder"},
    {"Nametag text color", "Textfarbe der Namensschilder"},
    {"Nausea", "Übelkeit"},
    {"Negative effects", "Negative Effekte"},
    {"Network", "Netzwerk"},
    {"Network share", "Netzwerk-Anteil"},
    {"Never", "Nie"},
    {"Newest on top", "Neueste oben"},
    {"Next", "Weiter"},
    {"Nick", "Nick"},
    {"Night", "Nacht"},
    {"Night Vision", "Nachtsicht"},
    {"No death yet", "Noch kein Tod"},
    {"No effects", "Keine Effekte"},
    {"No items", "Keine Items"},
    {"No limit active  ·  Monitor: %d Hz", "Kein Limit aktiv  ·  Monitor: %d Hz"},
    {"No line selected", "Keine Zeile gewählt"},
    {"No measurement", "Keine Messung"},
    {"No pack", "Kein Pack"},
    {"No players", "Keine Spieler"},
    {"No reply", "Keine Antwort"},
    {"No reply from the server. Is the firewall blocking ICMP?", "Keine Antwort vom Server. Blockiert die Firewall ICMP?"},
    {"No resource packs found.", "Keine Ressourcenpakete gefunden."},
    {"No scripts yet. Put a .lua file in the folder.", "Noch keine Skripte. Lege eine .lua-Datei in den Ordner."},
    {"No service address set.", "Keine Dienstadresse eingestellt."},
    {"North", "Norden"},
    {"Northeast", "Nordosten"},
    {"Northwest", "Nordwesten"},
    {"Not allowed on many servers. Only turn it on where the server rules allow it.", "Auf vielen Servern nicht erlaubt. Nur einschalten, wenn die Server-Regeln es zulassen."},
    {"Not on The Hive. The overlay only shows there.", "Nicht auf The Hive. Die Anzeige erscheint nur dort."},
    {"Not on The Hive. This module only works there.", "Nicht auf The Hive. Dieses Modul funktioniert nur dort."},
    {"Not on Zeqa. This module only works there.", "Nicht auf Zeqa. Dieses Modul funktioniert nur dort."},
    {"Notice on a poor connection", "Hinweis bei schlechter Verbindung"},
    {"Notice on change", "Hinweis beim Wechsel"},
    {"Notice on death", "Hinweis beim Tod"},
    {"Notice on high load", "Hinweis bei hoher Last"},
    {"Notice on low FPS", "Hinweis bei niedrigen FPS"},
    {"Number", "Zahl"},
    {"Number and percent", "Zahl und Prozent"},
    {"Number color", "Zahlenfarbe"},
    {"Number of tips", "Anzahl Tipps"},
    {"Numbers", "Zahlen"},
    {"Numbers on safe tiles too", "Zahlen auch auf sicheren Feldern"},
    {"Numbers on the right", "Zahlen rechts"},
    {"Obfuscated (random letters)", "Verschleiert (zufällige Buchstaben)"},
    {"Offhand", "Nebenhand"},
    {"Offset (FPS)", "Abzug (FPS)"},
    {"Offset X", "Versatz X"},
    {"Offset Y", "Versatz Y"},
    {"On click", "Bei Klick"},
    {"On the clipboard.", "In der Zwischenablage."},
    {"On this server the message on a kill is banned and disabled.", "Auf diesem Server ist die Nachricht beim Kill verboten und deaktiviert."},
    {"On/off key", "Ein/Aus-Taste"},
    {"One block with selectable lines: FPS, CPS, Ping, position, health, clock, RAM.", "Ein Block mit wählbaren Zeilen: FPS, CPS, Ping, Position, Leben, Uhr, RAM."},
    {"One color", "Eine Farbe"},
    {"One line", "Eine Zeile"},
    {"Online", "Online"},
    {"Only against full armor", "Nur gegen volle Rüstung"},
    {"Only at certain hours", "Nur zu bestimmter Uhrzeit"},
    {"Only at night", "Nur nachts"},
    {"Only for mobs", "Nur bei Mobs"},
    {"Only for players", "Nur bei Spielern"},
    {"Only in solo modes", "Nur in Solo-Modi"},
    {"Only lines containing (empty = all)", "Nur Zeilen mit (leer = alle)"},
    {"Only load codes from people you trust.", "Lade nur Codes von Leuten, denen du vertraust."},
    {"Only my own", "Nur meine eigenen"},
    {"Only on crit", "Nur bei Crit"},
    {"Only say that you play Minecraft", "Nur zeigen, dass du Minecraft spielst"},
    {"Only simulate instead of correcting", "Nur simulieren statt korrigieren"},
    {"Only underwater", "Nur unter Wasser"},
    {"Only when in hand", "Nur wenn in der Hand"},
    {"Only where monsters can spawn", "Nur wo Monster spawnen können"},
    {"Only while Tab is held", "Nur solange Tab gehalten wird"},
    {"Only while a key is held", "Nur solange eine Taste gehalten wird"},
    {"Only while sprinting", "Nur beim Sprinten"},
    {"Only while the camera moves", "Nur bei Kamerabewegung"},
    {"Only while the menu is open", "Nur bei offenem Menü"},
    {"Only while walking", "Nur beim Gehen"},
    {"Only while zooming", "Nur beim Zoomen"},
    {"Only with a bow", "Nur mit Bogen"},
    {"Only with an empty hand", "Nur bei leerer Hand"},
    {"Open folder", "Ordner öffnen"},
    {"Opponent", "Gegner"},
    {"Opponent reach", "Gegner-Reach"},
    {"Opposite direction keys no longer cancel each other. Banned on many servers.", "Gegenläufige Richtungstasten heben sich nicht auf. Auf vielen Servern verboten."},
    {"Orange", "Orange"},
    {"Order", "Reihenfolge"},
    {"Original HUD off", "Original-HUD aus"},
    {"Original block outline", "Original-Blockumriss"},
    {"Original coordinates display", "Original-Koordinatenanzeige"},
    {"Original day counter", "Original-Tageszähler"},
    {"Other programs use {:.0f}% of the CPU.", "Andere Programme nutzen {:.0f}% der CPU."},
    {"Outline color", "Umriss-Farbe"},
    {"Outline enchanted", "Verzauberte umranden"},
    {"Outline enchanted items", "Verzauberte Items umranden"},
    {"Outline thickness", "Umriss-Dicke"},
    {"Overall size", "Größe gesamt"},
    {"Overlay", "Überlagern"},
    {"Overlay cost", "Overlay-Kosten"},
    {"Overlay {:.2f} ms per frame", "Overlay {:.2f} ms pro Frame"},
    {"Overworld", "Oberwelt"},
    {"Own WAV file", "Eigene WAV-Datei"},
    {"Own hitbox", "Eigene Hitbox"},
    {"Own nametag", "Eigener Nametag"},
    {"Own selection", "Eigene Auswahl"},
    {"Own sensitivity while you draw the bow, for more precise aiming.", "Eigene Empfindlichkeit, solange du den Bogen spannst, für präziseres Zielen."},
    {"Own sensitivity while zooming, drawing a bow, blocking, sneaking and sprinting.", "Eigene Empfindlichkeit beim Zoomen, Bogenspannen, Blocken, Schleichen und Sprinten."},
    {"Own values", "Eigene Werte"},
    {"Own words", "Eigene Wörter"},
    {"PNG file path", "PNG-Dateipfad"},
    {"PNG image", "PNG-Bild"},
    {"Packet loss", "Paketverlust"},
    {"Packs", "Pakete"},
    {"Padding X", "Innenabstand X"},
    {"Padding Y", "Innenabstand Y"},
    {"Pants", "Hose"},
    {"Particle amount", "Partikelmenge"},
    {"Particles", "Partikel"},
    {"Particles and sparks at the crosshair on hits. Local only, visible only to you.", "Partikel und Funken am Fadenkreuz bei Treffern. Nur lokal, nur für dich sichtbar."},
    {"Particles off", "Partikel aus"},
    {"Party accept command", "Befehl zum Annehmen von Partys"},
    {"Party invite words (comma)", "Wörter für Party-Einladungen (Komma)"},
    {"Paste code", "Code einfügen"},
    {"Paste path from clipboard", "Pfad aus der Zwischenablage einfügen"},
    {"Pastel", "Pastell"},
    {"Pause background downloads and cloud sync", "Hintergrund-Downloads und Cloud-Sync pausieren"},
    {"Per server", "Pro Server"},
    {"Percent", "Prozent"},
    {"Performance", "Leistung"},
    {"Performance block", "Leistungs-Block"},
    {"Permanent", "Dauerhaft"},
    {"Perspective", "Perspektive"},
    {"Pickup", "Aufsammeln"},
    {"Pill", "Pille"},
    {"Ping as bars", "Ping als Balken"},
    {"Ping bad", "Ping schlecht"},
    {"Ping bad from (ms)", "Ping schlecht ab (ms)"},
    {"Ping good", "Ping gut"},
    {"Ping history", "Ping-Verlauf"},
    {"Ping medium", "Ping mittel"},
    {"Ping medium from (ms)", "Ping mittel ab (ms)"},
    {"Ping spikes every {:.0f} s, probably a Wi-Fi scan in the background", "Ping-Spitzen alle {:.0f} s, vermutlich WLAN-Scan im Hintergrund"},
    {"Ping, jitter and packet loss to the server, plus Wi-Fi data and tips.", "Ping, Jitter und Paketverlust zum Server, plus WLAN-Daten und Tipps."},
    {"Pink", "Rosa"},
    {"Pitch", "Tonhöhe"},
    {"Pixel editor (used for the shape \"Custom grid\")", "Pixel-Editor (wird bei Form \"Eigenes Raster\" benutzt)"},
    {"Pixel size", "Pixelgröße"},
    {"Pixels per degree", "Pixel pro Grad"},
    {"Platform", "Plattform"},
    {"Platform icons", "Plattform-Symbole"},
    {"Play crit sound", "Crit-Ton anhören"},
    {"Play sound", "Ton anhören"},
    {"Player", "Spieler"},
    {"Player block", "Spieler-Block"},
    {"Player count", "Spielerzahl"},
    {"Player heads", "Spielerköpfe"},
    {"Player left", "Spieler weg"},
    {"Player look rotation", "Blickdrehung des Spielers"},
    {"Player online", "Spieler online"},
    {"Players", "Spieler"},
    {"Players (comma)", "Spieler (Komma)"},
    {"Players only", "Nur Spieler"},
    {"Players shown", "Angezeigte Spieler"},
    {"Plays the hurt animation of the player you hit right away instead of after the server reply. Banned on many servers.", "Spielt die Treffer-Animation des getroffenen Spielers sofort, statt erst nach der Server-Antwort. Auf vielen Servern verboten."},
    {"Plays your own sound on every hit. Local only, creates no network packet.", "Spielt bei jedem Treffer einen eigenen Ton ab. Nur lokal, erzeugt kein Netzwerkpaket."},
    {"Point {}", "Punkt {}"},
    {"Points to next level", "Punkte bis zum nächsten Level"},
    {"Poison", "Vergiftung"},
    {"Poor", "Schlecht"},
    {"Pop when switching", "Hüpfen beim Wechseln"},
    {"Portal", "Portal"},
    {"Position", "Position"},
    {"Position block", "Positions-Block"},
    {"Position in chunk", "Position im Chunk"},
    {"Positive effects", "Positive Effekte"},
    {"Post effects", "Post-Effekte"},
    {"Potion effect strength", "Stärke der Trank-Effekte"},
    {"Potion value (-1 = any)", "Trank-Wert (-1 = egal)"},
    {"Power saving notice", "Energiespar-Hinweis"},
    {"Precise FPS limiter, throttles in the background and in the menu.", "Präziser FPS-Limiter, drosselt im Hintergrund und im Menü."},
    {"Prefix the server name", "Servername davorsetzen"},
    {"Preset", "Vorlage"},
    {"Press a key while you look at a player to save their skin as a PNG file on your PC. Nothing is sent, your own skin stays as it is.", "Drücke eine Taste, während du einen Spieler ansiehst, um seinen Skin als PNG auf deinem PC zu speichern. Es wird nichts gesendet, dein eigener Skin bleibt unverändert."},
    {"Press animation speed", "Tempo beim Drücken"},
    {"Press {} again to drop it", "Drücke {} noch einmal zum Wegwerfen"},
    {"Preview for food in hand", "Vorschau für Essen in der Hand"},
    {"Primary and secondary value of the game", "Haupt- und Nebenwert des Spiels"},
    {"Processor: %d cores  ·  Memory: %.0f GB  ·  Video memory: %.0f GB", "Prozessor: %d Kerne  ·  Arbeitsspeicher: %.0f GB  ·  Grafikspeicher: %.0f GB"},
    {"Profile ", "Profil "},
    {"Profile applied", "Profil angewendet"},
    {"Profile not found", "Profil nicht gefunden"},
    {"Profile switched", "Profil gewechselt"},
    {"Promo words (comma)", "Werbe-Wörter (Komma)"},
    {"Protect", "Schützen"},
    {"Pulse", "Pulsieren"},
    {"Pulse depth", "Puls-Tiefe"},
    {"Pulse speed (Hz)", "Puls-Tempo (Hz)"},
    {"Pulse while clicking", "Pulsieren beim Klicken"},
    {"Pulsing", "Pulsierend"},
    {"Purple", "Lila"},
    {"Put /cs in front of the code", "/cs vor den Code setzen"},
    {"Puts a color filter over the game image, for example a soft pink.", "Legt einen Farbfilter über das Spielbild, zum Beispiel zartes Rosa."},
    {"Quality (samples)", "Qualität (Proben)"},
    {"Queue", "Warteschlange"},
    {"Queue command ({type} {mode})", "Queue-Befehl ({type} {mode})"},
    {"Rain", "Regen"},
    {"Rain strength", "Regenstärke"},
    {"Rainbow", "Regenbogen"},
    {"Rainbow speed", "Regenbogen-Tempo"},
    {"Rainbow text", "Regenbogen-Text"},
    {"Range (0 = unlimited)", "Reichweite (0 = unbegrenzt)"},
    {"Range (blocks)", "Reichweite (Blöcke)"},
    {"Range (chunks)", "Reichweite (Chunks)"},
    {"Ranked", "Ranked"},
    {"Raw sound names", "Rohe Sound-Namen"},
    {"Read the options file again", "Optionsdatei neu lesen"},
    {"Real time", "Echtzeit"},
    {"Recommendation: %s", "Empfehlung: %s"},
    {"Red", "Rot"},
    {"Red below (s, 0 = off)", "Rot unter (s, 0 = aus)"},
    {"Red from (blocks)", "Rot ab (Blöcke)"},
    {"Red on hits", "Rot bei Treffern"},
    {"Red weakness (protanopia)", "Rotschwäche (Protanopie)"},
    {"Refresh every (s)", "Aktualisieren alle (s)"},
    {"Refresh rate minus offset", "Bildwiederholrate minus Abzug"},
    {"Refresh stats after (min)", "Statistik aktualisieren nach (min)"},
    {"Refresh the list", "Liste aktualisieren"},
    {"Release animation speed", "Tempo beim Loslassen"},
    {"Reload", "Neu laden"},
    {"Reload scripts when the file changes", "Skripte neu laden, wenn sich die Datei ändert"},
    {"Remaining height change", "Restliche Höhenänderung"},
    {"Remaining strength", "Restliche Stärke"},
    {"Remaining totems", "Verbleibende Totems"},
    {"Remaining wait", "Restliche Wartezeit"},
    {"Remember level", "Stufe merken"},
    {"Remembered death points", "Gemerkte Todespunkte"},
    {"Remembers where you died and shows the last death points with coordinates.", "Merkt sich, wo du gestorben bist, und zeigt die letzten Todespunkte mit Koordinaten."},
    {"Remove color codes", "Farbcodes entfernen"},
    {"Render thread with higher priority", "Render-Thread mit höherer Priorität"},
    {"Requeue after a match", "Nach einem Match neu einreihen"},
    {"Requeue command", "Requeue-Befehl"},
    {"Requeue for duels after a match, chat cleanup and auto accept for Zeqa. Only runs on Zeqa.", "Requeue für Duelle nach dem Match, Chat aufräumen und Auto-Accept für Zeqa. Läuft nur auf Zeqa."},
    {"Requeue helper, map avoider, role requeue, chat cleanup and auto accept for The Hive. Only runs on The Hive.", "Requeue-Helfer, Map Avoider, Rollen-Requeue, Chat aufräumen und Auto-Accept für The Hive. Läuft nur auf The Hive."},
    {"Requeue key", "Requeue-Taste"},
    {"Requeue now", "Jetzt neu einreihen"},
    {"Reset after (s)", "Zurücksetzen nach (s)"},
    {"Reset after (s, 0 = never)", "Zurücksetzen nach (s, 0 = nie)"},
    {"Reset after a pause", "Nach einer Pause zurücksetzen"},
    {"Reset measurement", "Messung zurücksetzen"},
    {"Resistance", "Resistenz"},
    {"Right column", "Rechte Spalte"},
    {"Ring color by phase", "Ringfarbe nach Phase"},
    {"Rise", "Aufstieg"},
    {"Role {}", "Rolle {}"},
    {"Role: {}  ·  Deaths this game: {}", "Rolle: {}  ·  Tode in diesem Spiel: {}"},
    {"Roman numerals", "Römische Ziffern"},
    {"Rotation", "Drehung"},
    {"Rotation X", "Drehung X"},
    {"Rotation Y", "Drehung Y"},
    {"Rotation Z", "Drehung Z"},
    {"Rotation speed", "Drehtempo"},
    {"Round", "Runde"},
    {"Round counter", "Rundenzähler"},
    {"Round {}", "Runde {}"},
    {"Rounding", "Rundung"},
    {"Rounds until the long break", "Runden bis zur langen Pause"},
    {"Row spacing", "Zeilenabstand"},
    {"Rows", "Zeilen"},
    {"Rows per column", "Zeilen pro Spalte"},
    {"Running", "Laufend"},
    {"Runs your own Lua 5.4 scripts from the scripts folder: HUD elements, reactions to hits and chat, small helpers. Safe sandbox, reloads when you save.", "Führt eigene Lua-5.4-Skripte aus dem Skript-Ordner aus: HUD-Elemente, Reaktionen auf Treffer und Chat, kleine Helfer. Sichere Sandbox, lädt beim Speichern neu."},
    {"SE", "SO"},
    {"Safe color", "Farbe für sicher"},
    {"Sakura petals fall gently across the screen.", "Sakura-Blütenblätter fallen sanft über den Bildschirm."},
    {"Salmon", "Lachs"},
    {"Samples in the window", "Messwerte im Fenster"},
    {"Sat", "Sa"},
    {"Saturation", "Sättigung"},
    {"Saturation color", "Sättigungsfarbe"},
    {"Save as file", "Als Datei speichern"},
    {"Save key", "Speichertaste"},
    {"Save the active list", "Aktive Liste speichern"},
    {"Saved. Restart the game to apply.", "Gespeichert. Starte das Spiel neu, damit es wirkt."},
    {"Saves the chat to a text file per day, with timestamps and filter.", "Speichert den Chat in einer Textdatei pro Tag, mit Zeitstempel und Filter."},
    {"Say when it would be lethal", "Sagen, wenn es tödlich wäre"},
    {"Scale", "Skalierung"},
    {"Scales the game's interface in fine steps, beyond the normal levels.", "Skaliert die Oberfläche des Spiels in feinen Schritten, über die normalen Stufen hinaus."},
    {"Scan again", "Neu suchen"},
    {"Scan now", "Jetzt suchen"},
    {"Screenshot copied", "Screenshot kopiert"},
    {"Screenshot failed", "Screenshot fehlgeschlagen"},
    {"Screenshot on a key, with or without the Monchi HUD, as PNG or JPEG.", "Screenshot per Taste, mit oder ohne Monchi-HUD, als PNG oder JPEG."},
    {"Screenshot saved", "Screenshot gespeichert"},
    {"Script list from GitHub", "Skript-Liste von GitHub"},
    {"Script {} stopped", "Skript {} gestoppt"},
    {"Scripts run in a sandbox, but only install scripts you trust.", "Skripte laufen in einer Sandbox, installiere aber nur Skripte, denen du vertraust."},
    {"Second color", "Zweitfarbe"},
    {"Second line", "Zweite Zeile"},
    {"Sensitive displays are off.", "Sensible Anzeigen sind aus."},
    {"Server block", "Server-Block"},
    {"Server code copied", "Server-Code kopiert"},
    {"Server ping with color dot", "Server-Ping mit Farbpunkt"},
    {"Server=profile, separate with semicolons", "Server=Profil, mit Semikolon trennen"},
    {"Service address", "Adresse des Dienstes"},
    {"Service answered {}.", "Der Dienst antwortete mit {}."},
    {"Service not reachable.", "Dienst nicht erreichbar."},
    {"Set a point at my position", "Punkt an meiner Position setzen"},
    {"Set the death point automatically", "Todespunkt automatisch setzen"},
    {"Set your field of view freely. Sprint and potion effects can be turned off.", "Stellt dein Sichtfeld frei ein. Sprint- und Trank-Effekte lassen sich abschalten."},
    {"Sets the time of day only for you: fixed, running or sunset.", "Stellt die Tageszeit nur bei dir ein: fest, laufend oder Sonnenuntergang."},
    {"Several light levels", "Mehrere Lichtlevel"},
    {"Shadow", "Schatten"},
    {"Shadows off", "Schatten aus"},
    {"Shaky", "Wackelig"},
    {"Sharpens the game image, useful at low resolution or scaling.", "Schärft das Spielbild nach, nützlich bei niedriger Auflösung oder Skalierung."},
    {"Shift hue", "Farbton verschieben"},
    {"Shirt", "Oberteil"},
    {"Short", "Kurz"},
    {"Short break", "Kurze Pause"},
    {"Short break (min)", "Kurze Pause (min)"},
    {"Shortens the local chain from click to frame. Creates no clicks. Banned on some servers.", "Kürzt die lokale Kette Klick bis Bild. Erzeugt keine Klicks. Auf manchen Servern verboten."},
    {"Shortens the wait between item uses. Banned on many servers.", "Verkürzt die Wartezeit zwischen Item-Nutzungen. Auf vielen Servern verboten."},
    {"Shortest first", "Kürzeste zuerst"},
    {"Show", "Anzeigen"},
    {"Show a hint when a drop is blocked", "Hinweis zeigen, wenn ein Wegwerfen blockiert wird"},
    {"Show a notice for every action", "Bei jeder Aktion einen Hinweis zeigen"},
    {"Show a presence in the menus", "Auch in den Menüs etwas zeigen"},
    {"Show active effect channels", "Aktive Effekt-Kanäle zeigen"},
    {"Show armor", "Rüstung anzeigen"},
    {"Show at most", "Maximal anzeigen"},
    {"Show color codes", "Farbcodes darstellen"},
    {"Show distance", "Entfernung zeigen"},
    {"Show from (blocks)", "Anzeigen ab (Blöcke)"},
    {"Show grid", "Raster anzeigen"},
    {"Show health", "Leben anzeigen"},
    {"Show hearts of other users", "Herzen anderer Nutzer zeigen"},
    {"Show cosmetics on players in the world (experimental)", "Cosmetics an Spielern in der Welt zeigen (experimentell)"},
    {"Also on myself in third person", "Auch an mir in der Third-Person-Ansicht"},
    {"Cosmetics are drawn (test)", "Cosmetics werden gezeichnet (Test)"},
    {"Before the world", "Vor der Welt"},
    {"With the name tags", "Mit den Namensschildern"},
    {"After the world", "Nach der Welt"},
    {"Shoes swing the other way (test)", "Schuhe schwingen andersherum (Test)"},
    {"Name size", "Größe der Namen"},
    {"Hearts of Monchi users", "Herzen von Monchi-Nutzern"},
    {"Name colors of Monchi users", "Namensfarben von Monchi-Nutzern"},
    {"Line spacing", "Zeilenabstand"},
    {"Only limit in the background", "Nur im Hintergrund begrenzen"},
    {"Lowers the FPS while Minecraft is in the background. In the game and in its pause menu the game's own limit applies, unless you set one here.",
     "Senkt die FPS, solange Minecraft im Hintergrund ist. Im Spiel und im Pausenmenü gilt die Grenze des Spiels, außer du stellst hier eine ein."},
    {"Cosmetics in the world are not available on this game version.", "Cosmetics in der Welt sind auf dieser Spielversion nicht verfügbar."},
    {"Show in hearts", "In Herzen anzeigen"},
    {"Show name colors of other users", "Namensfarben anderer Nutzer zeigen"},
    {"Show notice", "Hinweis anzeigen"},
    {"Show peak value", "Höchstwert anzeigen"},
    {"Show percent", "Prozent anzeigen"},
    {"Show ping", "Ping anzeigen"},
    {"Show rank", "Rang zeigen"},
    {"Show reach", "Reichweite zeigen"},
    {"Show reason", "Grund anzeigen"},
    {"Show record", "Rekord anzeigen"},
    {"Show swings", "Schwünge anzeigen"},
    {"Show text", "Text anzeigen"},
    {"Show the command that is sent", "Den gesendeten Befehl anzeigen"},
    {"Show the play time", "Spielzeit zeigen"},
    {"Show the server", "Server zeigen"},
    {"Show the unit (s)", "Einheit (s) zeigen"},
    {"Show tips", "Tipps anzeigen"},
    {"Show unit", "Einheit anzeigen"},
    {"Show value", "Wert zeigen"},
    {"Show your own hitbox", "Eigene Hitbox zeigen"},
    {"Show yourself first", "Dich selbst zuerst zeigen"},
    {"Showing made-up Monchi users, nothing is sent.", "Zeigt erfundene Monchi-Nutzer, es wird nichts gesendet."},
    {"Shown death points", "Angezeigte Todespunkte"},
    {"Shown programs", "Angezeigte Programme"},
    {"Shows WASD, space and the mouse buttons live. Glow, borders, custom texts, spacing and animation speed.", "Zeigt WASD, Leertaste und Maustasten live. Leuchten, Ränder, eigene Texte, Abstand und Animationstempo."},
    {"Shows a message and plays a sound when one of your totems is used up.", "Zeigt eine Meldung und spielt einen Ton, wenn ein Totem bei dir verbraucht wird."},
    {"Shows cooldowns, for example for ender pearls. You choose which items count.", "Zeigt Abklingzeiten, zum Beispiel für Enderperlen. Welche Items zählen, legst du selbst fest."},
    {"Shows the hitbox of what you aim at, and your own in third person. Only what you can see, never through walls. Box or flat style, thickness, opacity, eye and look lines, Java size.", "Zeigt die Hitbox dessen, worauf du zielst, und deine eigene in der dritten Person. Nur was du siehst, nie durch Wände. Box oder flach, Linienstärke, Deckkraft, Augen- und Blicklinie, Java-Größe."},
    {"Shows how far you have fallen and how much damage you would take if you landed now.", "Zeigt, wie weit du gefallen bist und wie viel Schaden du bei einer Landung jetzt nehmen würdest."},
    {"Shows how far your bow is drawn, right at the crosshair.", "Zeigt, wie weit dein Bogen gespannt ist, direkt am Fadenkreuz."},
    {"Shows hunger and saturation as a bar and previews what the food in your hand gives.", "Zeigt Hunger und Sättigung als Balken und rechnet vor, was das Essen in deiner Hand bringt."},
    {"Shows other Monchi users with a heart and a colored name in the Tab List and chat, and lets them see yours. Sends only your gamertag, the server name, your style and your cosmetics to the Monchi service.", "Zeigt andere Monchi-Nutzer mit Herz und farbigem Namen in der Tab-Liste und im Chat und lässt sie deine sehen. Sendet nur deinen Gamertag, den Servernamen, deinen Stil und deine Cosmetics an den Monchi-Dienst."},
    {"Shows programs that use a lot of CPU and hurt FPS or ping.", "Zeigt Programme, die viel CPU ziehen und FPS oder Ping stören."},
    {"Shows the break progress of the block you are mining at the crosshair, as bar, ring or text (Block Break Indicator).", "Zeigt den Abbaufortschritt des Blocks am Fadenkreuz, als Balken, Ring oder Text (Block Break Indicator)."},
    {"Shows the chunk borders around you as lines, with sub-chunks, range and colors.", "Zeigt die Chunk-Grenzen um dich als Linien, mit Unterchunks, Reichweite und Farben."},
    {"Shows the contents of your inventory as a grid on the screen, with counts and durability.", "Zeigt den Inhalt deines Inventars als Raster auf dem Bildschirm, mit Mengen und Haltbarkeit."},
    {"Shows the distance from which the opponent last hit you.", "Zeigt die Distanz, aus der dich der Gegner zuletzt getroffen hat."},
    {"Shows the distance of your last hit, as average or best value.", "Zeigt die Distanz deines letzten Treffers, als Durchschnitt oder Bestwert."},
    {"Shows the game day and the world time.", "Zeigt den Spieltag und die Spielzeit der Welt."},
    {"Shows the item in your hand with count and durability.", "Zeigt das Item in deiner Hand mit Menge und Haltbarkeit."},
    {"Shows the real time, the game time or both, with date options.", "Zeigt die echte Uhrzeit, die Spielzeit oder beides, mit Datumsoptionen."},
    {"Shows the server address. Can be hidden for streamers.", "Zeigt die Server-Adresse. Für Streamer lässt sie sich verstecken."},
    {"Shows the stats of the players in your lobby from the public Hive API. Only on The Hive.", "Zeigt die Statistiken der Spieler in deiner Lobby aus der öffentlichen Hive-API. Nur auf The Hive."},
    {"Shows the time left on the primed TNT you are looking at, above the block and as a countdown.", "Zeigt die Restzeit des gezündeten TNT, das du ansiehst, über dem Block als Countdown."},
    {"Shows the top players of a Hive game, all time or this month. Only on The Hive.", "Zeigt die besten Spieler eines Hive-Spiels, gesamt oder in diesem Monat. Nur auf The Hive."},
    {"Shows what you are looking at: block or entity with name, distance and break progress.", "Zeigt, was du gerade anschaust: Block oder Entity mit Name, Distanz und Abbaufortschritt."},
    {"Shows what you hear as text with a direction arrow, for example footsteps behind you or an explosion to the left.", "Zeigt als Text mit Richtungspfeil, was du hörst, zum Beispiel Schritte hinter dir oder eine Explosion links."},
    {"Shows whether your last hit was a critical hit, and the crit rate.", "Zeigt, ob dein letzter Schlag ein kritischer Treffer war, und die Crit-Quote."},
    {"Shows which modules run on this version. Also home of the demo data switch.", "Zeigt, welche Module auf dieser Version laufen. Hier gibt es auch Demo-Daten."},
    {"Shows your active global resource packs. Packs a server forces on top are not listed.", "Zeigt deine aktiven globalen Resource Packs. Packs, die ein Server zusätzlich erzwingt, stehen nicht in der Liste."},
    {"Unknown pack ({})", "Unbekanntes Pack ({})"},
    {"Hits {}", "Treffer {}"},
    {"Fine tuning: shift X (GUI pixels)", "Feinkorrektur: Versatz X (GUI-Pixel)"},
    {"Fine tuning: shift Y (GUI pixels)", "Feinkorrektur: Versatz Y (GUI-Pixel)"},
    {"Fine tuning: size", "Feinkorrektur: Größe"},
    {"On the hunger bar", "Auf der Hunger-Anzeige"},
    {"Bar and text", "Balken und Text"},
    {"Menu: list {:.0f} us, details {:.0f} us, frame {:.0f} us", "Menü: Liste {:.0f} µs, Details {:.0f} µs, Frame {:.0f} µs"},
    {"Menu: {} rows, {} draw calls, {} vertices", "Menü: {} Zeilen, {} Draw-Calls, {} Vertices"},
    {"The dimension is not detected yet, so waypoints show in every dimension.", "Die Dimension wird noch nicht erkannt, deshalb erscheinen Wegpunkte in jeder Dimension."},
    {"Shows yaw and pitch of your view direction.", "Zeigt Yaw und Pitch deiner Blickrichtung."},
    {"Shows your active effects with time left, sorted and colored. Turns red when an effect is about to run out.", "Zeigt deine aktiven Effekte mit Restzeit, sortiert und farbig. Wird rot, wenn ein Effekt gleich ausläuft."},
    {"Shows your armor and the item in your hand with durability as a number, percent or bar.", "Zeigt deine Rüstung und das Item in der Hand mit Haltbarkeit als Zahl, Prozent oder Balken."},
    {"Shows your four armor pieces with durability right next to the hotbar.", "Zeigt deine vier Rüstungsteile mit Haltbarkeit direkt neben der Hotbar."},
    {"Shows your health as a number, hearts or bar, with absorption.", "Zeigt dein Leben als Zahl, Herzen oder Balken, mit Absorption."},
    {"Shows your level and the progress to the next level.", "Zeigt dein Level und den Fortschritt zum nächsten Level."},
    {"Shows your own name as a nick in Monchi's chat, tab list and stats. Only you see it, other players never do.", "Zeigt deinen Namen als Nick in Monchis Chat, Tab-Liste und Statistik. Nur du siehst ihn, andere Spieler nie."},
    {"Shows your own name tag above your head when you play in third person.", "Zeigt dein eigenes Namensschild über deinem Kopf, wenn du in der dritten Person spielst."},
    {"Shows your ping to the server.", "Zeigt deinen Ping zum Server."},
    {"Shows your position, optionally with chunk, biome, facing and Nether conversion.", "Zeigt deine Position, auf Wunsch mit Chunk, Biom, Himmelsrichtung und Nether-Umrechnung."},
    {"Shows your speed in blocks per second.", "Zeigt deine Geschwindigkeit in Blöcken pro Sekunde."},
    {"Shrink while sneaking", "Zusammenziehen beim Schleichen"},
    {"Side by side", "Nebeneinander"},
    {"Side of the hotbar", "Seite der Hotbar"},
    {"Signatures: {}/{} ({})", "Signaturen: {}/{} ({})"},
    {"Silver", "Silber"},
    {"Skeleton", "Skelett"},
    {"Skin color", "Hautfarbe"},
    {"Skin saved", "Skin gespeichert"},
    {"Skip phase", "Phase überspringen"},
    {"Sky", "Himmel"},
    {"Sky off", "Himmel aus"},
    {"Sleeps when idle", "Schläft bei Inaktivität"},
    {"Slide in and out", "Ein- und ausfahren"},
    {"Slide speed", "Fahr-Tempo"},
    {"Slight fluctuations", "Leichte Schwankungen"},
    {"Slot ", "Platz "},
    {"Slot size", "Slot-Größe"},
    {"Slow Falling", "Sanftes Fallen"},
    {"Slowness", "Langsamkeit"},
    {"Small heart icon", "Kleines Herz-Symbol"},
    {"Smooth fade", "Sanfter Übergang"},
    {"Smooth movement", "Weiche Bewegung"},
    {"Smoothing", "Glättung"},
    {"Smoothing (s)", "Glättung (s)"},
    {"Sneak", "Schleichen"},
    {"Sneak camera", "Schleich-Kamera"},
    {"Sneaking stays on until you press the sneak key again.", "Schleichen bleibt an, bis du die Schleich-Taste noch einmal drückst."},
    {"Soft focus: the image gets blurry towards the edges, like a camera with a tilt-shift effect.", "Weicher Fokus: das Bild wird zum Rand hin unscharf, wie bei einer Kamera mit Tilt-Shift-Effekt."},
    {"Soft, gliding camera movement like in film shots, with black bars. Optionally only while zooming.", "Weiche, gleitende Kamerabewegung wie im Film, mit schwarzen Balken. Auf Wunsch nur beim Zoomen."},
    {"Solid", "Einfarbig"},
    {"Solos", "Solo"},
    {"Some servers count this as an advantage. Only use it where the server rules allow it.", "Manche Server werten das als Vorteil. Nur nutzen, wo die Serverregeln es erlauben."},
    {"Sorting", "Sortierung"},
    {"Sound", "Ton"},
    {"Sound on crit", "Ton bei Crit"},
    {"Sound when someone mentions you", "Ton, wenn dich jemand erwähnt"},
    {"South", "Süden"},
    {"Southeast", "Südosten"},
    {"Southwest", "Südwesten"},
    {"Space bar height", "Höhe der Leertaste"},
    {"Space bar width", "Breite der Leertaste"},
    {"Spacing", "Abstand"},
    {"Sparks", "Funken"},
    {"Spawn and warning tiles", "Spawn- und Warnfelder"},
    {"Spectator", "Zuschauer"},
    {"Speed: {:.2f} b/s  ·  velocity {:.2f} {:.2f} {:.2f}", "Tempo: {:.2f} b/s  ·  Geschwindigkeit {:.2f} {:.2f} {:.2f}"},
    {"Spin speed (°/s)", "Dreh-Tempo (°/s)"},
    {"Splits the delay into input, frame, network and server tick.", "Teilt die Verzögerung in Eingabe, Bild, Netzwerk und Server-Tick auf."},
    {"Spread", "Streuung"},
    {"Spread while clicking", "Aufweiten beim Klicken"},
    {"Spread while jumping", "Aufweiten beim Springen"},
    {"Spread while walking", "Aufweiten beim Laufen"},
    {"Sprint", "Sprinten"},
    {"Sprint and potion effects off", "Sprint- und Trank-Effekte aus"},
    {"Sprinting stays on until you press the key again.", "Sprinten bleibt an, bis du die Taste noch einmal drückst."},
    {"Squads", "Squads"},
    {"Square", "Quadrat"},
    {"Stable", "Stabil"},
    {"Stacked", "Untereinander"},
    {"Stars", "Sterne"},
    {"Start / pause", "Start / Pause"},
    {"Start level", "Start-Level"},
    {"Start the next phase automatically", "Nächste Phase automatisch starten"},
    {"Statistics", "Statistik"},
    {"Step size", "Schrittweite"},
    {"Streak", "Serie"},
    {"Streak {} (best {})", "Serie {} (Rekord {})"},
    {"Strength", "Stärke"},
    {"Study and break timer: work phase, short and long break, with a notice on every change.", "Lern- und Pausen-Timer: Arbeitsphase, kurze und lange Pause, mit Hinweis beim Wechsel."},
    {"Sub-chunk levels", "Unterchunk-Ebenen"},
    {"Summary when you leave a server: duration, hits, combo, K/D.", "Zusammenfassung beim Verlassen eines Servers: Dauer, Treffer, Combo, K/D."},
    {"Summary: ", "Zusammenfassung: "},
    {"Sun", "So"},
    {"Sunset", "Sonnenuntergang"},
    {"Survival", "Überleben"},
    {"Survival Games", "Survival Games"},
    {"Swing angle", "Schwungwinkel"},
    {"Swing duration", "Schwung-Dauer"},
    {"Swing speed", "Schwunggeschwindigkeit"},
    {"Switch back afterwards", "Danach zurückwechseln"},
    {"Switch back when leaving", "Beim Verlassen zurückwechseln"},
    {"Switch the game mode with a key by typing the command for you. Works where you are allowed to use the command.", "Wechselt den Spielmodus per Taste, indem der Befehl für dich getippt wird. Funktioniert, wo du den Befehl nutzen darfst."},
    {"Switch to the 5 GHz band, 2.4 GHz is crowded", "Auf das 5-GHz-Band wechseln, 2,4 GHz ist überlaufen"},
    {"Switches between your saved settings profiles on a key.", "Wechselt per Taste zwischen deinen gespeicherten Einstellungs-Profilen."},
    {"Switches the perspective automatically, for example when gliding or drawing a bow.", "Wechselt die Perspektive automatisch, etwa beim Gleiten oder Bogenspannen."},
    {"System", "System"},
    {"System alert", "System-Warnton"},
    {"System block", "System-Block"},
    {"System ding", "System-Ton"},
    {"T shape", "T-Form"},
    {"Tab list", "Tab-Liste"},
    {"Tag color", "Tag-Farbe"},
    {"Target", "Ziel"},
    {"Target block", "Ziel-Block"},
    {"Teaming words (comma)", "Teaming-Wörter (Komma)"},
    {"Tells you when a player from your list joins the server, for example friends.", "Meldet, wenn ein Spieler aus deiner Liste auf den Server kommt, zum Beispiel Freunde."},
    {"Terrain off", "Gelände aus"},
    {"Text alignment", "Textausrichtung"},
    {"Text for back", "Text für Rückwärts"},
    {"Text for forward", "Text für Vorwärts"},
    {"Text for left", "Text für Links"},
    {"Text for left mouse button", "Text für linke Maustaste"},
    {"Text for right", "Text für Rechts"},
    {"Text for right mouse button", "Text für rechte Maustaste"},
    {"Text for space", "Text für Leertaste"},
    {"Text offset X", "Text-Versatz X"},
    {"Text offset Y", "Text-Versatz Y"},
    {"Text only", "Nur Text"},
    {"Text shadow offset", "Versatz des Textschattens"},
    {"Text size", "Textgröße"},
    {"Text when off", "Text wenn aus"},
    {"Text when on", "Text wenn aktiv"},
    {"The camera no longer drops when you sneak.", "Die Kamera springt beim Schleichen nicht mehr nach unten."},
    {"The camera no longer shakes when you get hit.", "Die Kamera wackelt nicht mehr, wenn du getroffen wirst."},
    {"The code has settings for {} modules. Apply it?", "Der Code hat Einstellungen für {} Module. Anwenden?"},
    {"The code is damaged.", "Der Code ist beschädigt."},
    {"The file could not be written.", "Die Datei konnte nicht geschrieben werden."},
    {"The game options file was not found.", "Die Optionsdatei des Spiels wurde nicht gefunden."},
    {"The game reads the list when it starts. Restart it to apply.", "Das Spiel liest die Liste beim Start. Starte es neu, damit sie wirkt."},
    {"The service stores your gamertag, style, cosmetics and the time you were last seen. Nothing from chat, no location, no worlds.", "Der Dienst speichert deinen Gamertag, Stil, Cosmetics und wann du zuletzt gesehen wurdest. Nichts aus dem Chat, kein Standort, keine Welten."},
    {"Third person back", "Dritte Person hinten"},
    {"Third person front", "Dritte Person vorne"},
    {"This gamertag is registered by another Monchi install.", "Dieser Gamertag ist von einer anderen Monchi-Installation registriert."},
    {"This is not a Monchi settings code.", "Das ist kein Monchi-Einstellungscode."},
    {"This month", "Dieser Monat"},
    {"Threshold (pixels per frame)", "Schwelle (Pixel pro Frame)"},
    {"Throttle in the background", "Im Hintergrund drosseln"},
    {"Throttle while the menu is open", "Bei offenem Menü drosseln"},
    {"Thu", "Do"},
    {"Thunder", "Gewitter"},
    {"Thunder off only", "Nur Gewitter aus"},
    {"Thunderstorm", "Gewitter"},
    {"Tick interval (ms)", "Tick-Raster (ms)"},
    {"Tick spacing", "Strichabstand"},
    {"Ticks", "Striche"},
    {"Time block", "Zeit-Block"},
    {"Time for the second press (ms)", "Zeit für den zweiten Druck (ms)"},
    {"Time from your attack until the server confirms the hit.", "Zeit von deinem Angriff, bis der Server den Treffer bestätigt."},
    {"Time left", "Restzeit"},
    {"Time of day", "Tageszeit"},
    {"Time since death", "Zeit seit dem Tod"},
    {"Time-left bar", "Restzeit-Balken"},
    {"Time: {} (day {})  {}", "Zeit: {} (Tag {})  {}"},
    {"Timestamp", "Zeitstempel"},
    {"Tint the image", "Bild einfärben"},
    {"Title", "Titel"},
    {"Title position", "Titel-Position"},
    {"Toggle", "Umschalten"},
    {"Toggle key", "Umschalttaste"},
    {"Toggle with the key", "Taste umschalten"},
    {"Tools only", "Nur Werkzeuge"},
    {"Top center", "Oben Mitte"},
    {"Top left", "Oben links"},
    {"Top right", "Oben rechts"},
    {"Total damage", "Gesamtschaden"},
    {"Total points", "Punkte insgesamt"},
    {"Totem used", "Totem verbraucht"},
    {"Totem used ({} left)", "Totem verbraucht ({} übrig)"},
    {"Traffic light", "Ampel"},
    {"Trail length (s)", "Länge der Spur (s)"},
    {"Transition speed", "Übergangstempo"},
    {"Triangle", "Dreieck"},
    {"Trident", "Dreizack"},
    {"Tridents", "Dreizacke"},
    {"Trigger", "Auslöser"},
    {"Try to exclude team", "Team ausschließen (Versuch)"},
    {"Tue", "Di"},
    {"Turn off power saving of the Wi-Fi adapter in the Device Manager", "Energiesparen des WLAN-Adapters im Geräte-Manager abschalten"},
    {"Turn off sky, fog and clouds one by one, only for you.", "Himmel, Nebel und Wolken einzeln abschalten, nur für dich."},
    {"Turn off the driver's automatic Wi-Fi scan", "Automatische WLAN-Suche des Treibers abschalten"},
    {"Turn the camera freely around you while your body and walking direction stay. Banned on some servers.", "Kamera frei um dich drehen, während Körper und Laufrichtung bleiben. Auf manchen Servern verboten."},
    {"Turns off the bobbing while walking, separately for camera and hand.", "Schaltet das Wackeln beim Laufen ab, für Kamera und Hand getrennt."},
    {"Turns the game image upside down. Controls stay normal, on purpose.", "Dreht das Spielbild auf den Kopf. Die Steuerung bleibt normal, das ist Absicht."},
    {"Turns your settings into a short code that you can send to friends, and loads codes from others.", "Macht aus deinen Einstellungen einen kurzen Code für Freunde und lädt Codes von anderen."},
    {"Type", "Art"},
    {"Unit", "Einheit"},
    {"Unlock words (comma)", "Freischalt-Wörter (Komma)"},
    {"Unranked", "Unranked"},
    {"Until (hour)", "Bis (Uhr)"},
    {"Up", "Hoch"},
    {"Use a PNG with a transparent background, up to 64 pixels.", "Nutze ein PNG mit transparentem Hintergrund, bis 64 Pixel."},
    {"Used so far: {}", "Bisher genutzt: {}"},
    {"Disables hotbar item-swapping shortcuts in the inventory without changing your Minecraft bindings.", "Schaltet Hotbar-Tausch-Tastenkürzel im Inventar aus, ohne deine Minecraft-Belegungen zu ändern."},
    {"Value", "Wert"},
    {"Version %s  ·  %d of %d signatures  ·  Source %s", "Version %s  ·  %d von %d Signaturen  ·  Quelle %s"},
    {"Vertical", "Vertikal"},
    {"Vertical correction", "Vertikale Korrektur"},
    {"Vertical speed (+/-)", "Vertikale Geschwindigkeit (+/-)"},
    {"Vignette off", "Vignette aus"},
    {"Violet", "Violett"},
    {"Visible for (s)", "Sichtbar für (s)"},
    {"Visible lines", "Sichtbare Zeilen"},
    {"Visible to other Monchi users", "Für andere Monchi-Nutzer sichtbar"},
    {"Vivid", "Lebendig"},
    {"Volume", "Lautstärke"},
    {"Vote for {}", "Stimme für {}"},
    {"WAV file path", "WAV-Dateipfad"},
    {"Waiting for the server", "Warte auf Server"},
    {"Warn below (%)", "Warnen unter (%)"},
    {"Warn from (% CPU)", "Warnen ab (% CPU)"},
    {"Warn when food would be wasted", "Warnen, wenn Essen verschwendet würde"},
    {"Warning below (%)", "Warnung unter (%)"},
    {"Warning below (s)", "Warnung unter (s)"},
    {"Warning color", "Warnfarbe"},
    {"Warning color at most (0 = off)", "Warnfarbe bei höchstens (0 = aus)"},
    {"Warning up to light level", "Warnung bis Lichtlevel"},
    {"Warns in the middle of the screen when armor or tools are almost broken, with an optional sound.", "Warnt in der Bildschirmmitte, wenn Rüstung oder Werkzeug fast kaputt sind, mit optionalem Ton."},
    {"Waste warning", "Warnung bei Verschwendung"},
    {"Water", "Wasser"},
    {"Water Breathing", "Wasseratmung"},
    {"Water color", "Wasserfarbe"},
    {"Waypoint distance", "Waypoint-Entfernung"},
    {"Waypoint names", "Waypoint-Namen"},
    {"Waypoint range (0 = unlimited)", "Waypoint-Reichweite (0 = unbegrenzt)"},
    {"Waypoints on the compass", "Waypoints im Kompass"},
    {"Weak Wi-Fi signal ({} %)", "WLAN-Signal schwach ({} %)"},
    {"Weakens the bobbing while walking. You set the strength yourself.", "Schwächt das Wackeln beim Laufen ab. Die Stärke stellst du selbst ein."},
    {"Weakness", "Schwäche"},
    {"Weather", "Wetter"},
    {"Weather effects off", "Wetter-Effekte aus"},
    {"Wed", "Mi"},
    {"Weekday", "Wochentag"},
    {"West", "Westen"},
    {"When", "Wann"},
    {"While blocking", "Beim Blocken"},
    {"While drawing a bow", "Beim Bogenspannen"},
    {"While emoting", "Bei einem Emote"},
    {"While gliding", "Beim Gleiten"},
    {"While sneaking", "Beim Schleichen"},
    {"While sprinting", "Beim Sprinten"},
    {"While swimming", "Beim Schwimmen"},
    {"While zooming", "Beim Zoomen"},
    {"White", "Weiß"},
    {"Wi-Fi", "WLAN"},
    {"Width", "Breite"},
    {"Win %", "Siege %"},
    {"Win rate", "Siegquote"},
    {"Win rate green from (%)", "Siegquote grün ab (%)"},
    {"Win rate yellow from (%)", "Siegquote gelb ab (%)"},
    {"Win streak", "Siegesserie"},
    {"Window: {:.0f}x{:.0f}", "Fenster: {:.0f}x{:.0f}"},
    {"Wins", "Siege"},
    {"With Monchi HUD", "Mit Monchi-HUD"},
    {"Without Monchi HUD", "Ohne Monchi-HUD"},
    {"Words (comma)", "Wörter (Komma)"},
    {"Words in chat (comma)", "Wörter im Chat (Komma)"},
    {"Work", "Arbeiten"},
    {"Work (min)", "Arbeit (min)"},
    {"World", "Welt"},
    {"World block", "Welt-Block"},
    {"World name", "Weltname"},
    {"World: {}", "Welt: {}"},
    {"X: x Y: y Z: z", "X: x Y: y Z: z"},
    {"YYYY-MM-DD", "JJJJ-MM-TT"},
    {"Yellow", "Gelb"},
    {"You died", "Du bist gestorben"},
    {"Your data will be deleted from the service.", "Deine Daten werden im Dienst gelöscht."},
    {"Your gamertag, the server name and your style are now sent to the Monchi service. Turn this module off to stop.", "Dein Gamertag, der Servername und dein Stil werden jetzt an den Monchi-Dienst gesendet. Schalte das Modul aus, um das zu beenden."},
    {"Your own crosshair with many shapes, a pixel editor and dynamics.", "Eigenes Fadenkreuz mit vielen Formen, Pixel-Editor und Dynamik."},
    {"Your own fog color, optionally as a rainbow.", "Eigene Nebelfarbe, auf Wunsch als Regenbogen."},
    {"Your own markers with beam, name and distance, also as an edge arrow.", "Eigene Markierungen mit Beam, Name und Entfernung, auch als Randpfeil."},
    {"Your own movable chat with timestamps, filter and highlighting.", "Eigener, verschiebbarer Chat mit Zeitstempeln, Filter und Hervorhebung."},
    {"Your own movable scoreboard without red numbers.", "Eigenes, verschiebbares Scoreboard ohne rote Zahlen."},
    {"Your own outline for the block you look at: color, thickness, fill, rainbow and pulsing.", "Eigener Umriss für den Block, den du anschaust: Farbe, Dicke, Füllung, Regenbogen und Pulsieren."},
    {"Your own water color, for example clear turquoise or pink.", "Eigene Wasserfarbe, zum Beispiel klares Türkis oder Rosa."},
    {"Zombie", "Zombie"},
    {"Zoom key", "Zoom-Taste"},
    {"Zoom level", "Zoomstufe"},
    {"Zoom on a key with smooth animation, scroll wheel steps and adjusted sensitivity.", "Zoom per Taste mit weicher Animation, Scrollrad-Stufen und angepasster Empfindlichkeit."},
    {"Zoom when drawing a bow", "Zoom beim Bogenspannen"},
    {"[Sneak: off]", "[Schleichen: aus]"},
    {"[Sneak: on]", "[Schleichen: an]"},
    {"[Sprint: off]", "[Sprint: aus]"},
    {"[Sprint: on]", "[Sprint: an]"},
    {"active", "aktiv"},
    {"clear", "klar"},
    {"combo_hud.lua already exists.", "combo_hud.lua gibt es schon."},
    {"hidden", "versteckt"},
    {"lethal", "tödlich"},
    {"missing: %s", "fehlt: %s"},
    {"requested", "angefordert"},
    {"the drop key", "die Wegwerf-Taste"},
    {"x y z", "x y z"},
    {"x, y, z", "x, y, z"},
    {"{:.0f} / {:.0f} health", "{:.0f} / {:.0f} Leben"},
    {"{:.0f} FPS on average. Turn on the performance profile in the \"Auto Profile\" module.", "Im Schnitt {:.0f} FPS. Aktiviere im Modul \"Auto Profile\" das Performance-Profil."},
    {"{:.0f} points wasted", "{:.0f} Punkte verschwendet"},
    {"{:.1f} % packet loss on the route", "{:.1f} % Paketverlust auf der Strecke"},
    {"{:.1f} % packet loss, probably radio interference", "{:.1f} % Paketverlust, vermutlich Funk-Störung"},
    {"{:.1f} blocks", "{:.1f} Blöcke"},
    {"{:.1f} blocks away", "{:.1f} Blöcke entfernt"},
    {"{}  ·  {} players", "{}  ·  {} Spieler"},
    {"{} (best {})", "{} (Rekord {})"},
    {"{} Monchi users in this list", "{} Monchi-Nutzer in dieser Liste"},
    {"{} almost broken ({:.0f}%)", "{} fast kaputt ({:.0f}%)"},
    {"{} deaths", "{} Tode"},
    {"{} events  ·  {} HUD  ·  {} KB", "{} Ereignisse  ·  {} HUD  ·  {} KB"},
    {"{} players", "{} Spieler"},
    {"{} points in total  ·  level {}", "{} Punkte insgesamt  ·  Level {}"},
    {"{}% system", "{}% System"},
    {"{}Loss {:.1f} %", "{}Verlust {:.1f} %"},
    {"§6Round 3 of 5 is starting", "§6Runde 3 von 5 startet"},
    {"§aMonchi Wars: You won!", "§aMonchi Wars: Du hast gewonnen!"},
    {"§eThe game starts in 5 seconds", "§eDas Spiel beginnt in 5 Sekunden"},
};

i18n::Table table(entries);

}
