#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Overworld name ({dim})", "Name der Oberwelt ({dim})"},
    {"Nether name ({dim})", "Name des Nethers ({dim})"},
    {"End name ({dim})", "Name des Endes ({dim})"},
    {"Movement direction (+/-) per axis", "Bewegungsrichtung (+/-) pro Achse"},
    {"Also for Y", "Auch für Y"},
    {"Fade starts at (% of the width)", "Ausblenden ab (% der Breite)"},
    {"Hide while the player list is open (Tab)", "Ausblenden, solange die Spielerliste offen ist (Tab)"},
    {"Tick thickness", "Strichstärke"},
    {"Cardinal tick thickness", "Strichstärke der Himmelsrichtungen"},
    {"Tick shadow", "Strichschatten"},
    {"Direction letters", "Richtungsbuchstaben"},
    {"Letter offset Y", "Buchstaben-Versatz Y"},
    {"Degree decimals", "Nachkommastellen der Grad"},
    {"Degree text size", "Textgröße der Grad"},
    {"Degree text offset", "Abstand der Gradanzeige"},
    {"Cardinal ticks", "Striche der Himmelsrichtungen"},
    {"Text shadow color", "Farbe des Textschattens"},
    {"Degree text", "Gradanzeige"},
    {"{}  ·  {} left", "{}  ·  noch {}"},
    {"Decimal level", "Dezimales Level"},
    {"Points in this level", "Punkte in diesem Level"},
    {"Everything", "Alles"},
    {"Points left to the next level", "Fehlende Punkte bis zum nächsten Level"},
    {"Level with decimals", "Level mit Nachkommastellen"},
    {"Roman numerals above V", "Römische Zahlen über V"},
    {"Time under the name", "Zeit unter dem Namen"},
    {"Time text size", "Textgröße der Zeit"},
    {"Text to the left (right-aligned)", "Text links (rechtsbündig)"},
    {"Hide when you have none", "Ausblenden, wenn du keine hast"},
    {"Items (comma, name or name:variant, =Label renames)", "Items (Komma, Name oder Name:Variante, =Bezeichnung benennt um)"},
    {"Count position", "Position der Anzahl"},
    {"In the text", "Im Text"},
    {"Left of the icon", "Links vom Symbol"},
    {"On the icon", "Auf dem Symbol"},
    {"Icon replaces the name", "Symbol ersetzt den Namen"},
    {"Dim items you do not have", "Items abdunkeln, die du nicht hast"},
    {"{} has {} durability left", "{} hat noch {} Haltbarkeit"},
    {"{} almost broken ({} left)", "{} fast kaputt (noch {})"},
    {"Warn by", "Warnen nach"},
    {"Durability points", "Haltbarkeitspunkten"},
    {"Warn at points left or less", "Warnen ab verbleibenden Punkten"},
    {"Check offhand", "Zweithand prüfen"},
    {"Text on screen", "Text auf dem Bildschirm"},
    {"Notification", "Benachrichtigung"},
    {"Edge grows with lost health", "Rand wächst mit verlorener Gesundheit"},
    {"Multiply the shown value (spoof)", "Angezeigten Wert vervielfachen (Spoof)"},
    {"System (used / total GB)", "System (belegt / gesamt GB)"},
    {"Minecraft and system", "Minecraft und System"},
    {"{:.0f} MB  ·  {}% system", "{:.0f} MB  ·  {}% System"},
    {"Stop it first, or allow resetting while it runs.", "Halte sie zuerst an oder erlaube das Zurücksetzen während sie läuft."},
    {"Allow resetting while it runs", "Zurücksetzen während sie läuft erlauben"},
    {"Precision", "Genauigkeit"},
    {"Tenths", "Zehntel"},
    {"Hundredths", "Hundertstel"},
    {"Milliseconds", "Millisekunden"},
    {"Color by state", "Farbe nach Zustand"},
    {"Paused", "Pausiert"},
    {"CPS text right button (empty = same)", "CPS-Text rechte Taste (leer = gleich)"},
    {"Button names in the mouse buttons", "Tastennamen in den Maustasten"},
    {"Key text size", "Textgröße der Tasten"},
    {"CPS text size", "Textgröße der CPS"},
    {"Blur behind each key", "Unschärfe hinter jeder Taste"},
    {"Glow size when pressed", "Leuchtgröße beim Drücken"},
    {"Glow size when idle", "Leuchtgröße im Ruhezustand"},
    {"Movement from", "Bewegung aus"},
    {"Mouse", "Maus"},
    {"View rotation", "Blickdrehung"},
    {"Return to the center", "Zurück zur Mitte"},
    {"Dot size", "Punktgröße"},
    {"Trail", "Spur"},
    {"Trail length", "Spurlänge"},
    {"Trail color", "Spurfarbe"},
    {"Center cross", "Kreuz in der Mitte"},
    {"Frame color", "Rahmenfarbe"},
    {"Always show", "Immer anzeigen"},
    {"Stays after moving (s)", "Bleibt nach der Bewegung (s)"},
    {"Time: {} ({:02}:{:02}, day {})  {}", "Zeit: {} ({:02}:{:02}, Tag {})  {}"},
    {"Yaw {:.1f}  Pitch {:.1f}  FOV {:.1f}  Aspect {:.2f}", "Yaw {:.1f}  Pitch {:.1f}  FOV {:.1f}  Seitenverhältnis {:.2f}"},
    {"View: {}", "Ansicht: {}"},
    {"System RAM: {:.1f} / {:.1f} GB", "System-RAM: {:.1f} / {:.1f} GB"},
    {"PC running for {}", "PC läuft seit {}"},
    {"{:.1f} ms min  ·  {:.1f} ms avg  ·  {:.1f} ms max", "{:.1f} ms min  ·  {:.1f} ms Schnitt  ·  {:.1f} ms max"},
    {"Camera block", "Kamera-Block"},
    {"Debug crosshair (XYZ axes)", "Debug-Fadenkreuz (XYZ-Achsen)"},
    {"Min, average and max frame time", "Minimale, mittlere und maximale Frametime"},
    {"Shows the time left on the primed TNT you are looking at, fixed on the screen or above the block.",
     "Zeigt die Restzeit des gezündeten TNT, das du ansiehst, fest auf dem Bildschirm oder über dem Block."},
    {"Fixed on the screen", "Fest auf dem Bildschirm"},
    {"Input {:.1f} ms old at the frame", "Eingabe beim Bild {:.1f} ms alt"},
    {"Limit waits {:.1f} ms in front of the input", "Limit wartet {:.1f} ms vor der Eingabe"},
    {"Wait in front of the input (lowest latency)", "Vor der Eingabe warten (geringste Latenz)"},
    {"Waiting in front of the input: the frame you see uses the newest input.", "Wartet vor der Eingabe: das Bild, das du siehst, nutzt die neueste Eingabe."},
    {"The game's input poll is not known yet, so the limit waits after Present.", "Die Eingabe-Abfrage des Spiels ist noch nicht bekannt, das Limit wartet deshalb nach dem Bild."},
    {"Frame start found: the limit and GPU pacing wait in front of the input.", "Frame-Anfang gefunden: Limit und GPU-Taktung warten vor der Eingabe."},
    {"Frame start not found yet: waiting for a steady input poll.", "Frame-Anfang noch nicht gefunden: warte auf eine gleichmäßige Eingabe-Abfrage."},
    {"Newest input at Present: %.1f ms old", "Neueste Eingabe beim Bild: %.1f ms alt"},
    {"Wait in front of the input: %.1f ms per frame", "Wartezeit vor der Eingabe: %.1f ms pro Bild"},
    {"Head follows the camera", "Kopf folgt der Kamera"},
    {"Off keeps your character's head still while you look around", "Aus: der Kopf deiner Figur bleibt still, während du dich umsiehst"},
    {"Changes rotation behavior of dropped items", "Ändert, wie sich gedroppte Items drehen: sie fallen und bleiben flach liegen"},
    {"Item Y Offset", "Höhen-Versatz der Items"},
    {"Vertical offset for non-block items", "Höhen-Versatz für Items, die keine Blöcke sind"},
    {"Preserve Rotations", "Drehung beibehalten"},
    {"Smooth Rotations", "Weiche Drehung"},
    {"Show the chat", "Chat anzeigen"},
    {"Clear chat key", "Taste zum Chat leeren"},
    {"Your own chat in place of the game's: move it, resize it, change colors and background, stack identical lines like Compact Chat, clear it with a key, hide it, timestamps, filter and highlighting.",
     "Dein eigener Chat statt dem des Spiels: verschieben, Größe ändern, Farben und Hintergrund anpassen, gleiche Zeilen stapeln wie bei Compact Chat, mit einer Taste leeren, ausblenden, Zeitstempel, Filter und Hervorhebung."},
    {"Pet, petals, DVD screen, deepfry, upside down and PatarHD", "Haustier, Blütenblätter, DVD-Bildschirm, Deepfry, Kopfüber und PatarHD"},
    {"0 = where the game puts it, 1 = far right", "0 = wo das Spiel es hinsetzt, 1 = ganz rechts"},
    {"0 = where the game puts it, 1 = bottom", "0 = wo das Spiel es hinsetzt, 1 = ganz unten"},
    {"Your own chat in place of the game's: move it, resize it, change colors and background, stack identical lines like Compact Chat, timestamps, filter and highlighting.",
     "Dein eigener Chat statt dem des Spiels: verschieben, Größe ändern, Farben und Hintergrund anpassen, gleiche Zeilen stapeln wie bei Compact Chat, Zeitstempel, Filter und Hervorhebung."},
    {"Moves the title and subtitle text that servers and commands show in the middle of the screen. Not the Minecraft logo in the menus. Works while you play, not in menus or the inventory.",
     "Verschiebt den Titel- und Untertiteltext, den Server und Befehle in der Bildschirmmitte zeigen. Nicht das Minecraft-Logo in den Menüs. Wirkt im Spiel, nicht in Menüs oder im Inventar."},
    {"Moves the game's hotbar. Works while you play, not in menus or the inventory.",
     "Verschiebt die Hotbar des Spiels. Wirkt im Spiel, nicht in Menüs oder im Inventar."},
    {"Moves the boss bar at the top of the screen. Works while you play.",
     "Verschiebt die Bossleiste oben am Bildschirm. Wirkt im Spiel."},
    {"Moves the game's own scoreboard on the side of the screen. Works while you play.",
     "Verschiebt die Anzeigetafel des Spiels am Bildschirmrand. Wirkt im Spiel."},
    {"Color, contrast, sharpen and blur", "Farbe, Kontrast, Schärfe und Unschärfe"},
    {"Brightness level", "Helligkeitsstufe"},
    {"Brightens the whole game, with a smooth fade and optionally only at night. The level sets how bright; the Brightness / Contrast filter adds to it.",
     "Hellt das ganze Spiel auf, mit sanftem Übergang und auf Wunsch nur nachts. Die Stufe bestimmt, wie hell; der Filter Helligkeit / Kontrast kommt obendrauf."},
    {"Brightness, contrast, gamma and vignette for the finished game image. Adds to Fullbright, which sets the brightness of the game itself.",
     "Helligkeit, Kontrast, Gamma und Vignette für das fertige Spielbild. Kommt zu Fullbright dazu, das die Helligkeit des Spiels selbst bestimmt."},
    {"Moves the game's own coordinates display (the world setting \"Show Coordinates\"). Monchi's Coordinates module is separate: drag it in the HUD editor.",
     "Verschiebt die Koordinatenanzeige des Spiels selbst (Welteinstellung \"Koordinaten anzeigen\"). Monchis Koordinaten-Modul ist getrennt: im HUD-Editor ziehen."},
    {"Moves the game's own day counter display (the world setting \"Show Days Played\"). Monchi's Day Counter module is separate: drag it in the HUD editor.",
     "Verschiebt die Tageszähler-Anzeige des Spiels selbst (Welteinstellung \"Gespielte Tage anzeigen\"). Monchis Tageszähler ist getrennt: im HUD-Editor ziehen."},
    {"Line spacing (blocks)", "Linienabstand (Blöcke)"},
    {"Horizontal position", "Horizontale Position"},
    {"Vertical position", "Vertikale Position"},
    {"Durability Warning", "Haltbarkeitswarnung"},
    {"Warns once when armor or a tool runs low and again when it is about to break: a card with the item, its bar and the percent, a short red flash at the screen edges and a sound that gets louder. Afterwards only a small indicator stays.",
     "Warnt einmal, wenn Rüstung oder ein Werkzeug knapp wird, und noch einmal kurz vor dem Bruch: eine Karte mit Gegenstand, Balken und Prozent, ein kurzer roter Blitz an den Bildrändern und ein Ton, der lauter wird. Danach bleibt nur ein kleiner Indikator."},
    {"Critical below (%)", "Kritisch unter (%)"},
    {"Critical at points left or less", "Kritisch bei Punkten übrig oder weniger"},
    {"Warning card", "Warnkarte"},
    {"Flash the screen edges when critical", "Bildränder bei Kritisch aufblitzen lassen"},
    {"Keep a small indicator while critical", "Kleinen Indikator bei Kritisch stehen lassen"},
    {"Critical only", "Nur bei Kritisch"},
    {"Color critical", "Farbe kritisch"},
    {"Critical", "Kritisch"},
    {"{} left", "{} übrig"},
    {"Display time (s)", "Anzeigedauer (s)"},
};

i18n::Table table(entries);

}
