#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Advanced mode (full ids like minecraft:stone)", "Erweiterter Modus (volle IDs wie minecraft:stone)"},
    {"Show air when you look at nothing", "Luft anzeigen, wenn du auf nichts schaust"},
    {"Air", "Luft"},
    {"Thinner lines with distance", "Dünnere Linien mit der Entfernung"},
    {"View while active", "Ansicht solange aktiv"},
    {"Players (comma, name=ff8800 for an own color)", "Spieler (Komma, name=ff8800 für eine eigene Farbe)"},
    {"Monchi players first", "Monchi-Spieler zuerst"},
    {"Match part of the name", "Auch Teile des Namens erkennen"},
    {"Remind who is online every (s, 0 = never)", "Erinnern, wer online ist, alle (s, 0 = nie)"},
    {"Check now", "Jetzt prüfen"},
    {"Players online", "Spieler online"},
    {"Nobody from your list is here.", "Niemand von deiner Liste ist hier."},
    {"Nether", "Nether"},
    {"The End", "Das Ende"},
    {"Show the dimension", "Dimension anzeigen"},
    {"Counter brackets", "Klammern um den Zähler"},
    {"Own counter color", "Eigene Zählerfarbe"},
    {"Counter color", "Zählerfarbe"},
    {"Bracket color", "Klammerfarbe"},
    {"Own room", "Eigener Raum"},
    {"Room name (same name, same voice room)", "Raumname (gleicher Name, gleicher Sprachraum)"},
    {"Everything with durability", "Alles mit Haltbarkeit"},
    {"Use the drop key from the game options", "Wegwerf-Taste aus den Spieloptionen nehmen"},
    {"After inventories and chests", "Nach Inventaren und Truhen"},
    {"After the pause menu", "Nach dem Pausenmenü"},
    {"After the chat", "Nach dem Chat"},
    {"After all other screens", "Nach allen anderen Bildschirmen"},
    {"Always sprint", "Immer sprinten"},
    {"Show what you are doing (walking, sprinting ...)", "Anzeigen, was du gerade tust (gehen, sprinten ...)"},
    {"Show whether sprint is toggled", "Anzeigen, ob Sprint umgeschaltet ist"},
    {"Standing", "Stehen"},
    {"Sneaking", "Schleichen"},
    {"Gliding", "Gleiten"},
    {"Swimming", "Schwimmen"},
    {"Sprinting", "Sprinten"},
    {"Walking", "Gehen"},
    {" (toggled)", " (umgeschaltet)"},
    {" (vanilla)", " (normal)"},
    {"Scrolling allowed", "Scrollen erlaubt"},
    {"Scrolling blocked", "Scrollen gesperrt"},
    {"Key that switches the block on and off", "Taste, die die Sperre ein- und ausschaltet"},
    {"Notice when a favorite map is up for vote", "Hinweis, wenn eine Lieblingskarte zur Wahl steht"},
    {"Overlay key (0 = always shown)", "Overlay-Taste (0 = immer sichtbar)"},
    {"Only while the key is held", "Nur solange die Taste gedrückt ist"},
    {"Also show in the hub", "Auch im Hub anzeigen"},
    {"Look into the distance for {:.0f} seconds.", "Schau {:.0f} Sekunden lang in die Ferne."},
    {"Look into the distance", "Schau in die Ferne"},
    {"Break length (s)", "Pausenlänge (s)"},
    {"Extreme mode: black screen during the break", "Extremmodus: schwarzer Bildschirm während der Pause"},
    {"Countdown on the black screen", "Countdown auf dem schwarzen Bildschirm"},
    {"Esc ends the break early", "Esc beendet die Pause früher"},
    {"Shows how far you look up or down, for example to hold the best elytra angle.", "Zeigt, wie weit du nach oben oder unten schaust, zum Beispiel um den besten Elytra-Winkel zu halten."},
    {"Degree sign", "Gradzeichen"},
    {"Up is positive", "Oben ist positiv"},
    {"Only with an elytra on", "Nur mit angelegten Elytren"},
    {"Only while gliding", "Nur beim Gleiten"},
    {"Color near a target angle", "Färben nahe einem Zielwinkel"},
    {"Target angle", "Zielwinkel"},
    {"Tolerance (°)", "Toleranz (°)"},
    {"Color at the target", "Farbe am Ziel"},
    {"Grid lines in the editor", "Rasterlinien im Editor"},
    {"Mark the middle in the editor", "Mitte im Editor markieren"},
    {"Saved crosshairs", "Gespeicherte Fadenkreuze"},
    {"Save", "Speichern"},
    {"Could not save the crosshair", "Das Fadenkreuz konnte nicht gespeichert werden"},
    {"Use", "Benutzen"},
    {"None yet. Save the grid above or put PNG files into the crosshairs folder.", "Noch keine. Speichere das Raster oben oder lege PNG-Dateien in den Ordner crosshairs."},
};

i18n::Table table(entries);

}
