#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Hand follows the field of view", "Hand folgt dem Sichtfeld"},
    {"Cinematic camera while zooming", "Kinokamera beim Zoomen"},
    {"View", "Ansicht"},
    {"Keep a view you pick yourself (F5)", "Selbst gewählte Ansicht behalten (F5)"},
    {"Toggle with a key", "Mit einer Taste umschalten"},
    {"While a key is held", "Solange eine Taste gedrückt ist"},
    {"Shape of the sharp area", "Form des scharfen Bereichs"},
    {"Horizontal band (tilt-shift)", "Waagrechtes Band (Tilt-Shift)"},
    {"Size of the sharp area", "Größe des scharfen Bereichs"},
    {"Transition width", "Breite des Übergangs"},
    {"Height of the sharp area", "Höhe des scharfen Bereichs"},
    {"Maximum blur", "Maximale Unschärfe"},
    {"Quality", "Qualität"},
    {"Off in menus", "In Menüs aus"},
    {"Same trail at every frame rate", "Gleiche Spur bei jeder Bildrate"},
    {"Trail length (ms)", "Spurlänge (ms)"},
    {"Deep-fried", "Frittiert"},
    {"Paint", "Gemalt"},
    {"Brush size", "Pinselgröße"},
    {"What turns", "Was sich dreht"},
    {"Whole picture", "Ganzes Bild"},
    {"Only the world", "Nur die Welt"},
    {"Upside down", "Kopfüber"},
    {"Mirrored", "Gespiegelt"},
    {"Only when the frame rate drops", "Nur wenn die Bildrate einbricht"},
    {"Below (FPS)", "Unter (FPS)"},
    {"Draw the outline", "Umriss zeichnen"},
    {"All visible faces", "Alle sichtbaren Seiten"},
    {"Only the face you look at", "Nur die Seite, auf die du schaust"},
    {"Glide to the next block", "Zum nächsten Block gleiten"},
    {"Grid on the walls of the current chunk", "Raster auf den Wänden des aktuellen Chunks"},
    {"Vertical line spacing (blocks)", "Abstand senkrechter Linien (Blöcke)"},
    {"Horizontal line spacing (blocks)", "Abstand waagrechter Linien (Blöcke)"},
    {"Grid color", "Rasterfarbe"},
    {"Corner color", "Eckenfarbe"},
    {"Progress bar", "Fortschrittsbalken"},
    {"Full fuse (s)", "Volle Zündzeit (s)"},
    {"Waypoint added", "Wegpunkt hinzugefügt"},
    {"Shown", "Angezeigt"},
    {"Click to rename", "Zum Umbenennen klicken"},
    {"Beam", "Strahl"},
    {"Random color for new points", "Zufällige Farbe für neue Punkte"},
    {"Smaller text far away", "Kleinere Schrift in der Ferne"},
    {"Text in the waypoint color", "Text in der Wegpunktfarbe"},
    {"Label background", "Hintergrund der Beschriftung"},
    {"Background in the waypoint color", "Hintergrund in der Wegpunktfarbe"},
    {"Background opacity", "Deckkraft des Hintergrunds"},
    {"Border in the waypoint color", "Rahmen in der Wegpunktfarbe"},
    {"Beam style", "Strahl-Stil"},
    {"Line", "Linie"},
    {"Column", "Säule"},
    {"Sides of the column", "Seiten der Säule"},
    {"Column radius", "Radius der Säule"},
    {"Outer glow", "Äußeres Leuchten"},
    {"Glow radius", "Leuchtradius"},
    {"Only on the server they were set on", "Nur auf dem Server, auf dem sie gesetzt wurden"},
    {"Horizontal speed", "Waagrechte Geschwindigkeit"},
    {"Vertical speed", "Senkrechte Geschwindigkeit"},
    {"Text (empty = Monchi)", "Text (leer = Monchi)"},
    {"New color on every bounce", "Neue Farbe bei jedem Abprall"},
};

i18n::Table table(entries);

}
