#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"PvP", "PvP"},
    {"HUD", "HUD"},
    {"Utility", "Nützliches"},
    {"Server", "Server"},
    {"Search modules", "Module suchen"},
    {"Live preview (click to hide)", "Live-Vorschau (klicken zum Ausblenden)"},
    {"Live preview (click to show)", "Live-Vorschau (klicken zum Einblenden)"},
    {"Turn the module on to see it here.", "Schalte das Modul ein, um es hier zu sehen."},
    {"Drag it in the picture to move it.", "Im Bild ziehen, um es zu verschieben."},
    {"No game data", "Keine Spieldaten"},
    {"no data", "keine Daten"},
    {"blocked", "gesperrt"},
    {"Search...", "Suchen..."},
    {"Favorite", "Favorit"},
    {"Global Settings", "Globale Einstellungen"},
    {"Change global settings for the client.", "Globale Einstellungen für den Client ändern."},
    {"Wings, capes and more. Only you and other Monchi players see them.", "Flügel, Umhänge und mehr. Nur du und andere Monchi-Spieler sehen sie."},
    {"Change Color", "Farbe ändern"},
    {"Unbind", "Entfernen"},
    {"none", "keine"},
    {"Accent color", "Akzentfarbe"},
    {"[Staff]", "[Team]"},
    {"The tag needs game data for chat and the Tab List. It shows up by itself once the data for your version is there.",
     "Das Tag braucht Spieldaten für Chat und Tab-Liste. Es erscheint von selbst, sobald die Daten für deine Version da sind."},
    {"Colors switches, sliders, buttons and modules that are on.", "Färbt Schalter, Slider, Buttons und eingeschaltete Module."},
    {"Change the panels and background. Your accent color stays.", "Ändern Panels und Hintergrund. Deine Akzentfarbe bleibt."},
    {"Right Shift to close", "Rechts-Shift schließt"},
    {"{} on", "{} an"},
    {"{}/{}", "{}/{}"},
    {"Keys, mouse buttons, CPS and mouse movement", "Tasten, Maustasten, CPS und Mausbewegung"},
    {"This one needs game data for your Minecraft version. It turns on by itself once the data is there.",
     "Dieses Modul braucht Spieldaten für deine Minecraft-Version. Es schaltet sich selbst frei, sobald die Daten da sind."},

    {"Sprint & Sneak", "Sprinten & Schleichen"},
    {"Toggle sprint and sneak, straight into the game's input", "Sprinten und Schleichen zum Umschalten, direkt in der Eingabe des Spiels"},
    {"Combat Info", "Kampf-Infos"},
    {"Reach, combo, hit ping, target and fight stats", "Reichweite, Combo, Hit Ping, Ziel und Kampfwerte"},
    {"Item Counters", "Item-Zähler"},
    {"Pots, totems, arrows and any item you pick", "Tränke, Totems, Pfeile und jedes Item deiner Wahl"},
    {"Hit Feedback", "Treffer-Feedback"},
    {"Markers, sounds, particles and effects when you hit", "Marker, Töne, Partikel und Effekte, wenn du triffst"},
    {"Aim & Input", "Zielen & Eingabe"},
    {"Movement keys, sensitivity, clicks and hotbar keys", "Bewegungstasten, Empfindlichkeit, Klicks und Hotbar-Tasten"},
    {"Player Info", "Spieler-Infos"},
    {"Coordinates, direction, speed, health and XP", "Koordinaten, Richtung, Tempo, Leben und XP"},
    {"Inventory HUD", "Inventar-HUD"},
    {"Inventory, armor bar, held item, item tracker, paperdoll and hunger", "Inventar, Rüstungsleiste, Item in der Hand, Item-Tracker, Paperdoll und Hunger"},
    {"Clock & Timers", "Uhr & Timer"},
    {"Clock, stopwatch, session time and pomodoro", "Uhr, Stoppuhr, Spielzeit und Pomodoro"},
    {"Game HUD", "Spiel-HUD"},
    {"Scoreboard, tab list and hotbar animation", "Scoreboard, Tab-Liste und Hotbar-Animation"},
    {"World Info", "Welt-Infos"},
    {"What you look at, break progress, TNT and entities", "Was du ansiehst, Abbaufortschritt, TNT und Entities"},
    {"Info Displays", "Info-Anzeigen"},
    {"Ping, server, packs, memory and watermark", "Ping, Server, Pakete, Speicher und Wasserzeichen"},
    {"Field of view, dynamic FOV, freelook and perspective", "Sichtfeld, dynamisches FOV, Freelook und Perspektive"},
    {"Clean View", "Klare Sicht"},
    {"No hurt cam, no bobbing and no hand", "Kein Hurt Cam, kein Wackeln und keine Hand"},
    {"Screen Filters", "Bildfilter"},
    {"Color, contrast, sharpen, blur and motion blur", "Farbe, Kontrast, Schärfe, Unschärfe und Bewegungsunschärfe"},
    {"Nametags", "Namensschilder"},
    {"Your own nametag and health above heads", "Dein eigenes Namensschild und Leben über Köpfen"},
    {"Waypoints & Trails", "Wegpunkte & Spuren"},
    {"Waypoints and arrow trails", "Wegpunkte und Pfeilspuren"},
    {"Chat", "Chat"},
    {"Better chat, hotkeys, logger, friend alerts and nick", "Besserer Chat, Hotkeys, Logger, Freundes-Hinweise und Nick"},
    {"Inventory lock and inventory hotkeys off", "Inventarsperre und Inventar-Hotkeys aus"},
    {"Tools", "Werkzeuge"},
    {"Pack changer, profile and gamemode hotkeys, config sharing, scripts", "Pakete wechseln, Profil- und Spielmodus-Hotkeys, Config teilen, Skripte"},
    {"Integrations", "Verbindungen"},
    {"Discord, music, Mumble and Monchi Online", "Discord, Musik, Mumble und Monchi Online"},
    {"Latency, lag analyzer, network monitor and debug menu", "Latenz, Lag-Analyse, Netzwerkmonitor und Debug-Menü"},
    {"Windows tweaks while you play and an automatic profile", "Windows-Tweaks beim Spielen und ein automatisches Profil"},
    {"The Hive", "The Hive"},
    {"Requeue, map avoider, stats and leaderboard", "Requeue, Map Avoider, Statistiken und Bestenliste"},
    {"Match Tools", "Match-Werkzeuge"},
    {"Server profiles and a match summary", "Server-Profile und eine Match-Zusammenfassung"},
    {"Mini Games", "Minispiele"},
    {"Snake, Flappy Heart and Block Game for the queue", "Snake, Flappy Heart und Block Game für die Warteschlange"},
    {"Pet, petals, DVD screen, deepfry and upside down", "Haustier, Blüten, DVD-Bildschirm, Deepfry und Kopfstand"},

    {"Shorter frame queue, optional tearing instead of VSync, a higher priority render thread and a precise FPS limiter. Shows the time from click to frame so you can compare.",
     "Kürzere Bild-Warteschlange, optional Tearing statt VSync, ein Render-Thread mit höherer Priorität und ein präziser FPS-Limiter. Zeigt die Zeit vom Klick bis zum Bild, damit du vergleichen kannst."},
    {"Zooms the picture for now. With game data for your version it changes the real field of view, which looks sharper.",
     "Vergrößert vorerst das Bild. Mit Spieldaten für deine Version ändert Zoom das echte Sichtfeld, das sieht schärfer aus."},
    {"Works on the mouse movement the game reads. Bow, block, sneak and sprint values need game data.",
     "Wirkt auf die Mausbewegung, die das Spiel liest. Die Werte für Bogen, Blocken, Schleichen und Sprinten brauchen Spieldaten."},
    {"Needs game data or the game's own input on this version.", "Braucht auf dieser Version Spieldaten oder die Eingabe des Spiels."},
};

i18n::Table table(entries);

}
