#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Auto GG (Beta)", "Auto GG (Beta)"},
    {"Cosmetics (Beta)", "Cosmetics (Beta)"},
    {"Cosmetics are still in beta and may have bugs.", "Cosmetics sind noch in der Beta und können Bugs haben."},
    {"Never tear (every frame waits for the display)", "Nie zerreißen (jedes Bild wartet auf den Bildschirm)"},
    {"FPS Boost", "FPS-Boost"},
    {"Ultra Low Input Delay", "Sehr geringe Eingabeverzoegerung"},
    {"Reduces redundant DirectX bridge submissions. Compare overlay time and frame lows in the same world.", "Reduziert redundante DirectX-Brueckenaufrufe. Vergleiche Overlay-Zeit und Frame-Ausreisser in derselben Welt."},
    {"Requests a one-frame queue and GPU pacing before verified game input. Prevents tearing by default with display sync.", "Fordert eine Ein-Frame-Warteschlange und GPU-Taktung vor bestaetigter Spieleingabe an. Verhindert standardmaessig Tearing durch Bildschirmsynchronisierung."},
    {"Overlay CPU time: %.3f ms", "Overlay-CPU-Zeit: %.3f ms"},
    {"DirectX bridge flushes: %u", "DirectX-Bruecken-Flushes: %u"},
    {"Frame time p99: %.2f ms", "Frame-Zeit p99: %.2f ms"},
    {"Short frame queue active", "Kurze Frame-Warteschlange aktiv"},
    {"Short frame queue unavailable", "Kurze Frame-Warteschlange nicht verfuegbar"},
    {"Game input pacing verified", "Taktung vor Spieleingabe bestaetigt"},
    {"Waiting for verified game input pacing", "Warte auf bestaetigte Taktung vor Spieleingabe"},
    {"Compare click timing in Latency Meter at the same FPS limit.", "Vergleiche Klickzeiten im Latency Meter mit demselben FPS-Limit."},
    {"NVIDIA GPU Boost", "NVIDIA-GPU-Boost"},

    {"Local sneak input", "Lokale Sneak-Eingabe"},
    {"Waiting for the local game tick.", "Warte auf den lokalen Spiel-Tick."},
    {"Show your hurt tint. Turning this off hides it.", "Zeigt deine Schadensfärbung. Aus blendet sie aus."},
    {"Show opponent hurt tint. Turning this off hides it.", "Zeigt die Schadensfärbung anderer Spieler und Mobs. Aus blendet sie aus."},
    {"Apply the custom hurt color to your own player.", "Wendet die eigene Schadensfarbe auf deinen Spieler an."},
    {"Apply the custom hurt color to other players and mobs.", "Wendet die eigene Schadensfarbe auf andere Spieler und Mobs an."},
    {"Minecraft screen animations are already off. This module cannot make menus faster by disabling them again.", "Minecraft-Menüanimationen sind bereits aus. Erneutes Ausschalten macht die Menüs nicht schneller."},
    {"Container loading and server response times are controlled by Minecraft and the server.", "Inventar-Ladezeiten und Server-Antwortzeiten werden von Minecraft und dem Server bestimmt."},
    {"Follow selected item", "Ausgewähltem Item folgen"},
    {"Adjust the Minecraft interface scale.", "Passt die Größe der Minecraft-Oberfläche an."},
    {"Adds smooth hand movement when walking, looking and jumping.", "Fügt sanfte Handbewegungen beim Gehen, Umsehen und Springen hinzu."},
    {"Turns off camera and hand bobbing while walking.", "Schaltet Kamera- und Handbewegungen beim Gehen aus."},
    {"Estimated time from your click until the target loses health. Other damage can affect this measurement.", "Geschätzte Zeit vom Klick bis zum Lebensverlust des Ziels. Anderer Schaden kann die Messung beeinflussen."},
    {"Show item icon", "Item-Symbol anzeigen"},
    {"Show item name", "Item-Namen anzeigen"},
    {"Disable inventory hotbar shortcuts", "Hotbar-Tasten im Inventar ausschalten"},
    {"Separate self and opponent colors", "Eigene und Gegnerfarben getrennt einstellen"},
    {"Uses the actor shader to apply separate local damage colors.", "Wendet getrennte lokale Schadensfarben über den Entity-Shader an."},
    {"Color yourself", "Dich selbst einfärben"},
    {"Your hurt color", "Deine Schadensfarbe"},
    {"Color other entities", "Andere Entities einfärben"},
    {"Opponent hurt color", "Gegner-Schadensfarbe"},
    {"Used when separate colors are enabled.", "Gilt bei aktivierten getrennten Farben."},
    {"Used when separate colors are enabled. Includes players and mobs.", "Gilt bei getrennten Farben. Betrifft Spieler und Mobs."},
    {"Also used as the shared color when separate colors are disabled.", "Gilt auch als gemeinsame Farbe, wenn getrennte Farben ausgeschaltet sind."},
    {"Opens inventory menus without Minecraft's screen transition animation. Server response times stay unchanged.", "Öffnet Inventarmenüs ohne Minecrafts Übergangsanimation. Server-Antwortzeiten bleiben unverändert."},
    {"Minecraft screen animations", "Minecraft-Menüanimationen"},
    {"Module faulted; restart Minecraft before trying again.", "Das Modul hatte einen Fehler. Starte Minecraft vor einem erneuten Versuch neu."},
    {"Adjust the Minecraft UI to the nearest supported scale.", "Passt die Minecraft-Oberfläche an die nächstmögliche unterstützte Größe an."},
    {"Adds smooth hand sway when looking and jumping.", "Fügt sanfte Handbewegungen beim Umsehen und Springen hinzu."},
    {"Customize your nametag colors", "Farben deines eigenen Nametags anpassen"},
    {"Only your own nametag changes. Other players keep their original colors.", "Nur dein eigener Nametag wird verändert. Andere Spieler behalten ihre Originalfarben."},
    {"Enable Customize your nametag colors to apply this color.", "Aktiviere die Farbanpassung deines eigenen Nametags, um diese Farbe anzuwenden."},
    {"Hide HUD and hotbar", "HUD und Hotbar ausblenden"},
    {"Move head with camera", "Kopf mit Kamera mitbewegen"},
    {"Local world", "Lokale Welt"},
    {"No server address", "Keine Serveradresse"},
    {"Show status", "Status anzeigen"},
    {"Waiting for world and dimension data before adding waypoints.", "Warte auf Welt- und Dimensionsdaten, bevor Wegpunkte hinzugefügt werden."},
    {"Entity", "Entität"},
    {"Separate X/Y sensitivity is unavailable; uniform sensitivity is used.", "Getrennte X/Y-Empfindlichkeit ist nicht verfügbar; einheitliche Empfindlichkeit wird verwendet."},
    {"Separate X and Y sensitivity", "Getrennte X- und Y-Empfindlichkeit"},
    {"Horizontal sensitivity", "Horizontale Empfindlichkeit"},
    {"Vertical sensitivity", "Vertikale Empfindlichkeit"},
    {"Override native colors", "Originalfarben überschreiben"},
    {"Infinite", "Unbegrenzt"},
    {"The Flarial core is not running, so this module's settings are not available.", "Der Flarial-Kern läuft nicht; die Einstellungen dieses Moduls sind nicht verfügbar."},
    {"rainbow", "Regenbogen"},
    {"Frame intervals: %.2f ms average, %.2f ms P95, %.2f ms P99", "Frame-Abstände: %.2f ms Mittelwert, %.2f ms P95, %.2f ms P99"},
    {"GPU latency mode", "GPU-Latenzmodus"},
    {"On + NVIDIA Boost", "Ein + NVIDIA Boost"},
    {"GPU latency unavailable", "GPU-Latenzsteuerung nicht verfügbar"},
    {"GPU latency off", "GPU-Latenzsteuerung aus"},
    {"NVIDIA driver latency active; input pacing not connected", "NVIDIA-Treiberlatenz aktiv; Eingabe-Timing noch nicht angebunden"},
    {"GPU pacing connected before input", "GPU-Timing vor der Eingabe angebunden"},
    {"GPU latency driver rejected the request", "GPU-Treiber hat die Latenzanfrage abgelehnt"},
    {"AMD Anti-Lag 2 needs a verified frame start hook", "AMD Anti-Lag 2 benötigt einen geprüften Frame-Start-Hook"},
    {"Driver error: %d", "Treiberfehler: %d"},
    {"Click event to Present return: %.1f ms (%d samples)", "Klickereignis bis Present-Rückkehr: %.1f ms (%d Messwerte)"},
    {"This does not measure input to the displayed image.", "Dies misst nicht die Zeit bis zum angezeigten Bild."},
    {"Custom nametag overlay", "Eigenes Nametag-Overlay"},
    {"Makes end crystals easier to see and hit: no spin and bobbing, no base, optionally hidden the moment you hit them. Client side only, sends nothing extra.", "Macht End-Crystals leichter sichtbar und treffbar: kein Drehen und Wippen, kein Sockel, auf Wunsch sofort weg, wenn du sie triffst. Nur clientseitig, sendet nichts Zusätzliches."},
    {"No spin and bobbing", "Kein Drehen und Wippen"},
    {"Hide the bedrock base", "Bedrock-Sockel ausblenden"},
    {"Hide when hit", "Beim Treffen ausblenden"},
    {"Format ({label} {value})", "Format ({label} {value})"},
    {"1.8-style sword blocking pose while you hold right click, with the swing on top.", "Schwert-Blockpose im 1.8-Stil, solange du die rechte Maustaste hältst, mit Schwung obendrauf."},
    {"Pose strength", "Pose-Stärke"},
    {"Hold the item lower", "Item tiefer halten"},
    {"Hides an end crystal on your screen the moment you hit it, so the next placement feels faster. Client side only, sends nothing extra.", "Blendet einen End-Crystal auf deinem Bildschirm aus, sobald du ihn triffst, damit sich das nächste Platzieren schneller anfühlt. Nur clientseitig, sendet nichts Zusätzliches."},
    {"Some servers count crystal tweaks as an advantage. Only use it where the server rules allow it.", "Manche Server werten Crystal-Anpassungen als Vorteil. Nur nutzen, wo die Server-Regeln es erlauben."},
    {"Animations", "Animationen"},
    {"Crystal PvP", "Crystal-PvP"},
    {"Waiting for game data", "Wartet auf Spieldaten"},
    {"These modules need game data for your Minecraft version. They unlock as soon as it is available.", "Diese Module brauchen Spieldaten für deine Minecraft-Version. Sie werden freigeschaltet, sobald diese vorliegen."},
    {"Extras", "Extras"},
    {"Enabled", "Aktiv"},
    {"Disabled", "Aus"},
    {"Unavailable", "Nicht verfügbar"},
    {"Hold mode", "Halten-Modus"},
    {"Only on while the key is held", "Nur an, solange gehalten"},
    {"Keybind", "Taste"},
    {"Click, then press a key", "Klicken, dann Taste"},
    {"General", "Allgemein"},
    {"Style", "Stil"},
    {"Colors", "Farben"},
    {"Reset all", "Alles zurücksetzen"},
    {"Reset position", "Position zurücksetzen"},
    {"More modules", "Mehr Module"},
    {"MODULES", "MODULE"},
    {"Edit HUD", "HUD bearbeiten"},
    {"Appearance", "Aussehen"},
    {"All modules", "Alle Module"},
    {"unknown", "unbekannt"},
    {"Modules", "Module"},
    {"Appearance", "Aussehen"},
    {"Profiles", "Profile"},
    {"Settings", "Einstellungen"},
    {"All", "Alle"},
    {"Style options", "Stil-Optionen"},
    {"Hide style options", "Stil-Optionen ausblenden"},
    {"Background", "Hintergrund"},
    {"Background color", "Hintergrundfarbe"},
    {"Text color", "Textfarbe"},
    {"Accent color for labels", "Akzentfarbe für Beschriftung"},
    {"Corner radius", "Eckenradius"},
    {"Padding", "Innenabstand"},
    {"Text shadow", "Textschatten"},
    {"Size", "Größe"},
    {"Visual", "Visuell"},
    {"Comfort", "Komfort"},
    {"Fun", "Spaß"},
    {"Key", "Taste"},
    {"Module disabled", "Modul abgeschaltet"},
    {"Not allowed on this server.", "Auf diesem Server nicht erlaubt."},
    {"Measures frame time and the time from click to the next frame. Use it to compare settings.", "Misst Frametime und die Zeit vom Klick bis zum nächsten Bild. Zum Vergleichen von Einstellungen."},
    {"Click to frame {:.1f} ms", "Klick → Bild {:.1f} ms"},
    {"Click to frame: click once", "Klick → Bild: klick mal"},
    {"{}  ·  {}  ·  {} buffered", "{}  ·  {}  ·  {} Puffer"},
    {"Low latency on", "Low-Latency an"},
    {"Low latency off", "Low-Latency aus"},
    {"VSync/default", "VSync/Standard"},
    {"Flash test (white square on click)", "Flash-Test (weißes Quadrat bei Klick)"},
    {"Shows which server you are on.", "Zeigt, auf welchem Server du gerade bist."},
    {"Single player", "Einzelspieler"},
    {"Display", "Anzeige"},
    {"Address", "Adresse"},
    {"Only show on servers", "Nur auf Servern anzeigen"},
    {"Shows WASD, space and the mouse buttons live.", "Zeigt WASD, Leertaste und Maustasten live an."},
    {"Key size", "Tastengröße"},
    {"Mouse buttons", "Maustasten"},
    {"CPS in mouse buttons", "CPS in Maustasten"},
    {"Space", "Leertaste"},
    {"Key pressed", "Taste gedrückt"},
    {"Text pressed", "Text gedrückt"},
    {"Forward", "Vorwärts"},
    {"Left", "Links"},
    {"Back", "Rückwärts"},
    {"Right", "Rechts"},
    {"Jump", "Springen"},
    {"Shows your mouse movement as a dot with a trail.", "Zeigt deine Mausbewegung als Punkt mit Spur."},
    {"Sensitivity", "Empfindlichkeit"},
    {"Dot color", "Punktfarbe"},
    {"Shows how much RAM Minecraft is using.", "Zeigt, wie viel RAM Minecraft gerade nutzt."},
    {"How long you have been playing, in total or on the current server.", "Wie lange du schon spielst – gesamt oder auf dem aktuellen Server."},
    {"Counts", "Zählt"},
    {"Since game start", "Seit Spielstart"},
    {"Since joining the server", "Seit Server-Beitritt"},
    {"Shows your frames per second.", "Zeigt deine Bilder pro Sekunde."},
    {"Show 1% low", "1% Low anzeigen"},
    {"Update interval (s)", "Aktualisierung (s)"},
    {"Stopwatch with its own start/stop and reset keys.", "Stoppuhr mit eigener Start/Stopp- und Reset-Taste."},
    {"Time", "Zeit"},
    {"Start / stop", "Start / Stopp"},
    {"Reset", "Zurücksetzen"},
    {"Counts your clicks per second.", "Zählt deine Klicks pro Sekunde."},
    {"Left | Right", "Links | Rechts"},
    {"Left only", "Nur links"},
    {"Right only", "Nur rechts"},
    {"Shows the current time.", "Zeigt die aktuelle Uhrzeit."},
    {"12-hour format", "12-Stunden-Format"},
    {"Seconds", "Sekunden"},
    {"Date", "Datum"},
    {"Custom crosshair: cross, dot, circle or heart, with color, outline and click effect.", "Eigenes Fadenkreuz: Kreuz, Punkt, Kreis oder Herz, mit Farbe, Umriss und Klick-Effekt."},
    {"Shape", "Form"},
    {"Cross", "Kreuz"},
    {"Dot", "Punkt"},
    {"Circle", "Kreis"},
    {"Cross + dot", "Kreuz + Punkt"},
    {"Heart", "Herz"},
    {"Gap", "Abstand"},
    {"Thickness", "Dicke"},
    {"Color", "Farbe"},
    {"Outline", "Umriss"},
    {"Color on click", "Farbe beim Klicken"},
    {"Click color", "Klickfarbe"},
    {"Pulse on click", "Pulsieren beim Klicken"},
    {"Snake for the queue. Arrow keys/WASD, ESC quits.", "Snake für die Warteschlange. Pfeiltasten/WASD, ESC beendet."},
    {"Snake  ·  {}  ·  Best {}", "Snake  ·  {}  ·  Rekord {}"},
    {"Space = again, ESC = quit", "Leertaste = nochmal, ESC = beenden"},
    {"A bouncing logo like the DVD screensaver.", "Ein hüpfendes Logo wie beim DVD-Bildschirmschoner."},
    {"Speed", "Tempo"},
    {"Opacity", "Deckkraft"},
    {"Reminds you every 20 minutes to look at something 20 feet (6 m) away for 20 seconds.", "Erinnert dich alle 20 Minuten, 20 Sekunden lang etwas 20 Fuß (6 m) Entferntes anzuschauen."},
    {"Eye break", "Augenpause"},
    {"Look into the distance for 20 seconds.", "Schau 20 Sekunden lang in die Ferne."},
    {"Every (minutes)", "Alle (Minuten)"},
    {"Flappy Bird with a heart. Space flies, ESC quits.", "Flappy Bird mit einem Herz. Leertaste fliegt, ESC beendet."},
    {"Flappy Heart  ·  {}  ·  Best {}", "Flappy Heart  ·  {}  ·  Rekord {}"},
    {"Space = again", "Leertaste = nochmal"},
    {"Space to start", "Leertaste zum Starten"},
    {"Limits your clicks per second, for example for servers with a CPS limit.", "Begrenzt deine Klicks pro Sekunde nach oben, z. B. für Server mit CPS-Limit."},
    {"Left max CPS", "Links max. CPS"},
    {"Right max CPS", "Rechts max. CPS"},
    {"Stops you from scrolling through the hotbar by accident.", "Verhindert, dass du aus Versehen durch die Hotbar scrollst."},
    {"Only while sneaking", "Nur beim Schleichen"},
    {"Sneak key", "Schleichen-Taste"},
    {"1 ms timer", "1-ms-Timer"},
    {"Power saving off for Minecraft", "Energiesparen für Minecraft aus"},
    {"short queue active", "kurze Warteschlange aktiv"},
    {"default queue", "Standard-Warteschlange"},
    {"tearing possible", "Tearing möglich"},
    {"tearing not allowed by the game", "Tearing vom Spiel nicht freigegeben"},
    {"Short frame queue", "Kurze Bild-Warteschlange"},
    {"Allow tearing (VSync off)", "Tearing erlauben (VSync aus)"},
    {"Custom FPS limiter", "Eigener FPS-Limiter"},
    {"FPS limit", "FPS-Limit"},
    {"The menu.", "Das Menü."},
    {"Menu key", "Menü-Taste"},
    {"Mouse left", "Maus links"},
    {"Mouse right", "Maus rechts"},
    {"Mouse wheel", "Mausrad"},
    {"Mouse 4", "Maus 4"},
    {"Mouse 5", "Maus 5"},
    {"Right Shift", "Rechts-Shift"},
    {"Left Shift", "Links-Shift"},
    {"Right Ctrl", "Rechts-Strg"},
    {"Left Ctrl", "Links-Strg"},
    {"Insert", "Einfg"},
    {"Delete", "Löschen"},
    {"Home", "Pos1"},
    {"End", "Ende"},
    {"Page up", "Bild auf"},
    {"Page down", "Bild ab"},
    {"Caps lock", "Feststell"},
    {"Press a key…", "Taste drücken…"},
    {"All modules", "Alle Module"},
    {"Edit HUD", "HUD bearbeiten"},
    {"No server", "Kein Server"},
    {"Rules: %s", "Regeln: %s"},
    {"Search modules …", "Modul suchen …"},
    {"Not available on this Minecraft version yet.", "Auf dieser Minecraft-Version noch nicht verfügbar."},
    {"Nothing found.", "Nichts gefunden."},
    {"‹ Back", "‹ Zurück"},
    {"Active", "Aktiv"},
    {"Change position in the HUD editor", "Position im HUD-Editor ändern"},
    {"Presets", "Vorlagen"},
    {"Custom theme", "Eigenes Theme"},
    {"Surfaces", "Flächen"},
    {"Surfaces (hover)", "Flächen (Hover)"},
    {"Accent", "Akzent"},
    {"Accent 2", "Akzent 2"},
    {"Dimmed text", "Text gedimmt"},
    {"Success", "Erfolg"},
    {"Warning", "Warnung"},
    {"Off", "Aus"},
    {"Animation speed", "Animationstempo"},
    {"Gradients", "Farbverläufe"},
    {"Sparkles", "Glitzer"},
    {"Little hearts", "Herzchen"},
    {"Copy theme as code", "Theme als Code kopieren"},
    {"Load code from clipboard", "Code aus Zwischenablage laden"},
    {"Each profile stores modules, settings, HUD positions and theme.", "Jedes Profil speichert Module, Einstellungen, HUD-Positionen und Theme."},
    {"%s  (active)", "%s  (aktiv)"},
    {"Load", "Laden"},
    {"New profile …", "Neues Profil …"},
    {"Create", "Anlegen"},
    {"Signatures: %d of %d found", "Signaturen: %d von %d gefunden"},
    {"Source: %s", "Quelle: %s"},
    {"%d modules are waiting for signatures for this version.", "%d Module warten auf Signaturen für diese Version."},
    {"Connected: %s", "Verbunden: %s"},
    {"Keys", "Tasten"},
    {"Ctrl+L: unload client · F1: hide HUD · ESC: back · right-click a key: clear", "Strg+L: Client entladen · F1: HUD ausblenden · ESC: zurück · Rechtsklick auf eine Taste: entfernen"},
    {"Drag = move  ·  Arrows = nudge  ·  Mouse wheel = size  ·  Double click = reset  ·  Right click = settings  ·  Shift = no snap  ·  ESC = done", "Ziehen = verschieben  ·  Pfeiltasten = fein  ·  Mausrad = Größe  ·  Doppelklick = zurücksetzen  ·  Rechtsklick = Einstellungen  ·  Shift = ohne Einrasten  ·  ESC = fertig"},
    {"Monchi loaded", "Monchi geladen"},
    {"Right Shift opens the menu.", "Rechts-Shift öffnet das Menü."},
    {"None", "keine"},
    {"Priority \"Above normal\"", "Priorität \"Höher als normal\""},
    {"Windows settings while Minecraft runs: precise timer, higher priority, no power saving. Reverted when you quit.", "Windows-Einstellungen, solange Minecraft läuft: genauer Timer, höhere Priorität, kein Energiesparen. Wird beim Beenden zurückgesetzt."},
    {"Shorter frame queue, optional tearing instead of VSync and a precise FPS limiter. Compare before and after with the Latency HUD.", "Kürzere Bild-Warteschlange, optional Tearing statt VSync und ein präziser FPS-Limiter. Mit dem Latency-HUD vorher/nachher vergleichen."},
    {"{} had an error. See the log for details.", "{} hatte einen Fehler. Details im Log."},
    {"Not allowed on {}.", "Auf {} nicht erlaubt."},
    {"{}: not explicitly allowed, use at your own risk.", "{}: nicht ausdrücklich erlaubt, Nutzung auf eigenes Risiko."},
    {"{}: blocked", "{}: gesperrt"},
    {"{}: notice", "{}: Hinweis"},
    {"{} modules blocked here.", "{} Module hier gesperrt."},
    {"{} blocked", "{} gesperrt"},
    {"{} notices", "{} Hinweise"},
    {"Language", "Sprache"},
    {"Auto follows your Windows language.", "Auto folgt deiner Windows-Sprache."},
    {"Auto", "Automatisch"},
    {"bundled", "mitgeliefert"},
    {"no signature file", "keine Signaturdatei"},
    {"Show label", "Beschriftung anzeigen"},
    {"Custom label (empty uses default)", "Eigene Beschriftung (leer nutzt Standard)"},
    {"Label position", "Position der Beschriftung"},
    {"Before value", "Vor dem Wert"},
    {"After value", "Nach dem Wert"},
    {"Label gap", "Abstand zur Beschriftung"},
    {"Click separator", "Klick-Trennzeichen"},
    {"A custom format determines the label position and spacing.", "Ein eigenes Format bestimmt Position und Abstand der Beschriftung."},
    {"Show frame time", "Framezeit anzeigen"},
    {"Show click latency", "Klick-Latenz anzeigen"},
    {"Show input timing", "Eingabezeiten anzeigen"},
    {"Show presentation mode", "Darstellungsmodus anzeigen"},
    {"Show frame graph", "Framezeit-Diagramm anzeigen"},
    {"Graph width", "Diagrammbreite"},
    {"Graph height", "Diagrammhöhe"},
    {"Graph line thickness", "Linienstärke im Diagramm"},
    {"Statistics update interval (s)", "Statistik-Aktualisierung (s)"},
    {"UI Scale", "UI-Skalierung"},
    {"mph", "mph"},
    {"CPS label position", "Position der CPS-Beschriftung"},
    {"Hidden", "Ausgeblendet"},
    {"Frame {:.2f} ms", "Frame {:.2f} ms"},
    {"Show metric labels", "Messwertbeschriftungen anzeigen"},
    {"Show metric units", "Messwerteinheiten anzeigen"},
    {"Icon position", "Symbolposition"},
    {"Icon size", "Symbolgröße"},
    {"Icon gap", "Symbolabstand"},
    {"Show song title", "Songtitel anzeigen"},
    {"Show music app", "Musik-App anzeigen"},
    {"Music app position", "Position der Musik-App"},
    {"Show playback icon", "Wiedergabesymbol anzeigen"},
    {"Scroll long titles", "Lange Titel scrollen"},
    {"Scroll speed", "Scrollgeschwindigkeit"},
    {"Kill label", "Kill-Beschriftung"},
    {"Death label", "Todes-Beschriftung"},
    {"Ratio label", "Verhältnis-Beschriftung"},
    {"Ratio decimals", "Verhältnis-Nachkommastellen"},
    {"{} (best {})", "{} (beste {})"},
    {"Metric separator", "Messwert-Trennzeichen"},
    {"Slot spacing", "Slotabstand"},
    {"Text spacing", "Textabstand"},
    {"Show durability", "Haltbarkeit anzeigen"},
    {"Show item count", "Itemanzahl anzeigen"},
    {"Icon background", "Symbolhintergrund"},
    {"Icon background color", "Symbol-Hintergrundfarbe"},
    {"System decimals", "System-Nachkommastellen"},
    {"Show plus sign", "Pluszeichen anzeigen"},
};

i18n::Table table(entries);

}
