"""List every registered module and its source wiring, without claiming runtime success."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dll/src/modules"


def matches(code, pattern):
    return sorted(set(re.findall(pattern, code)))


def inventory():
    effects_source = (ROOT / "dll/src/sdk/Effects.cpp").read_text(encoding="utf-8-sig")
    effect_names = re.findall(r'\{"(fx\.[^"]+)"', effects_source)
    enum = (ROOT / "dll/src/sdk/Effects.hpp").read_text(encoding="utf-8-sig").split("enum class Id {")[1].split("\n    Count")[0]
    effect_ids = re.findall(r"\b(\w+)\s*,", enum)
    if len(effect_ids) != len(effect_names):
        raise ValueError("Effect enum and signature table disagree")
    signatures = dict(zip(effect_ids, effect_names))
    configured = json.loads((ROOT / "sigs/1.26.52.json").read_text(encoding="utf-8-sig"))["sigs"]
    classes = {}
    for file in sorted(SOURCE.rglob("*.hpp")):
        code = file.read_text(encoding="utf-8-sig")
        declarations = list(re.finditer(r"\bclass\s+(\w+)\s*:\s*public\s+(\w+)", code))
        for i, match in enumerate(declarations):
            body = code[match.start():declarations[i + 1].start() if i + 1 < len(declarations) else len(code)]
            classes[match[1]] = (match[2], file.relative_to(ROOT).as_posix(), body)
    registered = re.findall(r"add<(\w+)>\(\)", (SOURCE / "Manager.cpp").read_text(encoding="utf-8-sig"))
    rows = []
    for name in registered:
        if name not in classes:
            raise ValueError(f"Registered class missing: {name}")
        base, file, body = classes[name]
        inherited, seen = [], {name}
        while base in classes and base not in seen:
            seen.add(base)
            inherited.append(base)
            base, _, parent = classes[base]
            body += "\n" + parent
        rows.append({
            "class": name, "source": file, "inherited": inherited,
            "effects": matches(body, r"fx::Id::(\w+)"),
            "effects_without_bundled_signature": sorted({signatures[e] for e in matches(body, r"fx::Id::(\w+)") if e in signatures and signatures[e] not in configured}),
            "domains": matches(body, r"need::(player|inventory|effects|target|world|combat|chat|board|tab|camera|others|light)\b"),
            "signature_literals": matches(body, r'"(LocalPlayer|MoveState|PlayerStats|WorldTime|Dimension|PlayerName|HurtEvents|Biome|[A-Za-z]+\.[A-Za-z]+)"'),
            "game_calls": matches(body, r"\bgame::(\w+)\s*\("),
            "callbacks": matches(body, r"\b(onFrame|onRender|onEnable|onDisable|onKey|onMouse|onServer|content|value)\s*\("),
            "verification": "source wiring only; live behavior not certified by this audit",
        })
    return rows


def main():
    rows = inventory()
    output = ROOT / "docs/MODULE_AUDIT.json"
    output.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    lines = ["# Module source audit", "", "Generated by `python tools/audit_modules.py`. Includes every statically registered module and inherited callbacks. Dynamic Flarial proxies depend on successful native-core startup and are not separate static registrations.", "", "This is a source inventory, not an in-game pass. Signature literals are a search index, not a complete constructor evaluation. Effects can be optional settings; their presence alone does not mean the whole module requires them.", "", "The native core remains blocked by the unresolved ScreenView rendering entry. GUI Scale, native movable elements and native cosmetics need verified game bindings. Post-processing depth effects, real potion icons and the 3D paperdoll still need their rendering paths. Refer to the continuation and handoff documents for specific findings.", "", "| Module class | Source | Data domains | Effects | Callbacks (including inherited) |", "|---|---|---|---|---|"]
    for row in rows:
        effects = ', '.join(row['effects']) or '—'
        missing = row['effects_without_bundled_signature']
        if missing:
            effects += "<br>Absent from bundled 1.26.52 set: " + ', '.join(missing)
        lines.append(f"| {row['class']} | [{Path(row['source']).name}](../{row['source']}) | {', '.join(row['domains']) or '—'} | {effects} | {', '.join(row['callbacks']) or '—'} |")
    lines += ["", f"Total: {len(rows)} static registrations. Every row requires an explicit live test before receiving a runtime pass.", ""]
    (ROOT / "docs/MODULE_AUDIT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Indexed {len(rows)} registered modules")


if __name__ == "__main__":
    main()
