#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Version {} is available.", "Version {} ist verfügbar."},
    {"Your settings will stay saved.", "Deine Einstellungen bleiben gespeichert."},
    {"Download", "Herunterladen"},
    {"Later", "Später"},

    {"Not checked", "Nicht geprüft"},
    {"Check for updates", "Nach Updates suchen"},
    {"Downloads", "Downloads"},
    {"Installed versions", "Installierte Versionen"},
    {"Choose a version to install or play.", "Wähle eine Version zum Installieren oder Spielen."},
    {"Not supported", "Nicht unterstützt"},
    {"Minecraft version switcher", "Minecraft-Versionswechsel"},
    {"Upgrade or downgrade using your own Microsoft license.", "Upgrade oder Downgrade mit deiner eigenen Microsoft-Lizenz."},
    {"Worlds are backed up before the installed version changes.", "Vor dem Versionswechsel werden deine Spielstände gesichert."},
    {"Browse versions", "Versionen ansehen"},
    {"Cancel", "Abbrechen"},
    {"Refresh", "Aktualisieren"},
    {"Release", "Release"},
    {"Install", "Installieren"},

    {"Monchi connects to whichever Minecraft version you start.", "Monchi verbindet sich mit jeder Minecraft-Version, die du startest."},
    {"Version manager", "Versionsverwaltung"},
    {"LeviLauncher installs and switches Minecraft versions, including older ones.", "LeviLauncher installiert und wechselt Minecraft-Versionen, auch ältere."},
    {"Free open source tool by LiteLDev (GPL-3.0). You need a legitimate Minecraft license.", "Kostenloses Open-Source-Tool von LiteLDev (GPL-3.0). Du brauchst eine eigene Minecraft-Lizenz."},
    {"Open LeviLauncher", "LeviLauncher öffnen"},
    {"Install LeviLauncher", "LeviLauncher installieren"},
    {"Detected on this PC", "Auf diesem PC gefunden"},
    {"No Minecraft installation found.", "Keine Minecraft-Installation gefunden."},
    {"Play", "Spielen"},
    {"Updating", "Aktualisiere"},
    {"Starting Minecraft", "Starte Minecraft"},
    {"Waiting for the game", "Warte auf das Spiel"},
    {"Connecting", "Verbinde"},
    {"Running", "Läuft"},
    {"Try again", "Nochmal versuchen"},
    {"Versions", "Versionen"},
    {"Settings", "Einstellungen"},
    {"About", "Über"},
    {"Update available", "Update verfügbar"},
    {"Up to date", "Alles aktuell"},
    {"Ready to play", "Bereit zum Spielen"},
    {"Minecraft not found", "Minecraft nicht gefunden"},
    {"Install it from the Microsoft Store or add a folder under Versions.", "Installiere es aus dem Microsoft Store oder füge unter Versionen einen Ordner hinzu."},
    {"Current", "Aktuell"},
    {"Missing", "Fehlt"},
    {"Supported", "Unterstützt"},
    {"Untested", "Nicht getestet"},
    {"Which Minecraft version do you want to play?", "Mit welcher Minecraft-Version möchtest du spielen?"},
    {"Installed", "Installiert"},
    {"Monchi compatible", "Monchi-kompatibel"},
    {"Pick the Minecraft version Monchi starts. It is remembered for next time.", "Wähle die Minecraft-Version, die Monchi startet. Sie wird für das nächste Mal gemerkt."},
    {"Download older versions", "Ältere Versionen laden"},
    {"LeviLauncher downloads versions with your own license.", "LeviLauncher lädt Versionen mit deiner eigenen Lizenz."},
    {"Free tool by LiteLDev (GPL-3.0). Monchi finds what it installs.", "Kostenloses Tool von LiteLDev (GPL-3.0). Monchi findet, was es installiert."},
    {"Installed on this PC", "Auf diesem PC installiert"},
    {"Rescan", "Neu suchen"},
    {"Add folder", "Ordner hinzufügen"},
    {"Not installed", "Nicht installiert"},
    {"Microsoft Store", "Microsoft Store"},
    {"Own copy", "Eigene Kopie"},
    {"In use", "In Benutzung"},
    {"Use this one", "Diese nehmen"},
    {"Active", "Aktiv"},
    {"Switch", "Wechseln"},
    {"Version switching is still in progress", "Der Versionswechsel ist noch in Arbeit"},
    {"Switching will later work through your own Microsoft license. Until then you play with the installed version.", "Das Umschalten läuft später über deine eigene Microsoft-Lizenz. Bis dahin spielst du mit der installierten Version."},
    {"How the launcher should behave.", "Wie sich der Launcher verhalten soll."},
    {"Beta updates", "Beta-Updates"},
    {"Get new versions earlier, even if they may still have bugs.", "Neue Versionen früher bekommen, auch wenn sie noch Fehler haben könnten."},
    {"Connect automatically", "Automatisch verbinden"},
    {"Connects the client as soon as Minecraft has started.", "Verbindet den Client, sobald Minecraft gestartet ist."},
    {"Close launcher afterwards", "Launcher danach schließen"},
    {"Closes this window once the client has loaded.", "Schließt dieses Fenster, sobald der Client geladen ist."},
    {"Custom DLL (for developers)", "Eigene DLL (für Entwickler)"},
    {"Leave empty for the normal version.", "Leer lassen für die normale Version."},
    {"Browse", "Suchen"},
    {"Free PvP client for Minecraft Bedrock on Windows.", "Kostenloser PvP-Client für Minecraft Bedrock auf Windows."},
    {"Monchi is an independent project and is not affiliated with Mojang or Microsoft.", "Monchi ist ein unabhängiges Projekt und gehört nicht zu Mojang oder Microsoft."},
    {"The client only adds helpful displays and gives no unfair advantage.", "Der Client zeigt nur Hilfen an und gibt keine unfairen Vorteile."},
    {"Your antivirus may warn about injectors. That is normal, only download from the official page.", "Dein Antivirus kann bei Injektoren warnen. Das ist normal, lade nur von der offiziellen Seite."},
    {"Open logs", "Logs öffnen"},
    {"Open folder", "Ordner öffnen"},
    {"Home", "Start"},
    {"not found", "nicht gefunden"},
    {"Update to {}", "Auf {} aktualisieren"},
    {"What's new in {}", "Neu in {}"},
    {"Language", "Sprache"},
    {"Auto follows your Windows language.", "Auto folgt deiner Windows-Sprache."},
    {"Auto", "Automatisch"},
    {"Accent color", "Akzentfarbe"},
    {"Same choice as in the client menu.", "Die gleiche Auswahl wie im Client-Menü."},
    {"Blue", "Blau"},
    {"Cyan", "Cyan"},
    {"Green", "Grün"},
    {"Purple", "Lila"},
    {"Pink", "Rosa"},
    {"Red", "Rot"},
    {"Orange", "Orange"},
    {"Gray", "Grau"},
    {"Cosmetics", "Cosmetics"},
    {"What you wear in the game. Drag the figure to turn it.", "Was du im Spiel trägst. Zieh die Figur, um sie zu drehen."},
    {"The skin you wore last in the game", "Der Skin, den du zuletzt im Spiel getragen hast"},
    {"Your skin shows here after one game with Monchi", "Dein Skin erscheint hier nach einer Runde mit Monchi"},
    {"Minecraft is running: change cosmetics in the game menu, or close the game.", "Minecraft läuft: Cosmetics im Menü im Spiel ändern oder das Spiel schließen."},
    {"Start the game once with Monchi, then cosmetics can be picked here.", "Starte das Spiel einmal mit Monchi, dann lassen sich Cosmetics hier wählen."},
    {"No cosmetics found.", "Keine Cosmetics gefunden."},
    {"Boy", "Junge"},
    {"Girl", "Mädchen"},
    {"The skin picked in Minecraft", "Der in Minecraft gewählte Skin"},
    {"Marketplace skin: yours shows after one game", "Marketplace-Skin: deiner erscheint nach einer Runde"},
    {"wings", "Flügel"},
    {"cape", "Umhang"},
    {"head", "Kopf"},
    {"face", "Gesicht"},
    {"back", "Rücken"},
    {"body", "Körper"},
    {"waist", "Schweif"},
    {"feet", "Füße"},
    {"aura", "Aura"},
    {"pet", "Begleiter"},
};

i18n::Table table(entries);

}
